### ISSUE TITLE
Add NATS input and output options to the telegraf image

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#102]
the goal is to be able to substitute NATS for Kafka, for the metrics it means having an input for telemetry worker and an output for telegraf-agent.

**Comment by chrisccoy** [comment]
All seems good, but I have not found a good output solution for how to go from `telegraf->NATS`

https://github.com/influxdata/telegraf/issues/148

**Comment by subfuzion** [comment]
@chrisccoy Focus on implementing our own telegraf plugin. This can be shared with the community as an open source contribution.

**Comment by subfuzion** [comment]
This issue is a sub-task of #113

**Comment by bquenin** [comment]
We can probably close this issue.
