### ISSUE TITLE
Cluster deploy on LInux failed

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#1024]
Executing hack/deploy on Ubuntu, i got the swarm dns issue we got previously:
- most of the time, not always, kibana don't find elasticsearch (which is well there)
- if kibana is ok, then agents don't find nats
then we got the message : "final service replicat smoke test failed exit 1"
and the cluster stops

looking logs and going into the containers, kibana or agent don't ping Elasticsearch or Nats respectively

**Comment by ndegory** [comment]
is Swarm initialized on your Linux? If not, what is the result of `sudo lsmod | grep ip_vs`?

**Comment by freignat91** [comment]
using command `sudo modprobe ip_vs`the issue is solved, closing the issue
