### ISSUE TITLE
Point cloud.atomiq.io at proper server

### ISSUE THREAD

**Issue by ingo** [appcelerator-archive/amp#1036]
It doesn't appear that cloud.atomiq.io is pointed at a proper server. It should at least have a web page to describe it, or if the service isn't running, we should create it somewhere.

**Comment by ndegory** [comment]
we can configure the main proxy of the cluster with base domain cloud.atomiq.io to default to a service serving a web page with information about this cluster (ULA, basic usage guidance, etc).
