### ISSUE TITLE
Correct copyright on http://atomiq.io

### ISSUE THREAD

**Issue by ingo** [appcelerator-archive/amp#1037]
Current copyright on atomiq.io is incorrect (as Atomiq is not a proper legal entity)

Copyright © 2016-2017 Atomiq and contributors => Copyright © 2016-2017 Axway

I'm unable to file an issue against the atomiq.io website, so filing it here. Please move as appropriate.

**Comment by subfuzion** [comment]
Done.

**Comment by ingo** [comment]
I meant to indicate replacing one phrase with the other. Will correct in a PR.

**Comment by bquenin** [comment]
I think #1076 resoles this issue.
