### ISSUE TITLE
Add CLA workflow to pull requests

### ISSUE THREAD

**Issue by ingo** [appcelerator-archive/amp#1038]
To make it easy (and legal) for people to contribute to the project, we need to ask them to sign a CLA.

To implement this workflow is simple:

* Add a new webhook under "Settings > Webhooks & Services" for "https://cla.appcelerator.com/webhook"
* Set the content type as "application/json"
* Select individual events and select "Pull Request"
* Click "Add Webhook"

Furthermore, you can enable branch protection and require that this check pass.

For questions about why a CLA is important, Github has a nice explanation.

https://cla.github.com/

**Comment by subfuzion** [comment]
Done:

Webhook:
https://github.com/appcelerator/amp/settings/hooks

Branch protection:
https://github.com/appcelerator/amp/settings/branches/master
