### ISSUE TITLE
Change the user token life-cycle

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#1048]
Right now,  the user token expires after 24 hours and then the user should signup again with the whole email validation process to get a new token.

It could better to change that: 
- The user gets a token witch expires after 24 hours too, but instead to force the user to signup again, when the server see that the token has expired, it just logs out the user to force him to re-logs in, then it creates a new token on the fly for the user. The email haven't changed, no need to revalidate it.
- during the validity period of the token, the user should log in once and then the token should be enough until it expires. So the user should log in at least every 24 hours.

This way the user see that the token has expired, because he has to re-log on the server, we could have a clear message explaining that, but he doesn't need to sign-up again. On its side the server can change on regular basis the user token in transparent way.

It'll especially useful for the ui, very few sites force a user to re-sign-up every day with email validation.

**Comment by bquenin** [comment]
Actually, you only need to `amp login` after 24 hours. Not the whole signup process.
We can extend the validity of the token to more than 24 hours if required.

**Comment by freignat91** [comment]
ok, perfect so
