### ISSUE TITLE
Create amp service to manage project

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#105]
We need to define that is a project, a set of user services as a stack?
or more than a stack?

**Comment by subfuzion** [comment]
I'm working on this one, @freignat91. I put the branch on hold for the demo and because I'm still dockerizing the makefile. One step to go.

**Comment by freignat91** [comment]
For what i understood from our discussions until now, a project is:
- a set of services
- a set of networks
  for instance we can have 'frontend' and 'backend' networks with several services inside each.
