### ISSUE TITLE
option to bypass the user signup workflow when working locally

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#1055]
When deploying a cluster locally for development purposes the email workflow is cumbersome and not most of the time not necessary.
It should be possible to disable that workflow:
```
$ amp cluster create --server=localhost --disable-email
$ amp user signup
[...]
# no email sent, implicit user verification
$ amp login
```

**Comment by bquenin** [comment]
We actually could bypass user email verification locally if `amplifier` knows it's working locally. It relates to #1018.
In that case, i.e. if `amplifier` public endpoint is `localhost` or `127.0.0.1`, we could verify users by default.

**Comment by subfuzion** [comment]
This was one of the alternate flows I specified [here](https://docs.google.com/document/d/15PXo7nPESxZZaAJpaBAbiD6b3aIbXTLQmXiWLzuGSrw/edit#heading=h.u28l6el329jm). What I'm looking is similar to what Nicolas proposed above, except it's a more general solution, which is the ability to specify a registration and verification strategy for different environments. Over time, these strategies should be pluggable, plus you should be able to specify multiple strategies (eg, email + SMS). So using Nicolas' example, it's not about disabling email (which maybe we leave as the default), it's about specifying a strategy, such as `--registration=none` or `--registration=email --registration=sms` etc.

**Comment by bquenin** [comment]
ok sure. I'll work on it once we'll have specify how strategies are enabled, configured, combined, etc. Just to make sure we're aligned.

**Comment by subfuzion** [comment]
Thanks @bquenin
