### ISSUE TITLE
CLI settings

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#1056]
Currently the AMP CLI requires option -s at each call, and defaults to cloud.atomiq.io.

- The Docker CLI uses the -H option to specify the remote server
- The Docker CLI checks a few environment variables:
  - DOCKER_CONFIG The location of your client configuration files.
  - DOCKER_CERT_PATH The location of your authentication keys.
  - DOCKER_HOST Daemon socket to connect to.
  - DOCKER_TLS_VERIFY When set Docker uses TLS and verifies the remote.
  - HTTP_PROXY
  - HTTPS_PROXY
  - NO_PROXY

AMP could behave similarly:

- by default AMP tries to connect to a local cluster (127.0.0.1:50101)
- AMP checks these environment variables:
  - AMP_CONFIG The location of your client configuration files.
  - AMP_CERT_PATH The location of your authentication keys.
  - AMP_HOST amplifier grpc endpoint to connect to.
  - AMP_TLS_VERIFY When set Docker uses TLS and verifies the remote.
  - HTTP_PROXY
  - HTTPS_PROXY
  - NO_PROXY

**Comment by bquenin** [comment]
Put as a comment in #1083
