### ISSUE TITLE
CLI - server TLS connection

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#1058]
> The connection between the amp CLI and amplifier is not secured by default.
> We already can add TLS termination on the amp stack, but the CLI should be modified to allow TLS.
> It can be TLS by default and fallback to non TLS if it's unavailable, and it can also use an option to force or disable mutual auth.

What needs to be done on `amplifier`:
- TLS should be enabled by default.
- `amplifier` will use the certificate located in `certificate_atomiq` docker secret.

What needs to be done on `amp` CLI:
- Enable TLS connection by default to amplifier.
- Add an option to skip certificate verification, for instance `-k` as in curl.

What needs to be done on `amplifier-gateway`:
- Update the gateway to use a TLS connection to amplifier if the server is using it.

The UI is not impacted as it's talking to the `amplifier-gateway` only.

**Comment by bquenin** [comment]
@subfuzion @ndegory What's the target for amplifier deployment ? Is it going to sit behind a proxy or is it going (like today) to be exposed directly?

**Comment by ndegory** [comment]
for local deployment you'll only get a self signed certificate, so if that breaks the connection between the CLI and amplifier, we'll still need a non encrypted connection. There's a way to do that with haproxy, because we have port 80 and 443 exposed, so we can establish the connection with or without TLS, and we can get rid of the non standard port (50101).

**Comment by bquenin** [comment]
I'm not sure to understand. For local deployment, I can add an option to the CLI to ignore TLS errors (such as `curl -k`) in case of self signed certificates.
But the idea is to have TLS for local/cloud deployment. Not a clear connection anymore.

**Comment by ndegory** [comment]
that would be great!
But we'd probably also should keep a --disable-tls on the CLI side, for tests purposes.

**Comment by bquenin** [comment]
Sure.
So does it mean the target is to deploy `amplifier` behind our proxy? Or do we keep it facing the internet directly? (It has impacts on how to bundle the server certificate)

**Comment by subfuzion** [comment]
We're still working this out right now, can provide more detail tomorrow.

**Comment by ndegory** [comment]
I would say behind the proxy, but that's an open debate

**Comment by bquenin** [comment]
Please check https://github.com/docker/dockercloud-haproxy/issues/6
