### ISSUE TITLE
Multiple signup/verification strategies

### ISSUE THREAD

**Issue by bquenin** [appcelerator-archive/amp#1100]
From #1055
> This was one of the alternate flows I specified [here](https://docs.google.com/document/d/15PXo7nPESxZZaAJpaBAbiD6b3aIbXTLQmXiWLzuGSrw/edit#heading=h.u28l6el329jm). What I'm looking is similar to what Nicolas proposed above, except it's a more general solution, which is the ability to specify a registration and verification strategy for different environments. Over time, these strategies should be pluggable, plus you should be able to specify multiple strategies (eg, email + SMS). So using Nicolas' example, it's not about disabling email (which maybe we leave as the default), it's about specifying a strategy, such as `--registration=none` or `--registration=email --registration=sms` etc.

**Comment by bquenin** [comment]
@subfuzion For `--registration=*`, I assume we need to pass these parameters to `amplifier`. Should we use a configuration file or actual CLI parameters or something else?

**Comment by ndegory** [comment]
@bquenin I would say variables at the service definition level, that's the way we're able to customize a deployment right now.

**Comment by bquenin** [comment]
Fixed by #1162 
We can discuss additional registration policies with another issue.
