### ISSUE TITLE
AMP networking

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#112]
`amplifier` should expose its services on an overlay network (for example, `amp-public`), that is distinct from the backbone network (`amp-swarm`). `haproxy` should be incorporated for mapping exposed IPs to consumers, such as the CLI.

**Comment by freignat91** [comment]
ok, so we need to have a REST proxy to handle the grpc call upstreams
So HAPRoxy will work on two network and the http requests for amplifier will be routed as normal one through the REST Proxy.
It is what you want?

**Comment by freignat91** [comment]
ok, i'm trying first to reverse proxy the grpc connection it-self, so in order:
- create networt amp-public
- create service amplifier using amp-public
- add HAProxy setting to reverse-proxy amplifier grpc connections

**Comment by freignat91** [comment]
Created a branch "haproxy".
tested ok using amp localhost
tested ok with amp on aws and amp command on local machine.
i will soon create a PR
