### ISSUE TITLE
Improper use of user's home directory for storing settings

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#1153]
Various services are storing configuration settings in the user's home directory under ~/.config, creating root-owned directories (including ~/.config itself if it didn't already exist). These subdirectories include `amp` and `infrakit` and files like `amplifier.yml`.

We should stick to appropriate [FHS](http://www.pathname.com/fhs/pub/fhs-2.3.html) conventions as much as possible. For example, we should consider storing static application files in `/opt/amp` and variable data in `/var/opt/amp`.

**Comment by ndegory** [comment]
it used to be the case with our earlier experiments on InfraKit, but I think we got rid of all those ~/.config/ folders (it now runs in a container, with a data volume mounted on /infrakit). Did you notice it recently?

**Comment by subfuzion** [comment]
It could be a left over artifact, but nevertheless, my main point is to ensure we clean up anything that is creating/storing any data under home that isn't based on the user's personal CLI preferences.

**Comment by subfuzion** [comment]
The directory was created for `~/.config/infrakit/certs` two and a half weeks ago. It's good that we're no longer doing that for infrakit. We need to update amplfier and ensure everyone is aware going forward.

**Comment by ndegory** [comment]
I see, it may still happen for this particular folder, we don't need it anymore so I'll remove that code.

**Comment by bquenin** [comment]
Fixed by #1175
