### ISSUE TITLE
Local deployment on local Swarm manager node

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#1190]
A default deployment mode that relies on the host being a swarm manager and doesn't use Docker-in-Docker to build a swarm cluster, and doesn't require pushing images to the local swarm cluster. The current local cluster mode that relies on InfraKit and creates a full isolated cluster using DinD can remain an option.
This is a prerequisite for the Windows CLI, so it may be possible to provide a Window CLI with this release or otherwise the next one.

**Comment by subfuzion** [comment]
Note that while this issue is still valid as a performance enhancement during development, it's no longer necessary specifically for Windows. Docker for Windows now supports mounting the docker socket.
