### ISSUE TITLE
bad behavior on amp user rm

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#1203]
if  user owner of an organization is deleted, then the error message is the following
`amp user rm freignat -s localhost`
`Error: organization must have at least one owner`

Which is ok, but then the user is not log anymore and we need to login again
Considering the error, the user shouldn't be logged out in order to immediately allow the user to act on amp and manage his organization.

**Comment by neha-viswanathan** [comment]
Unable to reproduce this issue anymore.
