### ISSUE TITLE
High IO wait on worker nodes

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#1215]
On a cluster running for several weeks with a few stacks on it, IO wait is getting high on a few worker nodes.
Significant CPU usage from the nats container but the clear winner is the agent container responsible of 99% of disk usage, continuously.
```
Total DISK READ :       0.00 B/s | Total DISK WRITE :     455.14 K/s
Actual DISK READ:       0.00 B/s | Actual DISK WRITE:     227.57 K/s
  TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN      IO    COMMAND
 9842 be/4 root        0.00 B/s  227.57 K/s  0.00 % 99.99 % agent
 9837 be/4 root        0.00 B/s  227.57 K/s  0.00 % 99.99 % agent
```

**Comment by ndegory** [comment]
@freignat91 is it fixed by #1223?

**Comment by subfuzion** [comment]
@ndegory You should probably be the one to verify that #1223 with the current settings has improved performance in our cloud environment. I would recommend that you close, not @freignat91.

**Comment by ndegory** [comment]
so far so good, closing the issue.
