### ISSUE TITLE
Dedicated nodes for core services

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#1218]
we should be able to allocate nodes for services like elasticsearch, etcd or nats
That means:
- adding a placement constraint on each core service definition, based on node labels
- adding all the labels to the cluster
  - that means that for local deployments (dnd or single node) we should make sure that all labels are set

A list of predefined labels can be:
- amp.type.mq (nats)
- amp.type.kv (etcd)
- amp.type.search (elasticsearch)
- amp.type.api (amplifier)
- amp.type.metrics
- amp.type.route (haproxy)
- amp.type.core (all other core services)
- amp.type.user (for non core services)

This way we can get rid of the node.role == worker, now we got a better mechanism to orchestrate the services.

**Comment by bquenin** [comment]
nats streaming is not able to scale yet.

**Comment by ndegory** [comment]
@bquenin right, but we still should allocate a dedicated server to it, which allow us to fine tune the server to the needs of the nats streaming server (i.e. iops if configured to do persistency on disk).

**Comment by subfuzion** [comment]
Yes, the goal here is to isolate core infrastructure services to dedicated nodes optimized for the specific performance requirements of the particular service. This will give us an opportunity to better analyze critical service performance on dedicated notes as well as overall system performance. While ideally most stateless workers can be distributed to any worker node, this is a pragmatic attempt to tune the system around core critical services that all involve storage (including NATS for durability), and need to perform as optimally and be as reliable as possible.
