### ISSUE TITLE
Browser experience on UI for local deployment should be easier

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#1220]
The steps to make the UI work on a local deployment are too complex (involves the clipboard and the KeyChain Access tool).
At most, it should be a single click on the browser to validate a local certificate.

**Comment by bquenin** [comment]
We should maybe stick to `http` instead of `https` for local experience. What do you think?

**Comment by ndegory** [comment]
that would be the easy solution

**Comment by ndegory** [comment]
the change in #1222 doesn't seem to improve that much the experience: it still should be added in a trusted store, just accepting the certificate in Chrome is not enough.

**Comment by ndegory** [comment]
One thing to consider: TLS is forced on the service depending on the value of the FORCE_SSL environment variable. If set to 1, TLS is forced. We should consider variabilizing it, setting it to 0 for local deployments.
