### ISSUE TITLE
Portal cleanup (followup of #1209)

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#1221]
gtw.yml
```
+      io.amp.role: "infrastructure"
+    environment:
+      - "SERVICE_PORTS=80"
+      - "VIRTUAL_HOST=https://gw.*"
```
you don't need redirection from http to https?

gtw.yml
```
+      - "SERVICE_PORTS=80"
+      - "VIRTUAL_HOST=https://gw.*"
+    ports:
+      - "8080:80"
```
do you need to expose on port 8080?

gtw.yml
```
+      - "VIRTUAL_HOST=https://gw.*"
+    ports:
+      - "8080:80"
+    deploy:
```
we should add a placement constraint to restrict it on the worker nodes (see other stack files)

api/rpc/stats/stats.proto
```
-  MetricsIOEntry io = 14;
-  MetricsMemEntry mem = 15;
-  MetricsNetEntry net = 16;
+  string sgroup = 13;
```
shouldn't we add new fields at the end, instead of breaking the ids?

pkg/docker/docker.go
```
@@ -155,6 +158,7 @@ func (d *Docker) StackList(ctx context.Context) (output string, err error) {
 	return string(output), nil
 }
 
+// StackRemove remoce a stack
```
s/remoce/remove/

platform/stacks/portal.stack.yml
```
+services:
+
+  portal:
+    image: appcelerator/amp-ui:1.0.0
```
we started aligning the versions of the artifacts. Please use the "${TAG:-0.10.1}" version as for other core services.

platform/stacks/portal.stack.yml
```
+    image: appcelerator/amp-ui:1.0.0
+    networks:
+      - default
+    deploy:
```
should contain a placement constraint too

Please also remove portal/.DS_Store, it contains a binary

**Comment by ndegory** [comment]
that can help you avoiding the issue with the DS_Store folder:
```
$ cat ~/.gitignore
.DS_Store
*.pem
*.bak
*~
```

**Comment by freignat91** [comment]
ok, addressed on a new pr
