### ISSUE TITLE
[UX enhancements] amp stack rm

### ISSUE THREAD

**Issue by neha-viswanathan** [appcelerator-archive/amp#1227]
Include the following output on the CLI when a stack is removed -
```
    $ amp stack rm counter
    [localhost:50101]
    Removing stack counter 
    Stopping services:
    Service go has been successfully stopped.    ← Should block until ready
    Service redis has been successfully stopped. ← Should block until ready

    Stack counter has been successfully removed.
```

**Comment by freignat91** [comment]
Unfortunately, what we have done with out previous stack management when we handled ourselves stacks is not possible with the docker one.
Docker didn't provide api verbs to manage stack. It only provide CLI commands. We have forked Docker code to make them usable by our api, but we can control the inner work of the command.
Especially, we can't wait at each service. We can act before and after that's all.

It seems that starting docker 17.05.1-ce we could have official option to have command synchronize, so then we could answer to issue at least for the 'wait between service' part
