### ISSUE TITLE
[UX enhancements] amp stack deploy

### ISSUE THREAD

**Issue by neha-viswanathan** [appcelerator-archive/amp#1228]
- Should probably be blocking by default and optionally asynchronous
- Should display, if images need to be pulled, the status of pulling
- Should display meaningful information like:
```
$ amp stack deploy -c counter.yml 
[localhost:50101]
Deploying stack counter using counter.yml.
Pulling images:
Image htilford/go-redis-counter:latest has been successfully pulled.
Image redis:1.2.3 already in cache.

Starting services:
Service go has been successfully started.	← Should block until ready
Service redis has been successfully started.	← Should block until ready

Stack counter has been successfully deployed.
See `amp service --help` for additional information on services.
The service go is accessible at https://go.counter.local.appcelerator.io/
The service redis is accessible at https://redis.counter.local.appcelerator.io/
```

- On redeploying an existing stack, it would be helpful to see that both stack and associated services are being updated:
```
$ amp stack deploy -c counter.yml 
[localhost:50101]
Redeploying stack counter using counter.yml.
Pulling images:
Image htilford/go-redis-counter:latest already in cache.
Image redis:latest has been successfully pulled.

Updating services:
Service redis has been successfully updated from tag `1.2.3` to `latest`.

Stack counter has been successfully redeployed.
```

**Comment by freignat91** [comment]
Unfortunately, what we have done with out previous stack management when we handled ourselves stacks is not possible with the docker one. 
Docker didn't provide api verbs to manage stack. It only provide CLI commands. We have forked Docker code to make them usable by our api, but we can control the inner work of the command.
Especially, we can't wait at each service. We can act before and after that's all.

It seems that starting docker 17.05.1-ce we could have official option to have command synchronize, so then we could answer to issue at least for the 'wait between service' part
