### ISSUE TITLE
DockerHub automated builds aren't working for the project 'amp-agent'

### ISSUE THREAD

**Issue by bquenin** [appcelerator-archive/amp#124]
The automated builds aren't working. Please check https://hub.docker.com/r/appcelerator/amp-agent/builds/

I didn't find a way to fix the problem. Even deleting the project and recreating it doesn't work.

**Comment by freignat91** [comment]
Same issue with haproxy  docker hub project. No way to build it with success anymore.

**Comment by ndegory** [comment]
The build issue is related to the vendor folder:
Checking out files: 100% (15955/15955), done.
No submodule mapping found in .gitmodules for path 'vendor/github.com/Microsoft/go-winio'
please ensure the correct public key is added to the list of trusted keys for this repository and the remote branch exists. (1)

**Comment by subfuzion** [comment]
@bertrand-quenin @ndegory @freignat91

This requires the same fixes I did for docker-haproxy. See my commits on September 25: https://github.com/appcelerator/docker-haproxy/commits/master

You need to explicitly remove all the cached submodules stored in the repo (not the vendor directory), although the path you specify for the submodule is under vendor. Try this:

```
git rm --cached vendor/github.com/Microsoft/go-winio
```

Then push and look at the logs. If there are any other cached submodules, you'll need to do the same for each. Ultimately, the automated build will succeed, as you can see [here](https://hub.docker.com/r/appcelerator/haproxy/builds/).

**Comment by ndegory** [comment]
works like a charm, thanks for the tip @subfuzion

**Comment by freignat91** [comment]
it seems that amp-agent doesn't work after this update. See amp-agent log:
amp-agent version:  build: 
Configuration:
Docker-engine: unix:///var/run/docker.sock
Kafka host: kafka:9092
Connected to Kafka
Kafka topic available amp-logs
Kafka producer successfuly created
Connected to Docker-engine
Extracting containers list...
Container inspect error: error during connect: Get https://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/8996b5db6dfe3f0a79a44fa9481e1a45c136abb3c038ca79baca8a3f872a6f0c/json: http: server gave HTTP response to HTTPS client
Container inspect error: error during connect: Get https://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/daa7fbe407499b0e74c12e62530e402a56e48af30675f916077124db9496c536/json: http: server gave HTTP response to HTTPS client
Container inspect error: error during connect: Get https://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/a6efdb773afe1643f34400b0377d2c616

**Comment by freignat91** [comment]
Connection to docker: ok
extract list container: ok
inspect containers: ko

**Comment by ndegory** [comment]
@freignat91 I think we should open a separate issue, it's not related anymore to the automated build, just to the changes that have been applied on the sources since then

**Comment by freignat91** [comment]
No change have been applied on the source since. I built it manually, but now after a clone, even the manually build doesn't work. It seems related to vendor.

**Comment by freignat91** [comment]
I'm on it. i'm going to open another issue closing this one
