### ISSUE TITLE
Rationalize portal and gateway replica counts

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#1240]
as of 0.11.0, the portal service has a replica count of 1 and the gateway service is global on all worker nodes.
- Can the portal have multiple replicas?
- Do we need to deploy the gateway on all worker nodes?

**Comment by freignat91** [comment]
The portal can have multiple replicas and it's not needed to have a gateway in each node.
 Have for instance 3 instances of each on the workers could be ok

**Comment by ndegory** [comment]
portal is not part of this repo anymore, so closing this issue for now.
