### ISSUE TITLE
Leverage LinuxKit to build lightweight, secure and fast booting images

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#1252]
- Define which packages should be part of the image
- build ISO and AMI with moby for deployment on Mac/HyperKit, VMware, Qemu/KVM and Google Cloud (and more once ready in LinuxKit)
- replace the local bootstrap with the linuxkit tool

**Comment by subfuzion** [comment]
I looked into this after DockerCon and created a DinD image to see if it would be a good replacement for our DinD-based bootstrap. I am enthusiastic about the future for LinuxKit and how we can leverage it; however, at least when I investigated it isn't an easy process to leverage on AWS (it's in work). This is something to watch, but keep on the back burner for now.

Also, unless this has changed recently allowing us to leverage the existing HyperKit hypervisor on the system from a Docker install, such as Docker for Mac, the ISO I generated required having either moby installed or another hypervisor on the system, like VirtualBox and I didn't want to require that as a dependency. Perhaps the moby support will be made available as part of a standard Docker for Mac/Windows installation, which would this issue.
