### ISSUE TITLE
AMP image needs Docker 1.12

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#126]
AMP image installs Docker 1.11 from default Alpine package repository, see Dockerfile:

[TODO apk installs the wrong version of docker (1.11.1-r0), need 1.12](https://github.com/appcelerator/amp/blob/346879d205105f12ce6cd5ea4dd9065a41dd7320/Dockerfile#L3-L4)

**Comment by subfuzion** [comment]
Thanks for updating, @ndegory. I had just noticed it when I left that comment for a different PR. Appreciated 👍

**Comment by subfuzion** [comment]
@ndegory by the way, if you put `Closes #126` (or `Fixes #126`, as appropriate) in your PR's description instead of just the issue number alone, then GitHub will automatically close the issue when the PR gets merged. It's very convenient.

**Comment by subfuzion** [comment]
For anyone else interested, you can search for alpine packages online, like [docker](https://pkgs.alpinelinux.org/packages?name=docker&branch=&repo=&arch=&maintainer=) and view package [details](https://pkgs.alpinelinux.org/package/edge/community/x86_64/docker).
