### ISSUE TITLE
amp create cluster doesn't take in account the SendGrid key 

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#1293]
if the fichier amplifier.yml containing a SendGrid key is created in the directory platform/secrets, then the deploiment script deploy, take it in account to create the right docker secret in order to allow the mailer to find the key and be able to send email.
But,
if we launch amp cluster using the CLI, it doesn't work the amplifier.yml file is not taken in account

**Comment by bquenin** [comment]
@freignat91 I think #1310 clarified the situation. Please reopen if needed.
