### ISSUE TITLE
Dashboard authorization

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#1319]
- Sign up users:  User1 and User2
**- Log with User1**
- create Organization Org1, then User1 is the owner
- create team Team1 in Org1
- add user User2 in team Team1
- create dashboard Dash1 under Org1
- add it as resource of the team Team1 authorization Read (only)
**- Log in as User2**
- load dashboard Dash1
- delete the dashboard -> we well get an error message "user not authorized"
- modify dashboard and save it -> the dashboard is well updated where we should get an error message

**Comment by bquenin** [comment]
Fixed by #1432
