### ISSUE TITLE
Account: Organization resources visibility improvement

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#1322]
Currently an organization resource is visible by any members of the organization.

In order to have the capability to hide/make visible organization resources to a member, we could have:
- the organization resources are visible only by the owners of organization, simple members have no authorization at all on them (or Read = false). They can't see them in any way.
- the members get authorization on organization resources only when they are part of a team , (then, the team authorizations become theirs)

This way, we can have completely separated teams where no member are able to see resources  managed on a team he is not.

**Comment by bquenin** [comment]
This works if we prevent organization members (not owners) from creating resources in the organization.

**Comment by bquenin** [comment]
Implemented in #1432
