### ISSUE TITLE
Fix file owner on Linux when running containerized tools on mounted volume

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#133]
@chrisccoy identified an issue that occurs on Linux (but not Docker for Mac): after running `make install-deps`, which runs glide in a container as root to update vendor dependencies by mounting the project directory, files are owned by `root:root`.

In fact, this error occurs for any files generated by containerized tools when writing on the mounted volume. This causes a variety of issues since the user can no longer remove the files without running sudo, such as when switching to a branch that doesn't have them, or updating vendor dependencies, etc. Files affected include all the generated protobuf `*.pb.go` files, the mounted glide cache directories (`$HOME/.glide`, `./.glide`), and `amp` and `amplifier`.

The expected behavior is that files have ownership attributes corresponding to the current UID:GID when running any of the containerized tools with make.

**Comment by subfuzion** [comment]
Unfortunately, #131 doesn't fix the issue, as observed here: https://github.com/appcelerator/amp/pull/138#issuecomment-244827193

Reopening for further investigation.

**Comment by bquenin** [comment]
I think this issue has been fixed since

**Comment by subfuzion** [comment]
@bquenin Actually it wasn't fixed, which I just confirmed with Nicolas, but I do have a fix for it now.
