### ISSUE TITLE
amp cluster create error (missing amp-bootstrap)

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#1331]
The default command usage should not fail, so a failure is considered a bug.

Currently it uses the version that is compiled into the amp binary. So, for example, in the following case it uses `appcelerator/amp-bootstrap:v0.12.0-dev`.  Since there is no version of the image on the hub at the moment and since the locally built image is `appcelerator/amp-bootstrap:local`, the command fails:

```
$ amp --server=localhost cluster create
[localhost:50101]
Unable to find image 'appcelerator/amp-bootstrap:v0.12.0-dev' locally
docker: Error response from daemon: manifest for appcelerator/amp-bootstrap:v0.12.0-dev not found.
See 'docker run --help'.
f573e897-7aa0-4516-a195-42ee91039e97
```

At the very least we should augment the message to say that `X-dev` versions aren't published, did the user want to specify the `--tag=local` or `--tag=latest` option?

**Comment by ndegory** [comment]
@subfuzion we talked about a solution for this: we should replace the `local` tag with a deployment version tag so that by default a developer will use the image he just built. I couldn't find the github ticket for that, should we do it for 1.0?
