### ISSUE TITLE
amp cluster create error (issue with secret)

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#1332]
While attempting to create a new cluster, amplifier fails to start:

```
uyodtp5a9k92        amp_amplifier           global              0/1                 appcelerator/amplifier:local             *:50101->50101/tcp
```

Inspecting the log shows:

```
amp_amplifier.0.lrvhyq6uhc9p@moby    | 2017/06/06 21:29:01 JWTSecret key cannot be empty. Please check amplifier configuration.
```

Running the following commands does not solve the issue:

```
docker secret rm amplifier_yml
docker volume rm amp-secrets
```

This is a bug because creating a new cluster should not fail for this reason. Either we should generate new secrets or else provide a warning if we are attempting to reuse an older secret (if using an existing swarm manager for a local cluster), or somehow more accurately indicate what the problem is and how to resolve it.

**Comment by ndegory** [comment]
@subfuzion I think this issue can be closed, it was related to an old file in your repo
