### ISSUE TITLE
Synchronize swarm nodes clock

### ISSUE THREAD

**Issue by bquenin** [appcelerator-archive/amp#1339]
In order to prevent node clock jitters, we should use a mechanism to synchronize them such as NTP.

**Comment by ndegory** [comment]
not for 1.0, as it will be BYOS only

**Comment by ndegory** [comment]
on Ubuntu 16.04, ntp is not installed by default anymore, it is replaced by timesyncd, therefore the clock is supposed to be in sync across the nodes.

    $ timedatectl | grep Network
    Network time on: yes
