### ISSUE TITLE
amp cluster create (deploy script) issue

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#1383]
On a regular cluster with a running and healthy swarm, the script deploy stop at:

```
 echo "wait for swarm mode"
  swarmcheck -t 300 -c $nodecount
  checkexit "swarm mode timed out"
  ok
```
and exit in timeout
removing the line the cluster start normally, seems, there is a bad condition somewhere
saw 3 times and two different clusters

**Comment by ndegory** [comment]
can't you please describe your use case?
how is the cluster created?
what is run? CLI or script?
where is it run?
the script or CLI is supposed to work fine when it is run in the standard deployment method, other deployment methods may fail. There's open PRs about it, please have a look if it's not already fixed there.
