### ISSUE TITLE
Stack recovery command

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#1391]
Have a CLI to re-integrate stacks in AMP.
When ETCD as been deleted and stacks still there, then command could take a tack name, verify it exist and re-create the entries in ETCD
Could be useful if we won't stop a stack for any reason, but have to restart amp or etcd after a crash

**Comment by ndegory** [comment]
etcd is using a named volume, it should retrieve the data even when the container is killed. And when deploying at least 3 workers is deployed HA, so the loss of a node should not cause loss of data.
Which leads me to think that we should recommend not to deploy clusters with less than 3 workers.
Local deployment is also not an issue, if you lose your laptop, restoring etcd won't be your priority...

**Comment by ndegory** [comment]
fixed in 0.12
