### ISSUE TITLE
Error: unable to connect to elasticsearch service

### ISSUE THREAD

**Issue by ingo** [appcelerator-archive/amp#1401]
amp -s localhost service logs pinger
[localhost:50101]
Error: unable to connect to elasticsearch service

docker service logs amp_elasticsearch
only supported with experimental daemon

**Comment by wickedest** [comment]
[amp_elasticsearch.txt](https://github.com/appcelerator/amp/files/1085024/amp_elasticsearch.txt)

Log file once experimental features enabled for docker.

**Comment by ndegory** [comment]
@ingo, which version of Docker do you have?

@wickedest thank you for the logs. It shows that the system prerequisite for elasticsearch is not set on your swarm node (amp -s localhost cluster create should have fixed it or warned about it):
you can run `sudo sysctl -w vm.max_map_count=262144` 
and set it permanently in /etc/sysctl.conf:
`vm.max_map_count = 262144`
This is not needed on Docker for Mac, and probably not on Docker for Windows (I'm not sure about that one)

**Comment by ingo** [comment]
@ndegory, that error was from @wickedest. I just pasted it in.

**Comment by bquenin** [comment]
Closing this since a workaround is provided.
