### ISSUE TITLE
Infrastructure service to auto-start services

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#147]
We could have a special infrastructure service, let's say call 'autostart', which could be the HAProxy default service.
So when HAProxy for a given connection doesn't found a service, it sends the call to the autostart service which gets the service name, verifies that the service is allowed to auto-start using ETCD and starts the service with the received url/body.
This way, we could have user services started at the first call instead to have them started by default with nothing to do.

**Comment by subfuzion** [comment]
@freignat91 This will all be addressed as part of the worker task (ie, serverless computing) support, discussed in the architecture doc as on-demand workers.
