### ISSUE TITLE
Support Casbin as the authorization module

### ISSUE THREAD

**Issue by hsluoyz** [appcelerator-archive/amp#1486]
Hi, [Casbin](https://github.com/casbin/casbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, Casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in Casbin's language) can be persisted in files or database (MySQL and Cassandra).

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

Casbin can provide more flexibility and security than the current authorization in api/auth. I can make PR if needed. Let me know if there's any question:) Thanks.

**Comment by bquenin** [comment]
Hi @hsluoyz and thanks for your feedback.
I'm not really happy with the current implementation of our RBAC authorization model right now. Since  we're close to a release, I didn't dig into it yet but I'm definitely planning to rework this. So your comment is very timely!
If you want to give it a try and submit a PR, I'll be happy to review it!
My only question so far (after quickly scanned Casbin docs) is do we have to use dedicated files to define policies or can it be done with code only?
Thanks!

**Comment by hsluoyz** [comment]
Hi @bquenin ,

Thanks for the response!

It's not necessary to reply on files for both the model and the policy rules. I have updated the docs, please see here: https://github.com/casbin/casbin#what-if-i-dont-want-to-reply-on-files-conf-csv

**Comment by hsluoyz** [comment]
Hi @bquenin ,

I have an initial plan here. This plan is the first step. So I try to modify the original code as least as possible to make a smooth transition.

1. I noticed the subject is not used because it's always ``<.*>``, e.g., ``Subjects:  []string{"<.*>"}``. So I just remove it in Casbin policy.
2. The ``Fulfills()`` function has many checkings and is very complicated. So I decide not to touch it in this initial plan.

So here's the Casbin model:

```ini
[request_definition]
r = res, act, owner, store, res_id

[policy_definition]
p = res, act, roles, levels

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.res == p.res && regexMatch(r.act, p.act) && fulfills(r.owner, r.store, r.res_id, p.roles, p.levels)
```

Here's the Casbin policy rules for the 11 default policies like usersAdminByThemselves, usersCanLeaveOrganizations, etc.

```csv
p, amprn:user, *, null, null

p, amprn:organization, leave, null, null
p, amprn:organization, *, owner, null

p, amprn:team, *, owner, null
p, amprn:team, create, (owner)|(member), null

p, amprn:stack, read, null, read
p, amprn:stack, (read)|(update), null, write
p, amprn:stack, *, owner, admin

p, amprn:dashboard, read, null, read
p, amprn:dashboard, (read)|(update), null, write
p, amprn:dashboard, *, owner, admin
```

The policy can be even compressed by integrating the stack and dashboard rules into something like:

```csv
p, amprn:(stack|dashboard), read, null, read
p, amprn:(stack|dashboard), (read)|(update), null, write
p, amprn:(stack|dashboard), *, owner, admin
```

Let me know if you have any questions:)
