### ISSUE TITLE
404 error on http://appcelerator.io while trying to download amp

### ISSUE THREAD

**Issue by bquenin** [appcelerator-archive/amp#1508]
When clicking on the v0.12.0 download link on http://appcelerator.io, we get a page not found error:
![image](https://user-images.githubusercontent.com/11057786/27978466-6b5f2022-6324-11e7-980d-ed279770bd5e.png)

**Comment by JosephGJ** [comment]
Not sure if we want to move this to https://github.com/appcelerator/amp.github.io as it sees more appropriate there.

**Comment by bquenin** [comment]
@JosephGJ you're right, let me open the issue there
