### ISSUE TITLE
Docker "build from git" feature isn't working with amp repository

### ISSUE THREAD

**Issue by bquenin** [appcelerator-archive/amp#152]
docker can build images from git repository URLs, e.g. `docker build git@github.com:appcelerator/amp.git`.

The problem is that docker clones the repository using a `git clone --recursive URL` command, so that, when u have submodules, they get initialized as right after the clone. `git clone --recursive` walks the entire source tree looking for submodules, by looking at `.git` sub folders.
The fact is that we do have such folders (in `vendor` folder), but they're not submodules, so when it tries to initialize them, it fails miserably:

```
docker build git@github.com:appcelerator/amp.git
unable to prepare context: unable to 'git clone' to temporary context directory: Error trying to use git: exit status 128 (Cloning into '/tmp/bq/docker-build-git754625222'...
fatal: no submodule mapping found in .gitmodules for path 'vendor/github.com/Shopify/sarama'
)
```

Unfortunately, this behavior is not configurable in docker: https://github.com/docker/docker/blob/master/pkg/gitutils/gitutils.go#L44

It's even a feature: https://github.com/docker/docker/pull/3463/files

So we have the following options:
- Remove our vendor directory
- Open a ticket at Docker to ask if it's possible to have an option for this
- Do not rely on docker build git feature

**Comment by subfuzion** [comment]
None of all this is necessary. Just need to remove the subprojects (ie, git submodules) and only commit source to vendor. These were introduced by running glide without the vendoring options (no longer necessary with glide 0.12).
