### ISSUE TITLE
Stacks available after cluster is destroyed

### ISSUE THREAD

**Issue by neha-viswanathan** [appcelerator-archive/amp#1533]
User deployed stacks are still available after starting up a local cluster, deploying a stack and destroying the cluster. On re-creating the cluster, since the stack already exists in Docker, deploying a new stack results in updating the previously deployed stack. 
```
$ amp cluster status 
[user neha @ localhost:50101]
cluster: running

$ docker stack ls
NAME                SERVICES
amp                 16
pinger              1

$ amp cluster rm
[user neha @ localhost:50101]
Removing service amp_nats
Removing service amp_node_exporter
Removing service amp_agent
......

$ docker stack ls
NAME                SERVICES
pinger              1

$ amp cluster create
......

$ amp user signup --name jdoe --password password --email jdoe@amp

$ amp stack up -c examples/stacks/pinger/pinger.yml
[user jdoe @ localhost:50101]
Deploying stack pinger using examples/stacks/pinger/pinger.yml
Updating service pinger_pinger (id: un30k1o9so7zy5jhw37or070y)
```
When the cluster is destroyed, along with the AMP infrastructure stacks, shouldn't the user deployed stacks also be removed?

**Comment by subfuzion** [comment]
Yes, user stacks should be removed. However, we can inform the user and refuse to destroy the cluster with running stacks unless a `--force` option is provided.  Docker itself doesn't give any warning, although it requires `--force` when the last manager leaving will destroy the swarm. We will need to ensure that we apply the correct metadata to be able to identify the stack/services created by amp.

**Comment by ndegory** [comment]
only a concern on local deployment
