### ISSUE TITLE
cluster status always reports 'running'

### ISSUE THREAD

**Issue by neha-viswanathan** [appcelerator-archive/amp#1534]
`amp cluster status` reports `running` status despite destroying a cluster.

```
$ amp cluster status
[user neha @ localhost:50101]
cluster: running
```

**Comment by ndegory** [comment]
and also `Error: only cluster operations with '--server=localhost' supported in this release` on remote clusters.

**Comment by neha-viswanathan** [comment]
Looks like this issue has been handled as part of PR #1593.

When a cluster is running, the status shows up something like this -
```
$ amp cluster status
[localhost:50101]
{"SwarmID":"mn4ah79okt017p6l8kqyef2wh","NodeID":"i5ll407nhlel1zdess2k3yc2n"}
```

**Comment by neha-viswanathan** [comment]
Reopening the issue as the current `status` command does not provide any details of whether a cluster is available or not.

If there is no cluster is running, it displays nothing
```
 $ amp cluster status
[localhost:50101]
```
