### ISSUE TITLE
ampagent checks are currently unreliable

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#1601]
With the local plugin, the checks never succeed, but with the `local-fast` option (which skips checks), they do.

Expected:

```
$ docker service ls
ID                  NAME                   MODE                REPLICAS            IMAGE                                          PORTS
3xva0n5j6wq4        amp_elasticsearch      replicated          1/1                 appcelerator/elasticsearch-amp:5.5.0
c2vweq4ev5zc        amp_prometheus         replicated          1/1                 appcelerator/amp-prometheus:latest             *:9090->9090/tcp
f38yfiywyrnd        amp_proxy              global              1/1                 dockercloud/haproxy:latest                     *:80->80/tcp,*:443->443/tcp,*:1936->1936/tcp
fffjq1ce0bxi        amp_agent              global              1/1                 appcelerator/agent:latest
mtrt19gi87ir        amp_haproxy_exporter   replicated          1/1                 prom/haproxy-exporter:v0.7.1
oub8mi0aa8cc        amp_etcd               replicated          1/1                 appcelerator/etcd:3.1.10
qcyaffhoqnfw        amp_ampbeat            replicated          1/1                 appcelerator/ampbeat:latest
ssyoptdktok5        amp_kibana             replicated          1/1                 appcelerator/kibana:5.5.0
u3ohzbb9n0fy        amp_alertmanager       replicated          1/1                 prom/alertmanager:v0.7.1                       *:9093->9093/tcp
u5f4jz98nak5        amp_nats_exporter      replicated          1/1                 appcelerator/prometheus-nats-exporter:latest
ui0ihg78sfjt        amp_gateway            global              1/1                 appcelerator/gateway:latest
vcbfdyencpcp        amp_nats               replicated          1/1                 appcelerator/amp-nats-streaming:v0.5.0
ve4xl2eieldy        amp_node_exporter      global              1/1                 prom/node-exporter:v0.14.0                     *:9100->9100/tcp
vh3iu1n64ry7        amp_amplifier          global              1/1                 appcelerator/amplifier:latest                  *:50101->50101/tcp
xg3m8ewviyhd        amp_grafana            replicated          1/1                 appcelerator/grafana-amp:1.2.4
```

Actual:

```
Error: test failed with status: task: non-zero exit (6)
```

Some of the system check code had to be commented out (lines 53-60 in checks.go).

Other errors have been observed relating to tasks and also the following:

```
2017/07/31 22:49:40 timeout reached while waiting for WATCH_ACTION_REMOVE events
```

Currently the Travis CI build has been configured to skip tests with the `cluster create local-fast` option to prevent false failures.

**Comment by ndegory** [comment]
`timeout reached while waiting for WATCH_ACTION_REMOVE events` is actually not an error, we don't want to get any remove events at that moment.

The tests that are failing in the case you reported are failures on messages sent between 2 test services. The idea was that if the cluster does not look good enough (missing messages between 2 services is not good), then we refuse to deploy.

We can be more permissive on the cluster health, but then, what is good enough to be able to deploy?

**Comment by subfuzion** [comment]
With respect to the `timeout` message, perhaps it can be improved since it's potentially misleading (timeouts are usually associated with negative things). Maybe `WATCH_ACTION_REMOVE events interval: success`.

With respect to cluster health, it should not be the case that we can successfully start the cluster as long as health checks are disabled; if our health checks themselves lead to system failures, we have to determine if we're doing something that is not optimal and/or putting to much pressure on the system somehow, or querying for results without adequate delays, or whatever the case may be, or else determine if Docker itself is simply buggy -- but we need to be super skeptical of that assumption and have solid, reliable evidence. I don't think we've done enough work here (and it might have to wait for the refactoring effort after 0.14).
