### ISSUE TITLE
repo cleanup

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#1631]
We currently have [68 repos](https://github.com/orgs/appcelerator/teams/amp/repositories?before=Y3Vyc29yOnYyOpKvYW1wLXN5c3RlbS10ZXN0zgOw2OE%3D) on GitHub.

There's nothing wrong with preserving a bit of history, but let's use this issue to identify repos that no longer serve any useful purpose as potential candidates for pruning.

**Comment by bquenin** [comment]
I've removed 2 obsolete repositories where I had ownership:
 * https://github.com/appcelerator/docker-zookeeper
 * https://github.com/appcelerator/amp-docker-kafka

I've also removed the associated Docker hub repositories:
 * https://hub.docker.com/r/appcelerator/zookeeper/
 * https://hub.docker.com/r/appcelerator/kafka/

**Comment by ndegory** [comment]
Github repos that are not used anymore, checked means removed:

- [ ] appcelerator/amp-activity-lib
- [ ] appcelerator/amp-agent (moved to amp repo)
- [ ] appcelerator/amp-api
- [ ] appcelerator/amp-autotest
- [ ] appcelerator/amp-build 
- [ ] appcelerator/amp-ci
- [x] appcelerator/amp-config (@ndegory)
- [ ] appcelerator/amp-consul-lib
- [ ] appcelerator/amp-demo-service
- [ ] appcelerator/amp-docker-agent 
- [ ] appcelerator/amp-docker-nats-streaming (@bquenin, moved to amp)
- [ ] appcelerator/amp-github-certs 
- [ ] appcelerator/amp-haproxy-controller (@freignat91)
- [ ] appcelerator/amp-kafka-lib (@subfuzion)
- [ ] appcelerator/amp-log 
- [ ] appcelerator/amp-log-agent 
- [ ] appcelerator/amp-log-lib
- [ ] appcelerator/amp-log-ui 
- [ ] appcelerator/amp-monitor 
- [ ] appcelerator/amp-pilot (@freignat)
- [ ] appcelerator/amp-portainer 
- [ ] appcelerator/amp-service 
- [ ] appcelerator/amp-service-worker 
- [ ] appcelerator/amp-status (@tpujals)
- [ ] appcelerator/amp-swarm-bootstrap (@tpujals)
- [ ] appcelerator/amp-swarm-deploy  (@ndegory, I keep it for now, there's legacy code for the cluster creation)
- [ ] appcelerator/amp-system-test 
- [ ] appcelerator/amp-telemetry-demo 
- [ ] appcelerator/amp-test (?)
- [ ] appcelerator/amp-ui (@freignat)
- [ ] appcelerator/amp-x-project 
- [ ] appcelerator/ampbeat (@freignat)
- [ ] appcelerator/ampswarm
- [ ] appcelerator/docker-amp 
- [ ] appcelerator/docker-cassandra
- [ ] appcelerator/docker-consul
- [ ] appcelerator/docker-elasticsearch-amp (@ndegory, moved to amp repo)
- [ ] appcelerator/docker-grafana-amp (@ndegory, moved to amp repo)
- [ ] appcelerator/docker-haproxy
- [ ] appcelerator/docker-influxdb (@ndegory)
- [ ] appcelerator/docker-influxdb-amp (@ndegory)
- [ ] appcelerator/docker-influxdb-proxy (@ndegory)
- [ ] appcelerator/docker-kapacitor (@ndegory)
- [ ] appcelerator/docker-kapacitor-amp (@ndegory)
- [x] appcelerator/docker-kibana  (@ndegory, moved to amp repo)
- [ ] appcelerator/docker-nginx 
- [ ] appcelerator/docker-node 
- [ ] appcelerator/docker-telegraf (@ndegory)
- [ ] appcelerator/issueDocker  (@freignat)
