### ISSUE TITLE
AMP on centos/redhat

### ISSUE THREAD

**Issue by nikolai-derzhak-distillery** [appcelerator-archive/amp#1672]
We should support amp on rhel OS family.

Biggest issue right now is node_exporter service , which mounts root fs inside of container.

And that brings fs namespace leakage. https://github.com/moby/moby/issues/34198

We should introduce flag for amp CLI to disable root FS volume mounting in node_exporter.

Also amp agent should detect centos/redhat OS in docker info and disable root FS mounting too.

Only newest RedHat 7.4 kernel with kernel setting works for now
```
echo 1 > /proc/sys/fs/may_detach_mounts
```
CentOS 7.4 to be releases soon and tested.

So we choose to disable root FS mounting and tolerate loss of disk usage metrics in monitoring for now.

CLI flag should have priority versus amp agent detection mechanism.

**Comment by ndegory** [comment]
the situation looks better since 17.09, the `may_detach_mounts` setting is enabled by Docker: https://github.com/moby/moby/pull/34886
