### ISSUE TITLE
Proxying, Domains and Certificates

### ISSUE THREAD

**Issue by bquenin** [appcelerator-archive/amp#1678]
Our current solution relies on `HAProxy` but it lacks the following:

- Support for multiple certificates (and therefore multiple domains) for multiple customers. It is, however, definitely possible to design a solution based on HAProxy to manage this use case,
- HTTP/2 proxying: Currently, `HAProxy` doesn't proxy the HTTP/2 protocol, the only way is to rely on TCP proxy for this use case which is not possible in our case since we rely on HTTP protocol information for routing. This is also why today, Amplifier (AMP API Server) is not sitting behind the proxy but directly accessed.

Considering this, we have to rethink our proxying strategy. There are alternatives to `HAProxy` and we need to study the alternatives (such as `nginx`, `traefik`, etc.) and check which one would best fit our needs.

**Comment by ndegory** [comment]
study updated on Confluence.
