### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by bquenin** [appcelerator-archive/amp#1683]
AMP doesn't provide anything related to storage. We need to study what could be provided. For instance:
 - Provision distributed file system (i.e. NFS) at deployment time?
 - Provide persistence storage (i.e. Portworx, etc.)?

- [x] #1739 NFS endpoint

**Comment by ndegory** [comment]
For persistence storage, #1414 provided the DockerPlugins option that allows to deploy a list of Docker plugins (mostly storage plugins, such as RexRay) on each node of the swarm.
That's something that we should refine once we implement the node management commands (different sets of plugins for different group of workers).
