### ISSUE TITLE
Update `gotools` and `amptools` images to use fixed versions

### ISSUE THREAD

**Issue by bquenin** [appcelerator-archive/amp#1692]

**Comment by ndegory** [comment]
I think it's already the case (since #1668):
```
$ grep appcelerator/amptools cmd/ampmake/main.go
	toolsImage      = "appcelerator/amptools:1.7"
```
Do you think of other places where we use the image without tag?

**Comment by neha-viswanathan** [comment]
It's for these packages in the image:
- github.com/golang/protobuf 
- google.golang.org/grpc/grpc-go
- github.com/grpc-ecosystem/grpc-gateway
- github.com/golang/glog
- google.golang.org/genproto
- github.com/alecthomas/gometalinter

**Comment by ndegory** [comment]
ok, got it
