### ISSUE TITLE
Adjust HEALTHCHECK parameters to be used without amp-pilot

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#22]
It seems that without amp-pilot, we need to let more time to the container before kill them, especially at amp startup period.
With amp 'min' we strange behavior due to service restarting to quickly.

**Comment by subfuzion** [comment]
Yes, I agree. I slightly bumped up the interval for [docker-telegraf](https://github.com/appcelerator/docker-telegraf/commit/01eaabf0c827f93407f8a99a2a653b588c46d1e8) and pushed that when I was experimenting yesterday. I was going to ask you and Nicolas to investigate and fine-tune further. Thanks!

**Comment by freignat91** [comment]
i investigated a little and i saw that the application are killed when they are starting if they spend too much time to be ready, letting them in the bad shape and some of them are not able anymore to start or block some port even started. It's weird.
amp-pilot didn't kill applications, it just wait to launch them, that was the difference, we can have sort delay to wait, but not to kill.
the best soution will be yours: having the dependencies management at service api level, in the meantime, we can raise the healthcheck delay to let more time to the application to start.

**Comment by freignat91** [comment]
Done. testing, removing all images locally and pulling them all to start amp min

**Comment by freignat91** [comment]
tests done and ok.

**Comment by subfuzion** [comment]
@freignat91: Awesome, pulling latest images. Just to confirm ... this is only for the `--min` set right now, correct? Or have all the images been updated?

**Comment by freignat91** [comment]
It's just for amp min, i have updated nginx and amp-ui because i use them for tests.
you're right, better to update all. I'm going to update all the other images this afternoon.

**Comment by freignat91** [comment]
done for amp services images excepted consul, kafka-manager, amp-pilot and the ones which have been already done

**Comment by subfuzion** [comment]
Since we will be using etecd instead of consul as our backend k/v store, I'd like to eliminate any other dependencies we might have on consul, such as storing reverse proxy configuration settings or anything else we were considering using it for, and remove it from the swarm script.

**Comment by freignat91** [comment]
About Consul, we have now only amp-pilot and amp-ui that use it. Nginx doesn't need Consul, it had just a upstream service Consul to reverse proxy Consul, but i have already removed it. So ningx has now no dependency with Consul.
About amp-pilot, it's ok for amp 'min', but for the full amp, we need to modify third products images to remove all amp-pilot trace in it. Could be done by Nicolas next week.
About amp-ui, we have to think how we want to update it:
I can update it to use tasks status instead of consul status for now (fast way to have it working as it was before removing Consul)
The target is perhaps more to use the amp api to get services health and be able to create, delete, update them.
?

**Comment by freignat91** [comment]
tested full amp platform without consul:
all services are up after a while
Logs are visible in Kibana
Grafana starts and show dashboard, but no data in there
amp-ui works (logs, containers details, ...) but doesn't show services status (all set to unknown)

**Comment by freignat91** [comment]
According to logs the telemetry worker issue come from telegraf-worker which started with kafka not readay, but is it-self considered as ready, so it does't restart and stay in a bad shape.
To be fixed by Nicolas next week
logs:
Fri Aug 12 2016 15:57:34    2016/08/12 13:57:34 Started the kafka consumer service, peers: [zookeeper:2181], topics: [telegraf]
Fri Aug 12 2016 15:57:34    2016/08/12 13:57:34 Kafka Consumer Error: kafka: error while consuming telegraf/-1: zk: node does not exist
Fri Aug 12 2016 15:57:50    2016/08/12 13:57:50 Output [influxdb] buffer fullness: 0 / 1000 metrics. Total gathered metrics: 0. Total dropped metrics: 0.
Fri Aug 12 2016 15:58:00    2016/08/12 13:58:00 Output [influxdb] buffer fullness: 0 / 1000 metrics. Total gathered metrics: 0. Total dropped metrics: 0.

**Comment by freignat91** [comment]
Here is a workaround: kill the telemetry-worker container, then the service restart it and after a short while we have all the data in grafana dashboard

**Comment by ndegory** [comment]
the problem with telegraf is not related to kafka, but to zookeeper (zk: node does not exist)
It's probably because the zookeeper service is started after the telegraf service in the swarm script, I'll change the order.
If Kafka is not available, then telegraf should fail, which is a good behavior (Swarm will launch a new one, and all will be fine once Kafka is up)

**Comment by subfuzion** [comment]
@ndegory Please look at [influxdb](https://github.com/appcelerator/docker-influxdb/blob/master/run.sh). It takes a long time to start:

```
$ ./swarm start --min
$ ./swarm monitor
```

It looks like `run.sh` has the potential to be optimized for a faster start, there shouldn't be anything related to amp-pilot in `run.sh` anymore, and the `HEALTHCHECK` can be more optimally tuned.

**Comment by subfuzion** [comment]
@ndegory 

> I'll change the order.

Please don't change the order. The point is to see how well we can tune the retry intervals so that we can trust docker 1.12 to still reliably ensure all the services eventually start. In other words if one service reports that it is unhealthy because its upstream dependency is not available, docker will retry to start the service according to its healthcheck retry policy. At some point, the upstream service itself will be running and healthy, which means the downstream service should now succeed on start. The point of tuning is to have reasonable delays on intervals (not too short or there is a lot of churn, but not too excessively long that time is wasted, which adds up to very lengthy delays in the system if there is a long chain of dependencies).

**Comment by subfuzion** [comment]
@ndegory I also want to emphasize that all updates to the swarm script need to go through a PR. We are no longer pushing updates to `master` for the very reason that changes might happen without me or anyone being aware. The PR process is so that there is the opportunity to approve or reject a change. Thanks!

**Comment by ndegory** [comment]
@subfuzion no worries, I prefer to go through PR anyway :)
I did some tests on my side, the order is not a good fix.
What happens is that in certain conditions (zookeeper up but Kafka not ready), telegraf doesn't initialize the input correctly but doesn't fail (it fails when zookeeper is down). There's nothing we can do in the healthcheck, unless we implement a complicated mechanism where we scan the log of the container to trap that kind of issues (or empty buffer, which is symptomatic), but I wouldn't recommend going this way.
I'll see if I can fix the telegraf plugin source, and at least I'll create a bug on the influxdata repo.

**Comment by ndegory** [comment]
I have a patch ready, but after a dozen of retries, I'm unable to trigger the issue anymore... I'll keep the patch in case the issue occurs again. Please also pull the latest telegraf image, I've made changes recently.

**Comment by subfuzion** [comment]
@ndegory, thanks for your analysis and the updated image. 👍
