### ISSUE TITLE
add command: amp stack redeploy 

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#220]
Implement the amp command: amp stack redeploy [stack yaml file]

it could work like that:
- compare the stack started services with new ones (in the stack yaml file)
  for each service:
- if no change, then nothing is done
- if change appear, then update it using docker service update swarm api
- if a service is not in the stack yaml file, then stop it
  and update ETCD data accordingly.

so on service side, we have to implement 'service update'
and on stack side, to implement 'stack redeploy'

What do you think?

**Comment by generalhenry** [comment]
:+1:
