### ISSUE TITLE
Service Env

### ISSUE THREAD

**Issue by generalhenry** [appcelerator-archive/amp#235]
Env is implemented by the docker swarm API as a `[]string`

1) Change the ServiceSpec for env to `repeated string`
2) Update the parser to use `[]string`
3) Pass Env to containerSpec

**Comment by freignat91** [comment]
@Henry. Our serviceSpect was already not the same than the docker one. I let Tony decide what to do with this PR, modify the parsing to have []string (the docker type) to be adapted to []*string (the repeated string type) whatever, or use the one the parsing already give now: map[string]string, this PR

**Comment by subfuzion** [comment]
@freignat91 See my comment here: https://github.com/appcelerator/amp/pull/238#issuecomment-249398791. I've gone ahead and submitted a separate PR that also includes some other cleanup/refactoring (#244).
