### ISSUE TITLE
Add Sub Commands to CLI

### ISSUE THREAD

**Issue by chrisccoy** [appcelerator-archive/amp#25]
I think it might be a good idea to add support for sub commands within the CLI to support nested commands where necessary. 
For example,

`amp status cpu --filter datacenter="dc2"`

In the above, we would have a cpu sub command nested within status. The cpu sub command would have its own flags for specific behavior. I feel like this behavior would make the CLI more intuitive to the end user and also would make help listing much more friendly. Depending on the use case, the nesting could go several levels deep.

**Comment by subfuzion** [comment]
Most of our commands will need subcommands similar to the Docker CLI. For example, we will need something like `amp service create`. Your use case definitely looks reasonable to me.

**Comment by subfuzion** [comment]
@chrisccoy No other discussion here, but I definitely see the need for sub-commands. I'm going to close this issue, but I think it was a good idea to raise it; in fact, I think it's a good idea that you, me, @generalhenry and @bertrand-quenin open separate issues with the specs for our respective CLI interfaces as they evolve so we can get feedback and consensus. The issues should have the `area/cli`, `kind/feature` and `status/needs-consensus` labels, and can also serve as a form of initial documentation on using the commands.
