### ISSUE TITLE
move all amp alpine go images/Dockerfiles to Go 1.7

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#258]
Last amp-agent issue shown bad sides effect using alpine go 1.6 image with docker/docker.
Moved to Go 1.7 solved the issue.
To be safe, better to move all our alpine images to Go 1.7

**Comment by freignat91** [comment]
see: 
https://github.com/appcelerator/issueDocker
a project to show the docker/docker issue

**Comment by ndegory** [comment]
@freignat91 can we change the tests in the docker-compose.test.yml of amp-agent to reflect these tests?

**Comment by pires** [comment]
Make sure it's the latest minor release, 1.7.1. There were some pretty serious DNS issues that were fixed in that release, https://github.com/golang/go/issues?q=milestone%3AGo1.7.1.

**Comment by ndegory** [comment]
@pires thank you for the notice. The edge repo of Alpine has Go 1.7.1, so we're fine.
