### ISSUE TITLE
Solution for localhost DNS with no prerequisite, all systems (linux, windows, mac)

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#260]
[fist post re-written]:
Create a DNS entry in Route53  format *.local.[domainName] and having 127.0.0.1 as value
So any host names matching the form *.local.[domaineName] will be resolved to 127.0.0.1 on all machines.
This way we can use Haproxy reserve proxy using host with a local instance of amp running on our machine for test or development. All URL having host finishing by `local.[domainName]` will be routed to the local haproxy and processed.

**Comment by freignat91** [comment]
I just created DNS entry: "local.axwaytest.net"
so xxx.local.axwaytest.net routes to localhost on all machines, no matter the what is 'xxx'
ui.local.axwaytest.net on your explorer will launch your local instance of amp-ui for instance

**Comment by generalhenry** [comment]
I also set *.local.appcelerator.io to localhost.

**Comment by subfuzion** [comment]
Modifying `etc/hosts` always works to provide a way to map host names. Although `/etc/hosts` wasn't intended for DNS, it works just fine for not only hostnames but multilevel domain names. Mapping dedicated names (`foo.appcelerator.io` to `127.0.01`, for example) works as long as there is no conflict with any 3rd level domain name. As per Henry's example, using `*.local.appcelerator.io` as a 4th level wildcard mapping for local.appcelerator.io is safer.

Ideally, we just want a simple tool to do to it in a safe reliable way that doesn't require the user to manually edit their hosts file (something a bit more robust than our current shell script).

**Comment by freignat91** [comment]
Not sure i got your last point @Tony, it's what we propose with "local.axwaytest.net" or "local.appcelerator.io". 
Anyone executing `ping xxx.local.appcelerator.io` on his machine anywhere will see answer: 127.0.0.1
with nothing to do on the machine. It's safe and robust.
I updated the first post which wasn't very clear.
