### ISSUE TITLE
Open an official Docker issue on the swarm bug 

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#263]
Defined a clear, repeatable use case to make obvious the issue we found on swam multi nodes configuration in order to get official Docker update or feedback.

**Comment by ndegory** [comment]
Good news: the bug was ours, after a fix on the security group, I don't notice any issues anymore on a full Swarm cluster (3 managers + 5 nodes). No need to open an issue on the Docker repo.
I've applied the changes on https://github.com/appcelerator/amp-swarm-deploy
