### ISSUE TITLE
Amp logs for service

### ISSUE THREAD

**Issue by craigivy** [appcelerator-archive/amp#271]
Would like the ability to see the logs for a given service, similar to stack.

Use cases:
- I want to understand why my service keeps restarting,  So I want to look at all the logs for that service.
- Want to look at my service and only my service holistically 
- I'm lazy, I don't want to deal with container IDs.  In early development you may only be running one instance and amp logs --service myservice is the fastest and easiest approach IMO

**Comment by craigivy** [comment]
Noticed the readme has this in the document.  But not  the command "amp logs -h" did not show it.  Pulled today

**Comment by bquenin** [comment]
@craigivy I've updated the documentation of the CLI `logs` command and the README in order to make it easier to figure out.
`amp logs` is service based by default. Running `amp logs myservice` fetches all the logs for this service, including stopped or running containers.

**Comment by craigivy** [comment]
@bertrand-quenin, Thanks, not sure why I did not try that.
