### ISSUE TITLE
Stack: replicas and public.name required?

### ISSUE THREAD

**Issue by craigivy** [appcelerator-archive/amp#273]
Sample stacks failing.  sample05 failing because public.name and replicas not set in stack file.  If these are required a user friendly error should be returned in both cases (as of now it is hard to tell what is wrong).  If defaulted I assume replicas is 1 and public.name is the name of the service.

**Comment by freignat91** [comment]
Replicat issue fiixed in PR#270, but created a dedicated PR #275

**Comment by freignat91** [comment]
fixed close issue
