### ISSUE TITLE
Ignore Vendor Folder Temporarily

### ISSUE THREAD

**Issue by chrisccoy** [appcelerator-archive/amp#29]
Considering we are doing `glide install` often, could we just add the vendor directory to gitignore to avoid status errors? I only suggest this as a temporary idea.

**Comment by subfuzion** [comment]
I've addressed this over slack, but just to recap, I'm definitely not in love with the current state of vendoring in the community. I agree that waiting for glide install to complete is painful (and it doesn't always complete successfully). But if you ignore vendor, then you will _for sure_ need to run glide install every you pull a PR or any new branch.

I think we're committed at this point and that means all in. I mentioned my conversations with other gophers and docker captains over slack and irc, and there was pretty broad consensus about the approach. A quick survey of major projects demonstrates the same: [Docker](https://github.com/docker/docker), [Kubernetes](https://github.com/kubernetes/kubernetes), [CoreOS rkt](https://github.com/coreos/rkt), [etcd](https://github.com/coreos/etcd/tree/master/cmd)...

It's not about [cargo cult programming](https://en.wikipedia.org/wiki/Cargo_cult_programming) ... until we have more experience and the insight for going against the tide, we don't have a strong basis for going against the community wisdom. By all accounts, vendoring is not ideal and apparently the go team has made a commitment to making further improvements things in the future.

I think we've beaten this to death for now, including how to resolve issues when they happen. Generally the most expedient thing will be to delete the vendor directory and run glide install again to get things matched up to what's specified in glide.lock.

**Comment by subfuzion** [comment]
As a follow-up to this issue, we have been able to resolve the pain points through the use of flags that don't add the submodule refs, but source instead. The Makefile commands (`make install-deps` and `make update-deps`) are provided as helpers.
