### ISSUE TITLE
Move stack parsing to client side

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#298]
related to #274 

Have the parsing of the stack file for the amp command 'up', client side to:
- manage the `env_file` item in stack file (like docker compose file)
- be able to pre-process stack file with environment variables or env files.

**Comment by subfuzion** [comment]
We had discussed moving the parsing to the client in the past, but decided at the time it was best to handle it on the service end. The parsing doesn't need to be done by the client to handle preprocessing transformations before submitting the stack file. On the other hand, I can't think of a reason why we couldn't also add an rpc operation that takes the protobuf generated type for the stack spec other than I don't think it really gives us much benefit right now. In fact, the transformation itself doesn't need to be handled on the client either -- it would be enough to read the file, identify the environment variables in the stack file, grab the environment values from the environment, and supply the map as part of the up api (`UpRequest` message). This mechanism would also support production environments when the environment variables for the stack have been configured by an admin, and need to be supplied along with the stack file.
