### ISSUE TITLE
add volumes/mount in stack file

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#299]
manage volume and mount in stack file per service and add capability to create named volumes used by services (so add a "volumes:" entry in stack file same level than "services:" and "network:"

**Comment by freignat91** [comment]
Partially done in PR #304, we can now define volumes for services in stack file included named volumes.

**Comment by ndegory** [comment]
@freignat91 what is missing?

**Comment by freignat91** [comment]
The capability to create shared volumes in stack files under dedicate topic "volumes" as it's the case for networks

**Comment by freignat91** [comment]
Close this one, open a new one for the shared volumes
