### ISSUE TITLE
amp tests fail on multi node swarm cluster

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#301]
To be able to test (with make test) the kafka service has to be advertised. The current implementation works for single node clusters, but not on multi node clusters.

**Comment by ndegory** [comment]
Proposition:
- the tests should interact with the amplifier part of the stack, not with an extra amplifier container.
- no direct interactions with other containers (influxdb, elasticsearch) should be done, unless it can be done with the Swarm routing mesh

**Comment by subfuzion** [comment]
Obsolete.
