### ISSUE TITLE
Swarm monitor not clearing lines below core services

### ISSUE THREAD

**Issue by hadrien-gantzer** [appcelerator-archive/amp#302]
Working with stacks and monitoring through `swarm monitor`

Display is not being refreshed properly when new services start to get populated.

_Steps to reproduce:_
1. `sudo swarm start`
2. `swarm monitor`
3. Once all service up & running, start a stack in another terminal: `amp stack up stack1 -f ./api/rpc/stack/test_samples/sample-03.yml`
4. You'll see all services getting populated properly in your `swarm monitor` window, issue arise when deleting the stack: `amp stack rm -f stack1`

**Observation:** newly created services visible within `swarm monitor` below the 14 core services part of AMP are not being cleared - which makes 3 additional lines using sample3

**Comment by hadrien-gantzer** [comment]
Modify swarm script **monitor** function:
- Current:
  `monitor() {
  interval=${1:-5}
  clear; while true; do tput cup 0 0; docker service ls; sleep $interval; done
  }`
- Proposition:
  `monitor() {
  interval=${1:-5}
  while true; do clear; tput cup 0 0; docker service ls; sleep $interval; done
  }`

**Comment by ndegory** [comment]
@hagantzer if you include _clear_ in the loop, there's no reason to use tput anymore, as the screen is already cleared an reset to 0;0.

**Comment by hadrien-gantzer** [comment]
@ndegory k, keeping the cup method to get smoother display update

**proposition 2:**

`monitor() {
  interval=${1:-5}
  while true; do tput cup 0 0; tput ed; docker service ls; sleep $interval; done
}
`

> proposed fix available in branch [swarm-monitor-fix](https://github.com/appcelerator/amp/tree/swarm-monitor-fix)

**Comment by subfuzion** [comment]
We can write a better script for this:
1. Set exit trap to restore cursor and move to the last row
2. Hide cursor
3. Clear the screen
4. Loop:
   1. List services
   2. Clear to the end of the screen
   3. Set cursor to top left
   4. Sleep for configured delay

**Comment by freignat91** [comment]
Fixed with `amp platform monitor`
