### ISSUE TITLE
Need an amp-bootstrap agent

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#306]
To replace appcelerator/amp-swarm-deploy, we need a go binary that will take care of same operations:
- make sure the Docker engine is up to date
- initialize the Swarm cluster

Later if will be also used to register on the AMP portal

**Comment by freignat91** [comment]
it could also be used to start/stop amp remotely or to add/remove new swam node(s) to swarm cluster.

**Comment by subfuzion** [comment]
Obsolete based on InfraKit strategy.
