### ISSUE TITLE
Release should include released mircoservice instead leatest

### ISSUE THREAD

**Issue by craigivy** [appcelerator-archive/amp#310]
When using a release all components should be versioned and used.  Swarm pull is pulling the latest of several docker images -
  appcelerator/amplifier:latest
  appcelerator/amp-agent:latest
  appcelerator/amp-log-worker:latest
  appcelerator/amp-ui:latest
  appcelerator/elasticsearch-amp:latest
  appcelerator/grafana:latest

Using versioned docker instances will ensure consistency between our environments which will help us identify amp issues vs environmental issues.

**Comment by subfuzion** [comment]
@craigivy Agree, this is in work (although the issue for it is in our old repo, so just as well that you opened it here). We just started to tag our milestone releases and we're talking about creating a single tagged image with all the binaries correlated for each release right now. You can expect resolution on this by the next iteration. cc/ @ndegory @hagantzer

**Comment by ndegory** [comment]
release v0.2.2 has locked versions for all images.
It will the case for all subsequent releases.
