### ISSUE TITLE
AMP commands return connection errors

### ISSUE THREAD

**Issue by craigivy** [appcelerator-archive/amp#311]
Running AMP commands return connection errors.
amp stats
2016/10/13 20:11:50 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::1]:50101: getsockopt: connection refused"; Reconnecting to {"localhost:50101" <nil>}

[swarm.txt](https://github.com/appcelerator/amp/files/528660/swarm.txt)

Using release 0.1.1, me know if you want more info. 

installed using these [instructions](https://github.com/appcelerator/engage-amp/blob/master/installAMP.md)

@vivekschauhan is this the same error your seeing?

**Comment by freignat91** [comment]
It seems that you don't have the server address set in your configuration file.
Add this file:   `~/.amp.yaml`
with inside one line:
`ServerAddress: 127.0.0.1:8080`

and it's going to work.

You can also add at the end of each amp command the argument --server 127.0.0.1:8080
your stats command become:  amp stats --server 127.0.0.1:8080

**Comment by craigivy** [comment]
After adding that line and starting amplifier I get the following error

sadmin@lphxcm020:~$ amplifier
amplifier (server version: 1.0.0, build: fff88706)
2016/10/14 08:12:22 connecting to etcd at http://localhost:2379
2016/10/14 08:12:22 connected to etcd at http://localhost:2379
2016/10/14 08:12:22 connecting to elasticsearch at http://localhost:9200
2016/10/14 08:12:28 amplifer is unable to connect to elasticsearch on: http://localhost:9200
no Elasticsearch node available
panic: amplifer is unable to connect to elasticsearch on: http://localhost:9200
no Elasticsearch node available

goroutine 1 [running]:
panic(0xa8cf00, 0xc42013f070)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
log.Panicf(0xbea762, 0x38, 0xc42023dcb0, 0x2, 0x2)
	/usr/local/go/src/log/log.go:327 +0xe3
github.com/appcelerator/amp/api/server.initElasticsearch(0xbc98d7, 0x6, 0xc420326ad0, 0x1, 0x1, 0xbd5a82, 0x15, 0x0, 0x0, 0x0, ...)
	/home/sadmin/go/src/github.com/appcelerator/amp/api/server/server.go:79 +0x246
github.com/appcelerator/amp/api/server.Start(0xbc98d7, 0x6, 0xc420326ad0, 0x1, 0x1, 0xbd5a82, 0x15, 0x0, 0x0, 0x0, ...)
	/home/sadmin/go/src/github.com/appcelerator/amp/api/server/server.go:27 +0xb2
main.main()
	/home/sadmin/go/src/github.com/appcelerator/amp/cmd/amplifier/main.go:89 +0x149
sadmin@lphxcm020:~$

**Comment by craigivy** [comment]
Passing arguments seems to be working. But the yaml file is not.  Maybe the yaml file is post 0.1.1.

```
sadmin@lphxcm020:~$ more ~/.amp.yaml 
ServerAddress 127.0.0.1:8080
sadmin@lphxcm020:~$ amp logs
2016/10/14 15:07:03 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::1]:50101: getsockopt: connection refused"; Reconnecting to {"localhost:50101" <nil>}
rpc error: code = 14 desc = grpc: the connection is unavailable
sadmin@lphxcm020:~$ amp logs --server 127.0.0.1:8080
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
```

**Comment by generalhenry** [comment]
I think I see the issue, I made a commit: https://github.com/appcelerator/engage-amp/pull/1#discussion_r83512786
