### ISSUE TITLE
Stack name label available in containers 

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#324]
It would be convenient to have labels available in the containers for the stack name and the environment, for alerting purposes (Kapacitor). Right now we only have the service name.

PS: The --label option of docker service create only apply to the service and does not propagate to the containers. There's a --container-label option for that.

**Comment by freignat91** [comment]
You mean for the infrastructure containers?
The containers created using stack have stack labels, for instance with pinger container:

```
"Labels": {
                "com.docker.swarm.node.id": "6k7aw8bv5atpmy33judq8gmwy",
                "com.docker.swarm.service.id": "d89lrn1snwmim6f452cvtjuj3",
                "com.docker.swarm.service.name": "test1-pinger",
                "com.docker.swarm.task": "",
                "com.docker.swarm.task.id": "6i1u5mhxrqkosj9vx4ch5pa2m",
                "com.docker.swarm.task.name": "test1-pinger.1",
                "io.amp.stack.id": "32997de8c3b32232164a60e2c26f9c7f2801e3259b38d3310d8509cc31268611",
                "io.amp.stack.name": "test1"
            }
```

**Comment by ndegory** [comment]
@freignat91 yes, I meant for the infra containers.
One thing that is missing in the labels of the stacks is an io.amp.stack.environment label.
