### ISSUE TITLE
Add binaries to release

### ISSUE THREAD

**Issue by jhaynie** [appcelerator-archive/amp#330]
Would be nice to build binaries for main target OS (like Windows, Linux, etc) and have them available for download on release (vs having to go build them).

**Comment by subfuzion** [comment]
Sorry, but that's part of the paid support plan. Kidding! We were just discussing this and will be building these as part of the releases. Thanks for opening the issue!

**Comment by subfuzion** [comment]
Getting done with today's 1.0-rc1 release!
