### ISSUE TITLE
Stack file documentation

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#342]
@appcelerator/amp team: Use this [gist](https://gist.github.com/subfuzion/ad84b0c97151f1bdfafefc32cdd79457) for now to start adding input to the stack file documentation. It doesn't need to look pretty for now; it's just a rough draft. @hagantzer and I will make edit it to create a doc that we add to the repo. We're using a gist instead of committing a rough draft so there isn't a storm of edit commits for now. The end result should be similar to the [Compose file reference](https://docs.docker.com/compose/compose-file/) and Docker Cloud [Stack YAML reference](https://docs.docker.com/docker-cloud/apps/stack-yaml-reference/).

**Comment by subfuzion** [comment]
@hagantzer Can you please work with @freignat91. We need more thorough documentation ASAP for the release. See examples above. The documentation should make it clear what options are available for configuring networks, the volume support, etc. There is currently not enough information! Thanks.

**Comment by subfuzion** [comment]
@hagantzer This is the target document after inputs have been gathered in the gist:
https://github.com/appcelerator/amp/blob/master/docs/stackfile-reference.md

**Comment by bquenin** [comment]
@subfuzion I guess we can close this issue now that we use compose v3+
