### ISSUE TITLE
Swarm not starting when network interface has multiple addresses 

### ISSUE THREAD

**Issue by hadrien-gantzer** [appcelerator-archive/amp#348]
**Error Message from `swarm start` in such case:**

> Error response from daemon: could not choose an IP address to advertise since this system has multiple addresses on interface eth0 (2620:ad:8083:8:e092:3051:cbcf:5987 and 2620:ad:8083:8:f21f:afff:fe5b:6946) - specify one with --advertise-add

Fixed by:

> docker swarm init --advertise-addr 127.0.0.1

**Comment by bquenin** [comment]
You're right, it's puzzling when you don't know how to initialize swarm.
I'll submit a fix.

**Comment by ndegory** [comment]
see #39
