### ISSUE TITLE
Bleve ?

### ISSUE THREAD

**Issue by joeblew99** [appcelerator-archive/amp#353]
i was wondering if you had considered using Bleve (http://www.blevesearch.com/) , instead of Elastic Search ?

Just like how your using NATS-Streaming and not Kafka.

**Comment by bquenin** [comment]
Hi @joeblew99,

Thanks for the link, I didn't know about Bleve.
After a quick look, it looks like Bleve is a full text search library, kind of what Lucene is for Java.
We are looking for distributed, scalable solutions such as Elasticsearch. However, if any distributed, bleve based DB shows up, we'll be pleased to give it a try.

**Comment by bquenin** [comment]
I just came across cbft (https://github.com/couchbase/cbft), which looks like a distributed, bleve based DB.
But it seems too early to consider such a solution.

**Comment by joeblew99** [comment]
@bquenin Yep Bleve is like Elastic Search.
But yes, you hit the nail on the head about cbft.

You can access it using the Alias command easily.
I personally prefer a non couchbase backing, and there are many: https://github.com/blevesearch/blevex

NATS-Streaming has the same need too - a store cluster.

Maybe a more generic solution is needed ?
https://www.minio.io/ is a s3 replacement and seems to have some lamda functions these days. I am going to look further into this...

**Comment by joeblew99** [comment]
https://github.com/minio/dsync

allows storage replication for free. Minio is stable now too. i used it for a while.
should work for bleve as a drop in Store factory i suspect
