### ISSUE TITLE
Engage: have volumes in stack file

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#354]
manage volume in stack file as in docker compose.
It's already done in service module and parsed in stack file
we just have to pass parameter from stack file to services to enable it

**Comment by avianey** [comment]
> It's already done in service module and parsed in stack file

 I tried `amp service create -v /some:/other ...` is it supposed to work ?

**Comment by freignat91** [comment]
It not yes integrated in amp service command, nor in stack in the current version.
It works internally using structure service description in service module for now, that's all. 
PR is on going, should be available soon if validated.
