### ISSUE TITLE
Grafana fails to start on slower hosts

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#363]
Reported by Stéphane Mercier on a laptop running Ubuntu with 16GB and a magnetic hard drive.
Grafana fails to initialize because of a timeout (not the Docker healthcheck but from the init script) reached.
It takes 25 secs to do what is usually done in ~2 secs, as can be seen below.

Logs from Stéphane's Grafana container:

> INFO - Download configuration archive file https://github.com/appcelerator/amp-config/archive/0.3.0.tar.gz...
> INFO - Overriding configuration file:
> INFO - Extra configuration file:
> /tmp/tmp.NPHfkg/amp-config-0.3.0/extra-config/grafana
> /tmp/tmp.NPHfkg/amp-config-0.3.0/extra-config/grafana/config-dashboard-AMPSwarmHealthRealtime.js
> /tmp/tmp.NPHfkg/amp-config-0.3.0/extra-config/grafana/config-dashboard-AMPLoadBalancer.js
> /tmp/tmp.NPHfkg/amp-config-0.3.0/extra-config/grafana/config-datasource-influxdb.js
> /tmp/tmp.NPHfkg/amp-config-0.3.0/extra-config/grafana/config-dashboard-AMPSwarmHealthRetention.js
> copying /etc/extra-config/grafana/config-dashboard-AMPLoadBalancer.js
> copying /etc/extra-config/grafana/config-dashboard-AMPSwarmHealthRealtime.js
> copying /etc/extra-config/grafana/config-dashboard-AMPSwarmHealthRetention.js
> converting /etc/extra-config/grafana/config-datasource-influxdb.js
> Starting grafana for configuration
> t=2016-10-20T17:46:41+0000 lvl=info msg="Starting Grafana" logger=main version=3.1.1 commit=v3.1.0+20-g2bfccd7 compiled=2016-08-01T10:47:55+0000
> t=2016-10-20T17:46:41+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
> t=2016-10-20T17:46:41+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
> t=2016-10-20T17:46:41+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
> t=2016-10-20T17:46:41+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
> t=2016-10-20T17:46:41+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.server.http_addr=127.0.0.1"
> t=2016-10-20T17:46:41+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.server.http_port=3001"
> t=2016-10-20T17:46:41+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
> t=2016-10-20T17:46:41+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
> t=2016-10-20T17:46:41+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
> t=2016-10-20T17:46:41+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
> t=2016-10-20T17:46:41+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
> t=2016-10-20T17:46:41+0000 lvl=info msg="Starting DB migration" logger=migrator
> t=2016-10-20T17:46:41+0000 lvl=info msg="Executing migration" logger=migrator id="create migration_log table"
> Checking that grafana is up...
> waiting for availability of grafana...
> .t=2016-10-20T17:46:42+0000 lvl=info msg="Executing migration" logger=migrator id="create user table"
> .t=2016-10-20T17:46:42+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index user.login"
> .t=2016-10-20T17:46:43+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index user.email"
> t=2016-10-20T17:46:43+0000 lvl=info msg="Executing migration" logger=migrator id="drop index UQE_user_login - v1"
> .t=2016-10-20T17:46:43+0000 lvl=info msg="Executing migration" logger=migrator id="drop index UQE_user_email - v1"
> .t=2016-10-20T17:46:44+0000 lvl=info msg="Executing migration" logger=migrator id="Rename table user to user_v1 - v1"
> .t=2016-10-20T17:46:44+0000 lvl=info msg="Executing migration" logger=migrator id="create user table v2"
> .t=2016-10-20T17:46:45+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_user_login - v2"
> .t=2016-10-20T17:46:45+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_user_email - v2"
> .t=2016-10-20T17:46:45+0000 lvl=info msg="Executing migration" logger=migrator id="copy data_source v1 to v2"
> .t=2016-10-20T17:46:46+0000 lvl=info msg="Executing migration" logger=migrator id="Drop old table user_v1"
> .t=2016-10-20T17:46:46+0000 lvl=info msg="Executing migration" logger=migrator id="create temp user table v1-7"
> .t=2016-10-20T17:46:46+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_temp_user_email - v1-7"
> .t=2016-10-20T17:46:47+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_temp_user_org_id - v1-7"
> .t=2016-10-20T17:46:47+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_temp_user_code - v1-7"
> .t=2016-10-20T17:46:48+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_temp_user_status - v1-7"
> .t=2016-10-20T17:46:48+0000 lvl=info msg="Executing migration" logger=migrator id="create star table"
> .t=2016-10-20T17:46:48+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index star.user_id_dashboard_id"
> .t=2016-10-20T17:46:49+0000 lvl=info msg="Executing migration" logger=migrator id="create org table v1"
> .t=2016-10-20T17:46:49+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_org_name - v1"
> .t=2016-10-20T17:46:50+0000 lvl=info msg="Executing migration" logger=migrator id="create org_user table v1"
> .t=2016-10-20T17:46:50+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_org_user_org_id - v1"
> .t=2016-10-20T17:46:50+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_org_user_org_id_user_id - v1"
> .t=2016-10-20T17:46:51+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account to org"
> t=2016-10-20T17:46:51+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account to org"
> .t=2016-10-20T17:46:51+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account_user to org_user"
> t=2016-10-20T17:46:51+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account_user to org_user"
> t=2016-10-20T17:46:51+0000 lvl=info msg="Executing migration" logger=migrator id="Drop old table account"
> .t=2016-10-20T17:46:52+0000 lvl=info msg="Executing migration" logger=migrator id="Drop old table account_user"
> t=2016-10-20T17:46:52+0000 lvl=info msg="Executing migration" logger=migrator id="create dashboard table"
> .t=2016-10-20T17:46:52+0000 lvl=info msg="Executing migration" logger=migrator id="add index dashboard.account_id"
> .t=2016-10-20T17:46:53+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index dashboard_account_id_slug"
> .t=2016-10-20T17:46:53+0000 lvl=info msg="Executing migration" logger=migrator id="create dashboard_tag table"
> ..t=2016-10-20T17:46:54+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index dashboard_tag.dasboard_id_term"
> t=2016-10-20T17:46:54+0000 lvl=info msg="Executing migration" logger=migrator id="drop index UQE_dashboard_tag_dashboard_id_term - v1"
> ..t=2016-10-20T17:46:54+0000 lvl=info msg="Executing migration" logger=migrator id="Rename table dashboard to dashboard_v1 - v1"
> .t=2016-10-20T17:46:55+0000 lvl=info msg="Executing migration" logger=migrator id="create dashboard v2"
> t=2016-10-20T17:46:55+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_dashboard_org_id - v2"
> ..t=2016-10-20T17:46:56+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_dashboard_org_id_slug - v2"
> .t=2016-10-20T17:46:56+0000 lvl=info msg="Executing migration" logger=migrator id="copy dashboard v1 to v2"
> t=2016-10-20T17:46:56+0000 lvl=info msg="Executing migration" logger=migrator id="drop table dashboard_v1"
> .t=2016-10-20T17:46:57+0000 lvl=info msg="Executing migration" logger=migrator id="alter dashboard.data to mediumtext v1"
> .t=2016-10-20T17:46:57+0000 lvl=info msg="Executing migration" logger=migrator id="Add column updated_by in dashboard - v2"
> .t=2016-10-20T17:46:58+0000 lvl=info msg="Executing migration" logger=migrator id="Add column created_by in dashboard - v2"
> .t=2016-10-20T17:46:58+0000 lvl=info msg="Executing migration" logger=migrator id="Add column gnetId in dashboard"
> .t=2016-10-20T17:46:58+0000 lvl=info msg="Executing migration" logger=migrator id="Add index for gnetId in dashboard"
> .t=2016-10-20T17:46:59+0000 lvl=info msg="Executing migration" logger=migrator id="Add column plugin_id in dashboard"
> .t=2016-10-20T17:46:59+0000 lvl=info msg="Executing migration" logger=migrator id="Add index for plugin_id in dashboard"
> .t=2016-10-20T17:46:59+0000 lvl=info msg="Executing migration" logger=migrator id="create data_source table"
> .t=2016-10-20T17:47:00+0000 lvl=info msg="Executing migration" logger=migrator id="add index data_source.account_id"
> .t=2016-10-20T17:47:00+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index data_source.account_id_name"
> .t=2016-10-20T17:47:01+0000 lvl=info msg="Executing migration" logger=migrator id="drop index IDX_data_source_account_id - v1"
> .t=2016-10-20T17:47:01+0000 lvl=info msg="Executing migration" logger=migrator id="drop index UQE_data_source_account_id_name - v1"
> t=2016-10-20T17:47:01+0000 lvl=info msg="Executing migration" logger=migrator id="Rename table data_source to data_source_v1 - v1"
> .t=2016-10-20T17:47:02+0000 lvl=info msg="Executing migration" logger=migrator id="create data_source table v2"
> .t=2016-10-20T17:47:02+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_data_source_org_id - v2"
> ..t=2016-10-20T17:47:03+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_data_source_org_id_name - v2"
> t=2016-10-20T17:47:03+0000 lvl=info msg="Executing migration" logger=migrator id="copy data_source v1 to v2"
> .t=2016-10-20T17:47:03+0000 lvl=info msg="Executing migration" logger=migrator id="Drop old table data_source_v1 #2"
> .t=2016-10-20T17:47:04+0000 lvl=info msg="Executing migration" logger=migrator id="Add column with_credentials"
> .t=2016-10-20T17:47:04+0000 lvl=info msg="Executing migration" logger=migrator id="create api_key table"
> .t=2016-10-20T17:47:05+0000 lvl=info msg="Executing migration" logger=migrator id="add index api_key.account_id"
> .t=2016-10-20T17:47:05+0000 lvl=info msg="Executing migration" logger=migrator id="add index api_key.key"
> .t=2016-10-20T17:47:05+0000 lvl=info msg="Executing migration" logger=migrator id="add index api_key.account_id_name"
> .t=2016-10-20T17:47:06+0000 lvl=info msg="Executing migration" logger=migrator id="drop index IDX_api_key_account_id - v1"
> .ERROR: unable to start grafana after 60 \* 0.4 sec

Logs from a normal behaving container:

> INFO - Download configuration archive file https://github.com/appcelerator/amp-config/archive/0.4.0.tar.gz...
> INFO - Overriding configuration file:
> INFO - Extra configuration file:
> /tmp/tmp.AOhmCJ/amp-config-0.4.0/extra-config/grafana
> /tmp/tmp.AOhmCJ/amp-config-0.4.0/extra-config/grafana/config-dashboard-AMPLoadBalancer.js
> /tmp/tmp.AOhmCJ/amp-config-0.4.0/extra-config/grafana/config-datasource-influxdb.js
> /tmp/tmp.AOhmCJ/amp-config-0.4.0/extra-config/grafana/config-dashboard-AMPSwarmHealthRealtime.js
> /tmp/tmp.AOhmCJ/amp-config-0.4.0/extra-config/grafana/config-dashboard-AMPSwarmHealthRetention.js
> copying /etc/extra-config/grafana/config-dashboard-AMPLoadBalancer.js
> copying /etc/extra-config/grafana/config-dashboard-AMPSwarmHealthRealtime.js
> copying /etc/extra-config/grafana/config-dashboard-AMPSwarmHealthRetention.js
> converting /etc/extra-config/grafana/config-datasource-influxdb.js
> Starting grafana for configuration
> t=2016-10-21T07:55:33+0000 lvl=info msg="Starting Grafana" logger=main version=3.1.1 commit=v3.1.0+20-g2bfccd7 compiled=2016-08-01T10:47:55+0000
> t=2016-10-21T07:55:33+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
> t=2016-10-21T07:55:33+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.server.http_addr=127.0.0.1"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.server.http_port=3001"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
> t=2016-10-21T07:55:33+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
> t=2016-10-21T07:55:33+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
> t=2016-10-21T07:55:33+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
> t=2016-10-21T07:55:33+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
> t=2016-10-21T07:55:33+0000 lvl=info msg="Starting DB migration" logger=migrator
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="create migration_log table"
> Checking that grafana is up...
> waiting for availability of grafana...
> .t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="create user table"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index user.login"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index user.email"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="drop index UQE_user_login - v1"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="drop index UQE_user_email - v1"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="Rename table user to user_v1 - v1"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="create user table v2"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_user_login - v2"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_user_email - v2"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="copy data_source v1 to v2"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="Drop old table user_v1"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="create temp user table v1-7"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_temp_user_email - v1-7"
> .t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_temp_user_org_id - v1-7"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_temp_user_code - v1-7"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_temp_user_status - v1-7"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="create star table"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index star.user_id_dashboard_id"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="create org table v1"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_org_name - v1"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="create org_user table v1"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_org_user_org_id - v1"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_org_user_org_id_user_id - v1"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account to org"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account to org"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account_user to org_user"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account_user to org_user"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="Drop old table account"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="Drop old table account_user"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="create dashboard table"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="add index dashboard.account_id"
> t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index dashboard_account_id_slug"
> .t=2016-10-21T07:55:33+0000 lvl=info msg="Executing migration" logger=migrator id="create dashboard_tag table"
> t=2016-10-21T07:55:34+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index dashboard_tag.dasboard_id_term"
> t=2016-10-21T07:55:34+0000 lvl=info msg="Executing migration" logger=migrator id="drop index UQE_dashboard_tag_dashboard_id_term - v1"
> t=2016-10-21T07:55:34+0000 lvl=info msg="Executing migration" logger=migrator id="Rename table dashboard to dashboard_v1 - v1"
> t=2016-10-21T07:55:34+0000 lvl=info msg="Executing migration" logger=migrator id="create dashboard v2"
> t=2016-10-21T07:55:34+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_dashboard_org_id - v2"
> t=2016-10-21T07:55:34+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_dashboard_org_id_slug - v2"
> t=2016-10-21T07:55:34+0000 lvl=info msg="Executing migration" logger=migrator id="copy dashboard v1 to v2"
> t=2016-10-21T07:55:34+0000 lvl=info msg="Executing migration" logger=migrator id="drop table dashboard_v1"
> t=2016-10-21T07:55:34+0000 lvl=info msg="Executing migration" logger=migrator id="alter dashboard.data to mediumtext v1"
> t=2016-10-21T07:55:34+0000 lvl=info msg="Executing migration" logger=migrator id="Add column updated_by in dashboard - v2"
> .t=2016-10-21T07:55:34+0000 lvl=info msg="Executing migration" logger=migrator id="Add column created_by in dashboard - v2"
> t=2016-10-21T07:55:34+0000 lvl=info msg="Executing migration" logger=migrator id="Add column gnetId in dashboard"
> t=2016-10-21T07:55:34+0000 lvl=info msg="Executing migration" logger=migrator id="Add index for gnetId in dashboard"
> t=2016-10-21T07:55:34+0000 lvl=info msg="Executing migration" logger=migrator id="Add column plugin_id in dashboard"
> t=2016-10-21T07:55:34+0000 lvl=info msg="Executing migration" logger=migrator id="Add index for plugin_id in dashboard"
> t=2016-10-21T07:55:34+0000 lvl=info msg="Executing migration" logger=migrator id="create data_source table"
> t=2016-10-21T07:55:34+0000 lvl=info msg="Executing migration" logger=migrator id="add index data_source.account_id"
> t=2016-10-21T07:55:34+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index data_source.account_id_name"
> t=2016-10-21T07:55:34+0000 lvl=info msg="Executing migration" logger=migrator id="drop index IDX_data_source_account_id - v1"
> t=2016-10-21T07:55:34+0000 lvl=info msg="Executing migration" logger=migrator id="drop index UQE_data_source_account_id_name - v1"
> .t=2016-10-21T07:55:34+0000 lvl=info msg="Executing migration" logger=migrator id="Rename table data_source to data_source_v1 - v1"
> t=2016-10-21T07:55:34+0000 lvl=info msg="Executing migration" logger=migrator id="create data_source table v2"
> t=2016-10-21T07:55:34+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_data_source_org_id - v2"
> t=2016-10-21T07:55:34+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_data_source_org_id_name - v2"
> t=2016-10-21T07:55:34+0000 lvl=info msg="Executing migration" logger=migrator id="copy data_source v1 to v2"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="Drop old table data_source_v1 #2"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="Add column with_credentials"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="create api_key table"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="add index api_key.account_id"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="add index api_key.key"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="add index api_key.account_id_name"
> .t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="drop index IDX_api_key_account_id - v1"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="drop index UQE_api_key_key - v1"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="drop index UQE_api_key_account_id_name - v1"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="Rename table api_key to api_key_v1 - v1"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="create api_key table v2"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_api_key_org_id - v2"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_api_key_key - v2"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_api_key_org_id_name - v2"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="copy api_key v1 to v2"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="Drop old table api_key_v1"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="create dashboard_snapshot table v4"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="drop table dashboard_snapshot_v4 #1"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="create dashboard_snapshot table v5 #2"
> .t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_dashboard_snapshot_key - v5"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_dashboard_snapshot_delete_key - v5"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_dashboard_snapshot_user_id - v5"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="alter dashboard_snapshot to mediumtext v2"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="create quota table v1"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_quota_org_id_user_id_target - v1"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="create plugin_setting table"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_plugin_setting_org_id_plugin_id - v1"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="Add column plugin_version to plugin_settings"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="create session table"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="Drop old table playlist table"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="Drop old table playlist_item table"
> t=2016-10-21T07:55:35+0000 lvl=info msg="Executing migration" logger=migrator id="create playlist table v2"
> .t=2016-10-21T07:55:36+0000 lvl=info msg="Executing migration" logger=migrator id="create playlist item table v2"
> t=2016-10-21T07:55:36+0000 lvl=info msg="Executing migration" logger=migrator id="drop preferences table v2"
> t=2016-10-21T07:55:36+0000 lvl=info msg="Executing migration" logger=migrator id="drop preferences table v3"
> t=2016-10-21T07:55:36+0000 lvl=info msg="Executing migration" logger=migrator id="create preferences table v3"
> t=2016-10-21T07:55:36+0000 lvl=info msg="Created default admin user: [admin]"
> t=2016-10-21T07:55:36+0000 lvl=info msg="Starting plugin search" logger=plugins
> t=2016-10-21T07:55:36+0000 lvl=info msg="Server Listening" logger=server address=127.0.0.1:3001 protocol=http subUrl=
> t=2016-10-21T07:55:36+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=127.0.0.1 time_ns=0s size=29
> <a href="/login">Found</a>.
> 
> configure datasources...
> datasource /etc/grafana/config-datasource-influxdb.js
> {"id":1,"message":"Datasource added"}
> configure dashboards...
> dashboard /etc/grafana/config-dashboard-AMPLoadBalancer.js
> {"slug":"amp-load-balancers-realtime","status":"success","version":0}dashboard /etc/grafana/config-dashboard-AMPSwarmHealthRealtime.js
> {"slug":"amp-swarm-health-realtime","status":"success","version":0}dashboard /etc/grafana/config-dashboard-AMPSwarmHealthRetention.js
> {"slug":"amp-swarm-health-historical","status":"success","version":0}
> Restarting grafana...
> 
> t=2016-10-21T07:55:36+0000 lvl=info msg="Received signal [terminated]. shutting down"
> Plugin installation...
> 
> t=2016-10-21T07:55:36+0000 lvl=info msg="Starting Grafana" logger=main version=3.1.1 commit=v3.1.0+20-g2bfccd7 compiled=2016-08-01T10:47:55+0000

**Comment by smercier74** [comment]
I tested the image grafana-3.1 instead of grafana-3.1.1 and it starts fine. The grafana web ui http://grafana.local.axwaytest.net/dashboard/db/amp-swarm-health-realtime is reachable. I notice a high hard drive activity on my machine all the time. Maybe grafana or dockerd did a lot of I/O

ID            NAME              REPLICAS  IMAGE                                   COMMAND
0rcywf3wdbq8  elasticsearch     1/1       appcelerator/elasticsearch-amp:2.3.3  
17i7zn79rzjm  grafana           1/1       appcelerator/grafana:grafana-3.1  
212x0rsklnup  influxdb          1/1       appcelerator/influxdb:influxdb-1.0.2  
2zb6x37as2h6  telegraf-haproxy  1/1       appcelerator/telegraf:telegraf-1.0.1  
3d6cn3s2wq9d  amp-ui            1/1       appcelerator/amp-ui:0.2.0  
56176cxt9eme  nats              1/1       appcelerator/amp-nats-streaming:0.2.2  
5vnabh9rbqf9  haproxy           1/1       appcelerator/haproxy:1.0.1  
6rp4xzs25o36  kapacitor         1/1       appcelerator/kapacitor:kapacitor-1.0.2  
8hggbjd92kau  telegraf-agent    global    appcelerator/telegraf:telegraf-1.0.1  
boqgz77r2b8w  amp-agent         global    appcelerator/amp:0.2.0                  amp-agent
c5bi05ahkeco  amplifier         1/1       appcelerator/amp:0.2.0  
c8vlec1szlil  amp-log-worker    1/1       appcelerator/amp:0.2.0                  amp-log-worker
cjtch14hwgn1  etcd              1/1       appcelerator/etcd:3.0.12                --name etcd --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://etcd:2379
d7qyhzct42nw  registry          1/1       registry:2.5.1

**Comment by ndegory** [comment]
:+1:
