### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#370]
We need to increase test coverage and extend integration tests to include networking, etc (see current integration tests [here](https://docs.google.com/spreadsheets/d/1i_fZ9ArzQwnePRPpudxk69f4_CIYk7WBMX73m1IOifY/edit?usp=sharing)).

Work on removing any redundancy with current backend integration tests (ie, those that require starting amplifier), that can be defined by yaml test specs and added [here](https://github.com/appcelerator/amp/tree/master/cmd/amp/cli/test_samples).

**Comment by bquenin** [comment]
Do you mind if I submit a PR for renaming the test files from:

```
00-invalid-sample-01.yml
00-invalid-sample-02.yml
01-create-service.yml
02-list-service.yml
03-curl-service.yml
04-remove-service.yml
05-create-stack.yml
06-list-stack.yml
07-stop-stack.yml
08-restart-stack.yml
09-remove-stack.yml
10-cpu-stats.yml
11-mem-stats.yml
12-io-stats.yml
13-task-stats.yml
14-container-stats.yml
15-net-stats.yml
16-node-stats.yml
17-service-stats.yml
18-stack-logs.yml
19-numbered-logs.yml
20-metadata-logs.yml
21-all-logs.yml
```

to

```
00-invalid-sample-01.yml
00-invalid-sample-02.yml
01-service-create.yml
02-service-list.yml
03-service-curl.yml
04-service-remove.yml
05-stack-create.yml
06-stack-list.yml
07-stack-stop.yml
08-stack-restart.yml
09-stack-remove.yml
10-stats-cpu.yml
11-stats-mem.yml
12-stats-io.yml
13-stats-task.yml
14-stats-container.yml
15-stats-net.yml
16-stats-node.yml
17-stats-service.yml
18-logs-stack.yml
19-logs-numbered.yml
20-logs-metadata.yml
21-logs-all.yml
```

?

**Comment by ndegory** [comment]
@bquenin if you can wait a bit before renaming the yaml files, I have a PR (#375) in progress impacting those files, thanks.

**Comment by subfuzion** [comment]
I'd like them renamed, but there is no reason for them to be numbered sequentially, giving a false sense of them running in order (see discussion here: https://github.com/appcelerator/amp/issues/374#issuecomment-255879628). Just drop the numbers altogether.

Also, let's get rid of "invalid". That was copied over from the stack file parse tests where it made sense to indicate that the stack file format was invalid. In addition to having support for expected output (which can be an error message just as much as it can be anything else), we should also support an expected exit code. It's not a bad idea to have a key for each test case that does indicated it is a negative ("unhappy") case test just so we can keep track and report in test results.

cc/ @ndegory @bquenin @JosephGJ @neha-viswanathan @generalhenry

**Comment by ndegory** [comment]
IMO current status of CLI tests justifies that we close this PR (in time for 0.3.0)

**Comment by subfuzion** [comment]
We made good progress on testing. This is an ongoing effort, so I'm going to update the milestone.
