### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#371]
Right now we generating any test coverage metrics to give us any insight into our test strategy. Implementing a `cover` rule in our Makefile will allow us to automate the generation of coverage statics that runs `go test cover` / `go test -cover*` commands (see this [article](https://blog.golang.org/cover) for inspiration.

**Comment by subfuzion** [comment]
I propose that @generalhenry take this, but if anyone else wants to, go for it...

**Comment by generalhenry** [comment]
The slightly tricky bit is that we are moving to integration tests where go test is only running our expectations, and shelling out to amp.  We'll need to build an instrumented amp binary for testing.

https://blog.cloudflare.com/go-coverage-with-external-tests/ looks like a good lead on the topic

**Comment by generalhenry** [comment]
sample coverall:

``` bash
#!/bin/sh

echo "mode: set" > coverage-all.out;
go test github.com/appcelerator/amp/api/rpc/logs -coverprofile=logs.out;
tail -n +2 logs.out >> coverage-all.out;
go test github.com/appcelerator/amp/api/rpc/service -coverprofile=service.out;
tail -n +2 service.out >> coverage-all.out;
go test github.com/appcelerator/amp/data/storage/etcd -coverprofile=letcd.out;
tail -n +2 etcd.out >> coverage-all.out;
go test github.com/appcelerator/amp/api/rpc/stack -coverprofile=stack.out;
tail -n +2 stack.out >> coverage-all.out;
go test github.com/appcelerator/amp/data/influx -coverprofile=influx.out;
tail -n +2 influx.out >> coverage-all.out;
go test github.com/appcelerator/amp/api/rpc/stats -coverprofile=stats.out;
tail -n +2 stats.out >> coverage-all.out;
go test github.com/appcelerator/amp/api/rpc/topic -coverprofile=topic.out;
tail -n +2 topic.out >> coverage-all.out;
go tool cover -html=coverage-all.out;
```

makefile example:
https://gist.github.com/skarllot/13ebe8220822bc19494c8b076aabe9fc

**Comment by generalhenry** [comment]
Problem:
  While go coverage has great support for unit test, coverage for integration tests is hacky at best at them moment.

Solution A:
  skip integration test coverage, but have to work on our unit tests to bring coverage up.

Solution B:
  implement/maintain test coverage on our integration tests, lowering our need to write unit test.

IMO it would be best to stick to solution a for now which means we add support in our make file to run the unit tests (all tests over than the cli tests) with coverage and combine the output into a single report.  We can then open up issues for areas of low coverage.

**Comment by subfuzion** [comment]
As we discussed yesterday, let's focus on coverage metrics for the unit tests for now. Let's put our heads together on how we can get a better sense of how effective our integration tests are from the CLI perspective. To me for now at least that implies we are testing our commands for all the combinations of options that are valid and invalid and confirm that we get the positive or negative results that we expect.
