### ISSUE TITLE
Stack Examples

### ISSUE THREAD

**Issue by generalhenry** [appcelerator-archive/amp#376]
In addition to our stack `test_samples` create a folder of example stacks representing demoable use cases complete with `readme`s

**Comment by subfuzion** [comment]
Let's put an `examples` folder at the top level for now and then specific examples with their own `README.md` files in subdirectories. We can keep the subdirectories flat for now. A top level `examples/README.md` should provide a general overview.

**Comment by subfuzion** [comment]
Thanks for adding the first example, Henry. Closing this issue now since I've opened one for general examples, not just stacks. Let's use that one for discussion.
