### ISSUE TITLE
etcd failing to start

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#377]
appcelerator/etcd:3.1 (based on [etcd v3.1.0-rc.0](https://github.com/coreos/etcd/tree/v3.1.0-rc.0)) fails to start. Rolling back to 3.0 fixes. The swarm script should specify `3.0` until `3.1` is verified to work.

**Comment by ndegory** [comment]
this is (another) Docker for Mac issue, working fine on Linux.
