### ISSUE TITLE
amp config (get/set)

### ISSUE THREAD

**Issue by generalhenry** [appcelerator-archive/amp#401]
Add the ability to get/set individual configuration fields eg `amp config set server localhost:8080`

Alternatively `amp config server localhost:8080`

**Comment by subfuzion** [comment]
Yes, what I was talking about is similar to how `git config` works, so `get`/`set` not explicitly required, just the alternative implicit version:

```
# get
$ amp config verbose
false

# set
$ amp config verbose true

# list
$ amp config config --list
verbose: true
server localhost:50101

# unset
$ amp config --unset verbose
$ amp config verbose
error: key not present: verbose
$ amp config --list
server localhost:50101
```

Also nice to have: options for specifying `--global`, `--local`, and `-f`|`--file` settings.
