### ISSUE TITLE
amp logs <stack> too chatty

### ISSUE THREAD

**Issue by generalhenry** [appcelerator-archive/amp#407]
Expected:
```
$ amp logs websocket
listening on 4000
received: something from the client
```

Actual:
```
$ amp logs websocket
listening on 4000
HAProxy controller version 1.1.0-10  (build:af714ef8)
ETCD endpoints [etcd:2379]
Role: Stack: websocket
Connected to etcd: [etcd:2379]
update HAProxy configuration
process service Id:ee3650bonqxhalpvkqjp005fm
process service Id:ayy636nt2irz48mvhu0wxq8vl
add service websocket-micro mapping: ws
    use_backend bk_websocket-micro4000 if { hdr_beg(host) -i ws. }

backend bk_websocket-micro4000
    server websocket-micro_1 websocket-micro:4000 check resolvers docker resolve-prefer ipv4
HAProxy configuration updated
Start API server on port 8090
launching HAProxy on initial configuration
Waiting for update on  amp/stacks/501048c559c9b347a39cab536343b05b926ecd9660e57a7355e247f32c23ff3f/services
received: something from the client
```

While the infrastructure logs should be available, they should be behind a flag (-v  or the like)

**Comment by freignat91** [comment]
Perhaps, it's more a matter of naming convention. Currently a stack HAProxy name is prefixed with its stack name as any other stack user services which makes the command amp logs [stackName] display its logs.
Considering that a stack HAProxy is more an infrastructure component even dedicated to the stack, we can rename it to haproxy-[stackName] then any commands (not only logs but also stats) using stack name will take in account only the true user services.
?

**Comment by generalhenry** [comment]
@freignat91 that sounds like a good solution.

**Comment by bquenin** [comment]
Hi, after discussion with François, we think that the best option is to filter on a specific criteria to be able to distinguish between `infrastructure` and `user` services.

The idea is to modify `amp-agent` to get the labels of the container and to add it to the log entry as well.
This way, `amp logs` can filter out all infrastructure logs. Of course, I will also add a flag on the command line to display infrastructure logs if required (disabled by default).
