### ISSUE TITLE
Have a amp test service to test multi-nodes environment on powerful way

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#410]
related to #301
for tests, we have on one hand:
- (1): Tests on server side as the ones executed launching `make test`. They are powerful because we can analyse returned struct data and any service status if needed, but these tests doesn't work on amp cluster having several nodes and need to start for each a separate amplifier.

on the other hand we have:

- (2): Tests on client side as the ones executed launching `go test -v ./cmd/amp/cli`. They are interesting because they work on any amp cluster, but because these tests work only using console output results, they doesn't allow us to perform powerful verification without a big parsing effort when it's possible (when needed data are in the results)

We need something in addition to (2), replacing (1) and able to work on amp cluster having several nodes.

We could develop a dedicated amp infrastructure test service, build as any other service, so able to connect naturally to any other services including the running amplifier service (or optionally a local amplifier instead) and having as tests all the server side tests we already have (or will have), then we have a way to test any amp clusters without having to launch several time amplifier, in the exact final environment if needed.

For instance, this test service could just start with a volume on amp project and run `make test`, if we refactor the tests in order to do not start a dedicated amplifier themselves.
This service will be a start/run/stop service.  We could have the equivalent of `make test`, but running on any environments.

What do you think?

**Comment by ndegory** [comment]
related to #301, I have a local branch where I'm trying to solve this issue, we can discuss about it @freignat91

**Comment by freignat91** [comment]
ok!

**Comment by bquenin** [comment]
I agree with François, after discussion, we ended up with the following table:

| | `amplifier` running locally  | `amplifier` running as a service in the swarm | 
|----|----|----|
| `swarm` running locally | This where we are today | This is our target for local swarm tests| 
| `swarm` running remotely | Not covered today and not required | This is our target for remote swarm tests | 

Also note that our tests would also be running a service in the swarm, which is not the case today.
