### ISSUE TITLE
Service rm should return service id

### ISSUE THREAD

**Issue by generalhenry** [appcelerator-archive/amp#413]
In order to be consistent `amp service rm <ident>` should return the service id rather than `<ident>`

**Comment by chrisccoy** [comment]
https://docs.docker.com/engine/reference/commandline/service_rm/

**Comment by generalhenry** [comment]
Interesting.  It looks like `docker rm <ident>` has the same behavior as well, which makes some sense considering that the [remove api](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/remove-a-container) has no return data.

So that means in order to be consistent with docker we would want to remove the return data from all our remove APIs, and adjust the CLI to return the given ident.
