### ISSUE TITLE
Add build commands to CLI

### ISSUE THREAD

**Issue by generalhenry** [appcelerator-archive/amp#42]
Proposed commands:

``` bash
amp build register appcelerator/amp
amp build remove appcelerator/amp
amp build listprojects -o appcelerator -lq
amp build listbuilds  -lq appcelerator/amp
amp build logs appcelerator/amp/8becef4ef8c5e6082ca09bd2b5dd3e71882fd772
amp build rebuild appcelerator/amp/8becef4ef8c5e6082ca09bd2b5dd3e71882fd772
```

**Comment by subfuzion** [comment]
Relates to https://github.com/appcelerator/amp/issues/13

**Comment by subfuzion** [comment]
Looks good to me for now.

You wanted monotonically increasing build numbers to make nice URLs and build reports, so maybe you can also accept build numbers as well as uuid's for at least the logs command...  ;)

**Comment by freignat91** [comment]
LGTM too, but for 'amp build logs appcelerator/amp/xxx, where do you got the xxxx?
For 'amp rebuild', do we need to give more than the project name, so 'amp rebuild appcelerator/amp" for amp?

**Comment by generalhenry** [comment]
@freignat91 the easiest place to get the `<owner>/<repo>/<sha>` is to run a `amp build listbuilds <owner>/<repo> -q` which will list the builds in the right format

**Comment by subfuzion** [comment]
@generalhenry ... which means maybe you also want to support `-l` (eg, `-lq`) to get the last build.

**Comment by generalhenry** [comment]
@subfuzion Already implemented :)

**Comment by subfuzion** [comment]
@generalhenry Looking very good. Need a command to start a build for `appcelerator/amp`.

**Comment by subfuzion** [comment]
@generalhenry nvm, apparently those are commitish SHAs. I'll try to do it with `rebuild`.

However, I think something like the following would be very useful commands:

```
$amp build <commitish>`

$ amp build <project> <branch>
```

**Comment by subfuzion** [comment]
Hmm this doesn't work:

```
$ amp build rebuild appcelerator/amp/c4015d02fbc60583a4cd82187eb99d3aac3b36e4
amp (cli version: 1.0.0, build: ae1ae94f)
rpc error: code = 2 desc = Build not found
```

**Comment by generalhenry** [comment]
Yeah rebuild checks for the build's existence, I could make it not do that, but I'd rather not mess with the semantics.

How about `amp build newbuild appcelerator/amp/c4015d02fbc60583a4cd82187eb99d3aac3b36e4` which does the same thing as rebuild but with the inverse existence check.

Alternatively it could be `amp build trigger appcelerator/amp/c4015d02fbc60583a4cd82187eb99d3aac3b36e4` which doesn't care if the build exists or not

**Comment by subfuzion** [comment]
Honestly, I'm not crazy about the semantics actually and want to revisit it, but don't want to bikeshed over it at the moment. I'm happy with the evolving functionality, and that's the important thing for now.

**Comment by subfuzion** [comment]
Yeah, `trigger` would essentially be the CLI interface to correspond to what I basically had in mind with the trigger endpoint I asked for [here](https://github.com/appcelerator/amp-build/issues/4), ie, something a user can request anytime regardless of whether there is an existing build. I do see value in allowing the user to also be able to specify in addition to commits the branch itself (which is essentially a reference to the commit at the tip of the branch), as I described above.

**Comment by subfuzion** [comment]
I'm going to close this issue now. We can open new ones for continuing enhancements.
