### ISSUE TITLE
Agent Logging

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#430]
`amp-agent` currently captures various Docker events plus container stdout/err streams and forwards them over the message queue for storage (buffering messages until these services are available).

However, when we are bootstrapping the swarm, Docker is logging events that we are either not capturing or currently not making available via the log query api/command.

We need to ensure that we have a strategy for configuring the log level we want to capture and ensuring these log events are stored and able to be queried for analysis, particularly in the case of failures.

Analysis:

This [gist](https://gist.github.com/subfuzion/f3e43dfd2e95180790dd6e136b53dc9a) is a sample of the output that was logged by Docker to the system log file when starting the amp swarm, and this [gist](https://gist.github.com/subfuzion/00372ee27dd7d2c71f18af614ea6706d) is a sample from the system log when stopping the swarm.

This is an example of an error that was taken from the log from an earlier run:

    time="2016-11-08T05:51:32.330296008Z" level=error msg="remove task failed" error="network amp-infra not found" module=taskmanager task.id=all29mw6grz5n0qog1czrg2d7

The system log file gets very large. On my laptop it is currently > 2 GB. This [gist](https://gist.github.com/subfuzion/166f9561fd1b6c9486fa664e700c66de) shows the first 100 lines. This is the location of the log on my laptop running Docker for Mac:

    $ head -n 100  ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/log/docker.log

Log file locations depend on OS (see [this stackoverflow answer](http://stackoverflow.com/questions/30969435/where-is-the-docker-daemon-log/30970134#answer-30970134)).

Events are constantly being logged; for example, health checks:

```
time="2016-11-08T06:28:10.582610291Z" level=debug msg="attach: stderr: end"
time="2016-11-08T06:28:10.582760709Z" level=debug msg="attach: stdout: end"
time="2016-11-08T06:28:10.583468340Z" level=debug msg="Health check done (exitCode=0)"
time="2016-11-08T06:28:10.625677483Z" level=debug msg="containerd: process exited" id=be5d7c493951b01b6c32904701a783112d276b4712e93034dee54754358f9a0f pid=cf3d2d4a66e692790a455fd6acfc8418e8b4b45944e62b493f1d26578fb9794a status=0 systemPid=7574
```

When stopping the swarm I noted the following:

```
$ tail -f  ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/log/docker.log | grep "level=error"
time="2016-11-08T06:36:25.488133552Z" level=error msg="network amp-infra remove failed: network amp-infra not found" module=taskmanager task.id=46dk4y1shx2up14hu2og8mopv
time="2016-11-08T06:36:25.488728597Z" level=error msg="remove task failed" error="network amp-infra not found" module=taskmanager task.id=46dk4y1shx2up14hu2og8mopv
```

And when starting it:

```
time="2016-11-08T06:37:59.817768588Z" level=error msg="Failed to create real server 10.0.0.8 for vip 10.0.0.6 fwmark 409 in sb fc1ae0730825b06c1d3e0afa45998411579dc8430c83dd5069a268c39f3b514f: no such process"
time="2016-11-08T06:38:01.086899609Z" level=error msg="Failed to create a new service for vip 10.0.0.6 fwmark 409: file exists"
time="2016-11-08T06:38:05.443163867Z" level=error msg="Failed to create real server 10.0.0.37 for vip 10.0.0.36 fwmark 420 in sb 73db2238eb418d473ad2f8f89d4c2c565aa80e18d2a41d5b527a34c5e17a0e4e: no such process"
time="2016-11-08T06:38:05.493028246Z" level=error msg="Failed to create real server 10.0.0.20 for vip 10.0.0.18 fwmark 421 in sb 92bf3fd731178d25de5cca28fb52bf2bb9599c6a43417306c05870854cc7be5a: no such process"
time="2016-11-08T06:38:05.935155785Z" level=error msg="Failed to create real server 10.0.0.23 for vip 10.0.0.22 fwmark 422 in sb 290422d1af660c612545f3f88e3f1e53016fc95ff6636a6ef138a72446fe5727: no such process"
time="2016-11-08T06:38:07.540969255Z" level=error msg="Failed to create real server 10.0.0.43 for vip 10.0.0.41 fwmark 424 in sb 52a12a9e3084af52e15069712d2ad42134d238496e0dfc0c889af68561c70551: no such process"
time="2016-11-08T06:38:07.542136545Z" level=error msg="Failed to create real server 10.0.0.43 for vip 10.0.0.41 fwmark 424 in sb 0e4c012f8f309c70e6db5229bb655a151465fe10ce53b47718f0a02638560564: no such process"
time="2016-11-08T06:38:08.074276438Z" level=error msg="Failed to create real server 10.0.0.28 for vip 10.0.0.26 fwmark 423 in sb 53d476813e00426fbda29f5134232b0f0767d923fe0c4b120dd9d0c0b69d323a: no such process"
time="2016-11-08T06:38:08.075343029Z" level=error msg="Failed to create real server 10.0.0.28 for vip 10.0.0.26 fwmark 423 in sb 52a12a9e3084af52e15069712d2ad42134d238496e0dfc0c889af68561c70551: no such process"
time="2016-11-08T06:38:08.075983648Z" level=error msg="Failed to create real server 10.0.0.28 for vip 10.0.0.26 fwmark 423 in sb 8db8fec15f8e6f4c370c07c5681195622427054edfbf2b6f877674b33b323732: no such process"
...
(there were a number of these)
...
time="2016-11-08T06:38:20.467471840Z" level=error msg="Failed to delete a new service for vip 10.0.0.6 fwmark 409: no such process"
time="2016-11-08T06:38:20Z" level=error msg="setting up rule failed, [-t mangle -D OUTPUT -d 10.0.0.6/32 -j MARK --set-mark 409]:  (iptables failed: iptables --wait -t mangle -D OUTPUT -d 10.0.0.6/32 -j MARK --set-mark 409: iptables: No chain/target/match by that name.\n (exit status 1))"
time="2016-11-08T06:38:20.579229227Z" level=error msg="Failed to add firewall mark rule in sbox /var/run/docker/netns/0b9a1a2af825: reexec failed: exit status 5"
time="2016-11-08T06:38:21.612542339Z" level=error msg="Failed to create a new service for vip 10.0.0.32 fwmark 426: file exists"
time="2016-11-08T06:38:21.731232883Z" level=error msg="Failed to create a new service for vip 10.0.0.32 fwmark 426: file exists"
time="2016-11-08T06:38:21.770242574Z" level=error msg="fatal task error" error="task: non-zero exit (1)" module=taskmanager task.id=8a7gn49z0us7cqjjtugnkfvij
time="2016-11-08T06:38:21.864845273Z" level=error msg="Failed to create a new service for vip 10.0.0.26 fwmark 423: file exists"
```

**Comment by bquenin** [comment]
Hi, I had a look at this issue and here is the status:

It seems that it's not possible to consistently get logs from the docker daemon, or at least, not in a portable manner.

 **dockerd** (the docker daemon):
- `dockerd` logs everything to `stdout` by default and doesn't support any configuration to alter this behavior as you can see in the source code of the daemon itself: https://github.com/docker/docker/blob/ba41a5edac16857121779434cd80b86dcdb0ffda/cmd/dockerd/docker.go#L96-L100
- There is also no configuration option to change this behavior as seen in the source code here: https://github.com/docker/docker/blob/165a3d0a7530b20167b99dace601a00a46a99dfa/daemon/config.go#L79-L147
- the docker team package `dockerd` with OS specific packager, then the OS specific package is responsible for dealing with logs. For instance, on Debian/Ubuntu, the logs are managed directly b y `systemd` and `journald`.

It seems difficult to hook into this kind of architecture to get the logs from the file itself.

Alternatives:
- **Docker events**: Another approach would be to logs docker events for each containers, service, tasks, and store it in elasticsearch in another index. This would mimic the `docker events` command behavior. Unfortunately, the docker events and docker daemon logs don't contain the same information, even though there is an overlap.
- **Docker API**: Unfortunately, there is no way to get the daemon log stream from the docker API itself.

**Comment by subfuzion** [comment]
@bquenin Thanks for the research/analysis. I see what you mean. As you mentioned the `docker events` command provides some overlap with the daemon log. I'm not sure how useful this is in diagnosing amp infrastructure issues, however, especially if we ensure that our bootstrapper reports errors as it runs. I think we can safely table this for now.
