### ISSUE TITLE
amp logs without arguments shouldn't be an error

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#431]
This is the current output from running `amp logs` without any arguments:

```
$ amp logs
Error during:  Fetch log entries matching provided criteria. If provided, SERVICE can be a partial or full service id or service name.
```

The command should return default logs (eg, *everything*) or it should default to displaying a help message. Either is better than showing an error.

**Comment by bquenin** [comment]
I'm on it
