### ISSUE TITLE
etcd failure

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#433]
At today's demo, CLI tests failed for @neha-viswanathan and @JosephGJ apparently because etcd was continuously failing. Analysis is needed to determine what might have been causing the failure, but more importantly a strategy is needed to ensure reliability. There are a number of things to consider:

* I didn't notice etcd cycling between running and failed; I just saw 1/1 replicas (which would imply to me that perhaps the healthcheck isn't as robust as it should be if it needed to be restarted). However, @JosephGJ did say he saw it cycle a few times before the demo started.

* If it cycled during the tests, the tests may have failed because state was not preserved. Even though we mount a volume for /data (since [this PR](https://github.com/appcelerator/amp/pull/281/files#diff-6b3d43184271885b9fb260c59821d5e8R268)), it's possible that the tests failed when attempting to store data, not when attempting to retrieve it.

* It should be possible to review @neha-viswanathan's logs. However, unlike etcd, we don't currently persist Elasticsearch data on localhost, and we don't expose an export/import facility for sharing logs for analysis.

`etcd` is too vital of a service to be failing so investigating this further is important.

**Comment by ndegory** [comment]
we'd need the docker inspect results from @neha-viswanathan or @JosephGJ to see why the healthchecks are failing. I'm guessing it's again the dreaded slowness of Docker for Mac that makes it fail, because it works flawlessly on Linux.

**Comment by ndegory** [comment]
What I see on Docker 1.12.3/Ubuntu, only one container and healthcheck taking ~0.3 sec:

```
~/src/github.com/appcelerator/amp(master ✔) docker service ps etcd
ID                         NAME    IMAGE                         NODE                    DESIRED STATE  CURRENT STATE           ERROR
7kkjxa9zeh0uey9q9w2fm1047  etcd.1  appcelerator/etcd:3.1.0-rc.0  nicolas-Latitude-E7240  Running        Running 27 minutes ago
~/src/github.com/appcelerator/amp(master ✔) docker inspect etcd.1.7kkjxa9zeh0uey9q9w2fm1047 | jq '.[0].State.Health'
{
  "Status": "healthy",
  "FailingStreak": 0,
  "Log": [
    {
      "Start": "2016-11-08T11:55:30.870363342+01:00",
      "End": "2016-11-08T11:55:31.207881984+01:00",
      "ExitCode": 0,
      "Output": ""
    },
    {
      "Start": "2016-11-08T11:55:36.208199972+01:00",
      "End": "2016-11-08T11:55:36.544326038+01:00",
      "ExitCode": 0,
      "Output": ""
    },
    {
      "Start": "2016-11-08T11:55:41.544411905+01:00",
      "End": "2016-11-08T11:55:41.870655049+01:00",
      "ExitCode": 0,
      "Output": ""
    },
    {
      "Start": "2016-11-08T11:55:46.870811337+01:00",
      "End": "2016-11-08T11:55:47.207781273+01:00",
      "ExitCode": 0,
      "Output": ""
    },
    {
      "Start": "2016-11-08T11:55:52.207875935+01:00",
      "End": "2016-11-08T11:55:52.540897601+01:00",
      "ExitCode": 0,
      "Output": ""
    }
  ]
}
```

**Comment by ndegory** [comment]
I've made a test on my Mac mini (Docker 1.12.1), I noticed that the healthcheck were executed in ~0.6 sec, and had one failure at more that 1 sec.
