### ISSUE TITLE
Move integration tests

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#434]
Our integrations tests also serve as examples for stack files -- and often get demonstrated as part of presentations and training. To some degree, the yaml-driven, CLI-based integration tests and forthcoming yaml-driven API tests will also be instructional as well. To make them easier to discover and to use in documentation and demos, let's move them under a top level `test` directory, similar to `examples`. Unit tests should remain where they are.

Proposal:

    test/
        + api/
        + cli/

Or something similar...

**Comment by hadrien-gantzer** [comment]
Please Checkout [branch 434](https://github.com/appcelerator/amp/tree/issue-434)

Moved cli & rpc tests to a `/tests` folder
Modified `Makefile` **test** section accordingly leveraging explicit definition of what is being tested

```
test:
    @go test -v ./tests/rpc
    @go test -v ./tests/cli

    $(foreach pkg,$(TEST_PACKAGES),\
    go test -v $(pkg);)
```

Cli tests & old TEST_PACKAGES loop are commented for the moment:
- Cli are not passing: investigating
- TEST_PACKAGES: to be refactored
