### ISSUE TITLE
Release binaries should be stored in S3

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#435]
Use appcelerator.io AWS account.

**Comment by subfuzion** [comment]
@ndegory See Docker for example:

https://github.com/docker/docker/releases

> deb/rpm install: curl -fsSL https://get.docker.com/ | sh
> Linux 64bit tgz: https://get.docker.com/builds/Linux/x86_64/docker-1.12.3.tgz
> Darwin/OSX 64bit client tgz: https://get.docker.com/builds/Darwin/x86_64/docker-1.12.3.tgz
> Linux 64bit arm tgz: https://get.docker.com/builds/Linux/armel/docker-1.12.3.tgz
> Windows 64bit zip: https://get.docker.com/builds/Windows/x86_64/docker-1.12.3.zip
> Windows 32bit client zip: https://get.docker.com/builds/Windows/i386/docker-1.12.3.zip

You can use the Appcelerator AWS account to set up Route 53 DNS for https://get.appcelerator.io/builds/{PLATFORM}/{ARCHITECTURE}-X.Y.Z.tgz|zip

We only need to worry about 64-bit Linux, Darwin, and Windows builds for `amp` and `amplifier` for now.

**Comment by ndegory** [comment]
- [x] Archives are built for v0.3.0 and uploaded on S3
- [x] Cloudfront is configured to delivery the content of the S3 bucket
- [x] [Release page](https://github.com/appcelerator/amp/releases/tag/v0.3.0) is updated
- [ ] ~~Certificate is configured~~

**Comment by ndegory** [comment]
Release page updated with http instead of https (no valid certificate).
