### ISSUE TITLE
amp swarm command

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#437]
Create an `amp swarm` command for local swarm development. The implementation for now will be temporary: the command should start the services in order, or in parallel for services that have no dependencies or else have common dependencies; no service should start until its upstream dependencies are healthy; the entire command should block until the swarm is running and healthy, or it should fail if any service fails to become healthy as specified by its healthchecks. The command should update the terminal to keep the user informed as it progresses.

**Comment by freignat91** [comment]
Concidering Docker will release soon its own version of stack implementation, i propose to do not use amp stack package for that, but just the service package and as suggested above create a command with as few as dependencies with amp.

**Comment by subfuzion** [comment]
Yes, I agree ("The implementation for now will be temporary"). For the time being, the implementation should just use the AMP service API, based on the remote Docker API.

**Comment by generalhenry** [comment]
It strikes me that these aren't top level commands.

imo they should either be
`amp platform start/stop/etc. . .`
or
`amplifier start/stop/etc. . .`
