### ISSUE TITLE
AMP binaries should include the swarm script

### ISSUE THREAD

**Issue by avianey** [appcelerator-archive/amp#459]
**Description**

Following the doc I successfully get the binaries from https://github.com/appcelerator/amp/blob/master/docs/installation/binaries.md but can't perform first step from https://github.com/appcelerator/amp/tree/master/docs.

**Steps to reproduce the issue:**
1. install from binaries
2. try to get started

**Describe the results you received:**
Can't use getting started guide since there's no swarm in 0.3.0 binaries
https://get.amp.appcelerator.io/builds/Linux/x86_64/amp-v0.3.0.tgz

**Describe the results you expected:**
I can start AMP from the binary distrib https://github.com/appcelerator/amp/tree/master/docs#starting-amp

**Comment by generalhenry** [comment]
related: https://github.com/appcelerator/amp/issues/437
