### ISSUE TITLE
Deleting volume permanently fail after non-graceful shutdown

### ISSUE THREAD

**Issue by avianey** [appcelerator-archive/amp#467]
**Description**

When hosting AMP services inside a VM and shutting down the VM, then required volume cannot be deleted/recreated and the VM needs to be destroy/recreated

**Steps to reproduce the issue:**
1. start AMP using engage-amp (branch simple-vm-setup) see procedure in /vagrant
2. shutdown the VM using virtualbox or vagrant halt
3. restart the VM and try to `./swarm start`

**Describe the results you received:**

```
./swarm start
[...]
deleting volume amp-etcd ...........failed, ignore
Error response from daemon: Unable to remove volume, volume still in use: remove amp-etcd: volume is in use - [49a3cd983cfeb26bb0d913709ce5120f550939e3f155af2f95e46ebb89a7b33f]
```
```
docker volume rm amp-etcd
Error response from daemon: Unable to remove volume, volume still in use: remove amp-etcd: volume is in use - [49a3cd983cfeb26bb0d913709ce5120f550939e3f155af2f95e46ebb89a7b33f]
```
```
docker ps       
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

**Describe the results you expected:**
Either :
* ./swarm start listen for shutdown to try to perform graceful ./swarm stop
* ./swarm start manage non graceful shutdown

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
in the VM
```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   34a2ead
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   34a2ead
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `amp version`:**

```
amp (cli version: v0.3.0, build: 9a052066)
Server: 127.0.0.1:8080
```

**Additional environment details (AWS, etc., if applicable):**
VirtualBox VM

**Comment by ndegory** [comment]
@avianey , you should add a script that will properly stop AMP at shutdown.
For instance on a system with systemd, something like this:

```
[Unit]
Description=AMP Cleanup
DefaultDependencies=no
Before=shutdown.target reboot.target halt.target

[Service]
ExecStart=/go/src/github.com/appcelerator/swarm stop
Type=oneshot
```

What happens in your case is that the services are killed at shutdown, but Docker does probably not have the time to clean up everything, the system is halted before that. You can consider it as a Docker bug, but that's debatable. So you still have stopped containers, you can check with `docker ps -a`. Then the volumes can't be deleted.
Another thing you can do (at system start or stop, or maybe both), is to make that cleanup yourself. A script like the following will help:

```
echo "cleanup containers..."
for c in $(docker ps -a | egrep -e "(Exited|Created)" | awk '{print $1}'); do docker rm $c; done
echo "done"
echo "cleanup volumes..."
for v in $(docker volume ls -q -f "dangling=true"); do docker volume rm $v ; done
echo "done"
echo "cleanup images..."
for image in $(docker images -qa --filter "dangling=true") ; do docker rmi $image ; done
echo "done"
```

**Comment by avianey** [comment]
will try this thx

**Comment by ndegory** [comment]
Closing this issue for now, if you need any further information please reopen.

**Comment by avianey** [comment]
for the record, this is working :
```
    - name: amp.service
      command: start
      content: |
        [Unit]
        Description=AMP
        After=docker.service

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/home/core/swarm start
        ExecStop=/home/core/swarm stop
    - name: amp-cleanup.service
      content: |
        [Unit]
        Description=AMP cleanup
        DefaultDependencies=no
        Before=shutdown.target reboot.target halt.target

        [Service]
        Type=oneshot
        ExecStart=/home/core/swarm stop
```
