### ISSUE TITLE
make build / install are failing

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#468]
`make build` / `install` are currently failing after pulling latest source and images.

```
$ make build
[run -u 20:20 --rm --name protoc -t -v /Users/tony/projects/go/src/github.com/appcelerator/amp:/go/src/github.com/appcelerator/amp -v /var/run/docker.sock:/var/run/docker.sock appcelerator/protoc --go_out=Mgoogle/api/annotations.proto=github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api,plugins=grpc:/go/src/ --grpc-gateway_out=logtostderr=true:/go/src --swagger_out=logtostderr=true:/go/src/ -I /go/src/ -I /go/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis /go/src/github.com/appcelerator/amp/api/rpc/build/build.proto]
/go/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis: warning: directory does not exist.
protoc-gen-grpc-gateway: program not found or is not executable
--grpc-gateway_out: protoc-gen-grpc-gateway: Plugin failed with status code 1.

panic: exit status 1

goroutine 1 [running]:
panic(0xd3720, 0xc420110540)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
main.main()
```

**Comment by subfuzion** [comment]
@generalhenry @bquenin @chrisccoy Looks like #452 is the cause. Can't build after this commit.

**Comment by generalhenry** [comment]
The updated protoc image is needed, `docker pull appcelerator/protoc`

**Comment by subfuzion** [comment]
@generalhenry Yes, I actually just figured it out on my own. This should have been announced.

**Comment by subfuzion** [comment]
Unfortunately, GitHub has been experiencing an outage for most of the past half hour: https://twitter.com/githubstatus/status/798901132810719232

**Comment by ndegory** [comment]
We'd probably tag the protoc image and not use `latest` in the amp build, that would secure all the other branches when we do new developments.

**Comment by bquenin** [comment]
I experienced the same issue. We should definitely use version on `appcelerator/protoc` image to make sure everything's ok.

**Comment by subfuzion** [comment]
Yes, that would definitely help.

**Comment by ndegory** [comment]
ok, I'll take care about it if that's fine for everybody.

**Comment by subfuzion** [comment]
Resolved by ensuring the latest image is pulled:

```
docker pull appcelerator/protoc
```
