### ISSUE TITLE
Influx test fails on OS X

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#48]
Running the influx test on OS X (Docker for Mac) fails with the following output:

```
$ make test-influx
=== RUN   TestQuery
--- FAIL: TestQuery (0.01s)
        influx_test.go:23: unable to decode json: received status code 405 err: invalid character 'M' looking for beginning of value
FAIL
```

The test failed on my Mac and on freshly installed Mac. However, it passes on Linux and it passes on the CI build.

[This issue](https://github.com/influxdata/influxdb/issues/6540) indicates that the problem is a mismatch between the client and the server versions. However, I made sure to pull the latest appcelerator/influxdb image on my Mac as well as the test Mac. I also ensured that the client package dependency was [explicitly tagged](https://github.com/appcelerator/amp/pull/47/commits/40d1de1c6b56c8f9c4557e2926d1416202faa280#diff-395f41b2a27b70ce44399c91c82158c2R28) for `0.13` in glide. I furthermore experimented by creating an updated image on my machine for `v1.0.0-beta3` and updated the client package for the same tag with glide. I still get the same error and `make test-stat` also fails for the same reason. It's critical that we resolve this issue quickly and ensure that we maintain parity between Linux, Docker for Mac and Docker for Windows.

[This PR](https://github.com/appcelerator/amp/pull/47) explicitly sets the version tag for the client dependency to match the server version use by [influxdb image](https://github.com/appcelerator/docker-influxdb/blob/master/Dockerfile#L4).

**Comment by subfuzion** [comment]
I reported the issue at the InfluxDB repo: https://github.com/influxdata/influxdb/issues/7184

**Comment by ndegory** [comment]
Great, now I can ask IT to provide me  with a macbook :)

**Comment by subfuzion** [comment]
Yes! You should definitely have one. So I also posted to the [influxdb slack channel](https://gophers.slack.com/archives/influxdb/p1471682768001183) ... hopefully someone there can offer some insight also.

**Comment by subfuzion** [comment]
Resolved. It was coincidental that the issue manifested  on two machines that happened to be running Docker for Mac. There was in fact a version mismatch between the client and the server depending on whether or not the client package was in sync with the repo's server image. We should not pull `latest` from the swarm script, but pull explicitly tagged versions instead so that any mismatch is a bit more conspicuous.

**Comment by ndegory** [comment]
@subfuzion I think we should do the same with the TICK images, instead of latest we should use the name of the branch. Right now we have influxdb-0.13 and influxdb-1.0, telegraf-0.13 and telegraf-1.0, kapacitor-0.13 and kapacitor-1.0.
