### ISSUE TITLE
[UX enhancements] AMP commands - blocking functionality

### ISSUE THREAD

**Issue by JosephGJ** [appcelerator-archive/amp#480]
Issue has arisen due to CLI tests running to fast.There is no blocking option for commands. It should force the command to wait until some condition has been met. Used when users want to write scripts using AMP commands.
e.g.
```
amp service create appcelerator/pinger --name pinger -p www:90:3000`
curl localhost:90/ping
```

Given how fast the service is created, `curl` will return 
```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 56518: Connection refused
                 : Error: exit status 7
```

When it should usually return. 
```
[f8dba4565d1d] pong
```

**Comment by bquenin** [comment]
@JosephGJ `amp` commands are asynchronous (like `docker`). I would advise to add some step in your test to get the status of the service (`docker service ps` or `docker servie ls`) and then curl it. I'm not sure we want to make amp synchronous.

**Comment by freignat91** [comment]
why not to add an option (--sync) to have amp commands synchrous, keeping them asynchrous by default?

**Comment by JosephGJ** [comment]
I've been working on adding the `--sync` option to the `service create` command. For the moment, if the flag is specified, it will block the create command from finishing execution if it the number of tasks is not equal to the number of replicas. However, after working on it for a bit, the scope is somewhat broader than I had originally seen, as there are other things that may be necessary to wait on depending on the options of the `service create` command e.g. `--publish` needs to wait on the server to be running or the `--mode` cannot check for replicas as it is set to global. 

Tony had originally suggested the idea of an "api Call" to wait on (#374), which I can work on for cli tests for now, however, as the tests become larger and have more converge, this `--sync` command could be something that could be worked on in the future.

**Comment by JosephGJ** [comment]
Closing as `amp service create` is no longer a command and blocking functionality for `amp stack deploy` has been covered in #1228
