### ISSUE TITLE
Travis doesn't pusblish docker image on master branch anymore

### ISSUE THREAD

**Issue by bquenin** [appcelerator-archive/amp#484]

**Comment by ndegory** [comment]
when do you the build to be pushed?
It should be the case only when a pull request is merged on master.

**Comment by ndegory** [comment]
If you look at the output of #485 build ( which triggers a push, and should not), you see that the issue is because of another change:

```
The command "make test" exited with 0.
after_success
0.00s
$ if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && timeout 120 ./shrink.sh latest && timeout 30 docker push appcelerator/amp:latest fi
/home/travis/build.sh: eval: line 58: syntax error: unexpected end of file

```
the travis script is interpreted without the linefeeds, which makes it fail

**Comment by bquenin** [comment]
The proposed fix doesn't solve the issue. The latest image is still not published to docker hub (https://hub.docker.com/r/appcelerator/amp/tags/)
