### ISSUE TITLE
Travis tests previous amplifier

### ISSUE THREAD

**Issue by generalhenry** [appcelerator-archive/amp#489]
Currently my build is failing on travis: https://travis-ci.org/appcelerator/amp/builds/178074710

This is due to a initialization bug introduced by https://github.com/appcelerator/amp/pull/479

I'm working on a fix to the initialization bug, but the issue will still remain that `amp pf pull && amp pf start` pulls and starts amplifier from docker hub.

**Comment by generalhenry** [comment]
@bquenin I fixed the init bug and hot pushed to docker hub to work around the prev build issue.  I see your work in https://github.com/appcelerator/amp/tree/amp-tests-fix which looks like you're making headway.

My current thinking is:
`./shrink local`
`amp platform pull --local`
`amp platform start --local`
Which would build the amp image locally, skip pulling amp and then launch services with the local amp image.

**Comment by bquenin** [comment]
You're right, I was working on a fix, but yours is better.
I'll submit a pull request with a doc for local test development.
