### ISSUE TITLE
Engage - Being able to see pulling status of stack images from cli

### ISSUE THREAD

**Issue by avianey** [appcelerator-archive/amp#502]
**Description**

Without access to the swarm cluster running amp services, it's impossible to check for pulling statuses of images after a remote `amp stack up`

**Steps to reproduce the issue:**
1. have the cli on one host
2. swarm services deployed elsewhere
3. create a stack from the cli (containing images that cannot be pulled from the cluster for exemple)
4. see simple-vm-setup branch of enagage-amp project (two minutes two reproduce...)

**Describe the results you received:**

```
$ amp stack up -f test-engage.yml engage
b7440414be2a1b2213d8ea76507cbf67717a73b477bb741558698586370f7b10
```
... waiting for something available
nothing weired using amp logs

**Describe the results you expected:**

distinguish pull status / have log for :
* a way to check if some 10GB images are still being pulled
* a way to check that pulling of some images fail permanently

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   34a2ead
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   34a2ead
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `amp version`:**

release 0.3.0

**Additional environment details (AWS, etc., if applicable):**

see branches

**Comment by generalhenry** [comment]
The docker solution to this in a service context is `docker service ps [service_ident]`

Which produces results like:
```
bash-3.2$ docker service ps private
ID                         NAME           IMAGE             NODE  DESIRED STATE  CURRENT STATE            ERROR
7jfl9iiabqfjkyf26315n9xr4  private.1      htilford/private  moby  Ready          Preparing 1 seconds ago
4o6s7r2fp23fsev6njly1t5vv   \_ private.1  htilford/private  moby  Shutdown       Rejected 1 seconds ago   "No such image: htilford/priva…"
```
Which gives some diagnostic about the status and why your service isn't working

So for `amp stack` a `amp stack ps [stack_ident]` could be made that would list an analogous diagnostic.

**Comment by freignat91** [comment]
amp command have been developed at the beginning only for localhost usage. It was one of the requirement so they don't implement any remote action capabilities.
Next step is to implement remote capabilities (#512), but it needs more than just to change the cli part. we have to include a more global architecture thiking. 
First answer is on the #519, but it's not the last on this important topic.

**Comment by bquenin** [comment]
Obsolete as amp doesn't manage stacks anymore
