### ISSUE TITLE
Simplify Install Instructions

### ISSUE THREAD

**Issue by chrisccoy** [appcelerator-archive/amp#505]
Is there a reason for the manual installation steps in the following [docs](https://github.com/appcelerator/amp/blob/master/docs/installation/cloud/cloud-ex-aws.md) for installing docker? I am thinking It might be better and easier to simply perform:
`curl -sSL https://get.docker.com/ | sh`
or for experimental:
`curl -fsSL https://experimental.docker.com/ | sh`

**Comment by generalhenry** [comment]
I don't think we need to add the experimental url, we don't use the experimental features, and as of docker 1.13 they're being moving into the main install under an experimental flag.

**Comment by bquenin** [comment]
Fixed by #507
