### ISSUE TITLE
Add --with-registry-auth flag

### ISSUE THREAD

**Issue by generalhenry** [appcelerator-archive/amp#506]
ref: https://github.com/appcelerator/amp/issues/503

Add a `--with-registry-auth flag` to `amp service create`, `amp stack create` and `amp stack up`

Follow the behavior of `docker service create` see https://github.com/docker/docker/blob/ce0068ed0483bd87dc4af1e7388d9b9a91431424/cli/command/service/create.go#L78

**Comment by generalhenry** [comment]
Working in branch: https://github.com/appcelerator/amp/tree/with-registry-auth
So far I've gotten `amp service create` working

To test:
`make install`
`./shrink.sh local`
`amp pf pull --local`
`amp pf start --local`
`amp service create --name test --with-registry-auth [private image]`
Should result in the private image running

**Comment by generalhenry** [comment]
Making progress on the stack, however it's proving more difficult since each image might be from a different registry which means the stackfile will need to be parsed on the client side.

**Comment by generalhenry** [comment]
I've gotten stacks working

To test:
`make install`
`./shrink.sh local`
`amp pf pull --local`
`amp pf start --local`
`amp stack up -f [path to stackfile that includes private image(s)] --with-registry-auth [stack name]`

However I need to do some clean up before it can be merged.

**Comment by chrisccoy** [comment]
@generalhenry 
I tried the start command as prescribed above and received the following results:
```
amp pf start --local
Starting AMP platform
Service nats is ready
Service registry is ready
Service amp-ui is ready
Service influxdb is ready
Service elasticsearch is ready
Start error: Service amp-agent image appcelerator/amp:local doesn't exist
```
Perhaps the platform pull is not including the amp image? 
```
amp pf pull --local
Pulling AMP images
image appcelerator/kapacitor-amp:1.1.2 pulled
image appcelerator/telegraf:telegraf-1.1.1 pulled
image appcelerator/amp-ui:0.2.0 pulled
image appcelerator/elasticsearch-amp:2.3.5 pulled
image appcelerator/grafana-amp:1.0.1 pulled
image appcelerator/haproxy:1.0.2 pulled
image appcelerator/influxdb-amp:1.1.2 pulled
image registry:2.5.1 pulled
image appcelerator/etcd:3.1.0-rc.1 pulled
image appcelerator/pinger:latest pulled
image appcelerator/amp-nats-streaming:0.3.0 pulled
AMP platform images pulled
```

**Comment by generalhenry** [comment]
@chrisccoy  try a `amp pf start -f --local`

**Comment by ndegory** [comment]
@chrisccoy I think it's because for now the ```amp pf pull``` command is only pulling on your local node, and we need to pull on all nodes of your Swarm cluster. This is an annoyance for now, you have to pull manually on each node.
@freignat91 is working on it through the amp agent, so that's a feature we should have soon.

By the way, the ```local``` build is only relevant on single node clusters, this tag is not supposed to be pulled.

**Comment by chrisccoy** [comment]
@ndegory @generalhenry I am actually running this, at the moment, as a single node. Sorry, I did not read clearly the explanation of the issue surrounding the --with-registry-auth option. I will enable the swarm mode and retest.
