### ISSUE TITLE
Cluster management

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#512]
be able to manage amp swarm cluster remotely:
- execute amp platform commands remotely (start, stop, status, monitor, pull images on all nodes)
- get nodes,images information
- purges nodes (containers, volujmes, images
- attach, detach a swarm node

This is related to #306, it comes just after swarm bootstrap installation.

**Comment by generalhenry** [comment]
Some thoughts on the cli:
`amp platform [command] --node [node_ident]`
`amp node ls`
`amp node images [node_ident]`
`amp node purge [node_ident]`
`amp swarm join [manager_addr]`
`amp node rm [node_ident]`
