### ISSUE TITLE
Serverless prototype

### ISSUE THREAD

**Issue by bquenin** [appcelerator-archive/amp#521]
The goal of this prototype is to implement a first version of serverless feature into amp. The proposal is to have a Faas (Function as a Service) built into AMP.

# Story
As a user, I want to trigger a function, i.e. a container when I receive an HTTP POST on a given route. 

# Scenario
In order to achieve this story, we need 2 elements:
1. A container which will execute the function
2. Register this container as a function in amp

## The function
In order to keep a maximum of flexibility on the technology used for functions, standard streams are used to pass function input and output parameters:
 - `stdin` : where the function gets its input parameter
 - `stdout`: where the function can produce a result
 - `stderr`: where the function logs

For instance, a function can be written like this:
```
package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"strings"
)

func main() {
	input, err := ioutil.ReadAll(os.Stdin)
	if err != nil {
		log.Fatal("Unable to read standard input", err)
	}
	log.Println("input", string(input))       // Logs on standard error
	fmt.Println(strings.Title(string(input))) // Writes response on standard output
}
```
This source code of the function is available here: [amp-demo-function](https://github.com/appcelerator/amp/tree/serverless-proto/examples/functions/demo-function)

Since functions are containers, the function developer needs to wrap his function inside a container. Let's consider the above snippet has been containerized in an image called `amp-demo-function`

## Registering the function
In order to register a function against amp, the user would need to do the following command:

    $ amp function create -i image-name function-name
    <function-id>

## Invoking a function via HTTP
In order to invoke a function, you can POST an HTTP request to `function.local.axwaytest.net/<function-id>`. The body will be transferred to the function on its standard input.
The call is blocking until the function sends a response.

    $ cat Makefile | curl function.local.axwaytest.net/[function-id] --data-binary @-

# Architecture
![Serverless prototype architecture](https://raw.githubusercontent.com/appcelerator/amp/serverless-proto/serverless-proto.png)
The idea is to have 2 new amp binaries:
 - `amp-function-listener`
 - `amp-function-worker`

## `amp-function-listener`
This service role is to:
- listen to HTTP events and send function request to NATS
- listen to NATS for function responses

## `amp-function-worker`
This service role is to:
 - listen to NATS events,
 - spawn container
 - pass the content of the message through standard input
 - get the response as standard output (if any)
 - post the response back to NATS

## `amplifier`
The `function` API is served by `amplifier` and function information are stored in etcd.
We need to be able to add, list and remove `function`s dynamically.

## `amp` CLI
`amp` CLI needs to be updated to support `function`s commands.
We need to be able to:
 - create a function
 - list functions
 - remove a function

# Observations
 - Maybe we should not use NATS-streaming but NATS directly (without storage) since I'm not sure we will replay function calls.
 - We can have a better NATS usage if we know beforehand whether or not the function produces a return value (fire and forget)

**Comment by chrisccoy** [comment]
This is well described @bquenin and makes sense to me and I think is a good place to start. I realize this is just in prototype phase and not sure what outcome we are expecting, but the topic of serverless computing immediately brings the following concerns to the forefront, in my mind:

- How to handle response data (correlation id? callbacks? synchronous capability?)

- Implementation of Claim Check [pattern](http://www.enterpriseintegrationpatterns.com/patterns/messaging/StoreInLibrary.html)

- Retries and Dead Letter Strategy

- Should we create a cannonical message format?

- Should we create a comprehensive catalog of all messages, their functions and rules?

- Monitoring performance and backlog

I guess the question boils down to: how much onus do we place on AMP to solve these concerns versus bring your own?

**Comment by bquenin** [comment]
@chrisccoy Thanks for your feedback Chris. I don't have all the answers and this prototype is definitely here to start discussions like this! Here is where I stand today:
 * Handling response data should be done via the natural symmetric of standard input, i.e. standard output. It may conflict with logs but we could standardize to use standard error for logs for instance.
 * Implementation of Claim Check pattern: I'm not sure I understand this pattern to its full extent, but all messages are stored in NATS making them available for reprocessing if necessary. Please correct me if I missed the point :)
 * Retries and DLS: Again, message are stored in NATS so we can make sure the worker acknowledge messages only when it gets a response (if required). In case of a failure, another worker is able to take over.
 * Canonical message format: Yes, I think we should provide a structure for the input message and output messages. The structure of this message should be simple and probably mimic an HTTP request and an HTTP response.
 * Catalog of messages: I'm not sure since our message format should be pretty generic. The detailed structure of messages is ultimately designed by the function developer.
 * Monitoring and performance: You're absolutely right. I'm not sure it's going to be covered by this prototype, but we definitely need to know the pressure on the NATS queue for instance in order to know if we need to scale the function workers.

I think function development in AMP should be code and forget, as in, AMP must be able to handle as much as possible in order to have the best developer experience.

**Comment by chrisccoy** [comment]
@bquenin, nice work on #539. I have been researching the serverless architecture provided by [ironio](https://github.com/iron-io/functions) and it seems very popular to be using [dind](https://hub.docker.com/_/docker/) _Docker In Docker_ 

This might be something we want to research as well. It requires running the FaaS container in privileged mode, but seems well suited for this use case.

**Comment by bquenin** [comment]
Hi @chrisccoy, I know about `dind` but I'm not sure we need to use it, we can use the actual docker daemon. What do you think are the pros/cons?

**Comment by chrisccoy** [comment]
Honestly, difficult to say. For starters, I like the encapsulation aspect of `dind`; spun up containers don't hang around on the main daemon. Also, it is easy to cleanup, by simply removing the FaaS container(s). 

However, I like the way you can attach to the socket and essentially "callback" to the main daemon, as the prototype does, but I think it warrants investigation, because it could be a bit messy.
