### ISSUE TITLE
registry --domain usage issue

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#540]
I didn't get why we have added a --domain argument to the amp registry cli command.
Why do'nt use the server address instead?
registry.[serveur address] is routed to registry by HAProxy
considering the server address shouldn't be an IP but a DNS, i don't see the need to use another information.
Note: we can use serverAddresss as IP format only for amplifier command as stats, logs, stack, ..., because amplifier doesn't use HTTP and have a dedicated port, but for all other services including user ones we need a DNS address to make HAProxy able to route it. So we could forbid IP address format in the configuration or in the --server argument, to have only DNS and then use it for registry. It seems more consistent.

**Comment by ndegory** [comment]
that would nice to merge the two options, for now we have these two options because of what you described (serverAddr can be an IP) and because serverAddr contains also a port, which is not the one for the registry service.
