### ISSUE TITLE
Grafana Swarm Issue

### ISSUE THREAD

**Issue by chrisccoy** [appcelerator-archive/amp#55]
I was trying to view the Grafana dashboards, which I have not done in quite sometime, but encountered an issue.

```
INFO - Download configuration archive file https://github.com/appcelerator/amp-config/archive/0.1.0.tar.gz...
curl: (6) Couldn't resolve host 'github.com'
WARN - download failed, ignore
no datasource or dashboard json file, skip the configuration step
```

**Comment by ndegory** [comment]
@chrisccoy the configuration (datasources and dashboards) is downloaded from github, your container doesn't seem to have internet access, so it skips this phase.
If we want to cover this use case (no internet access) then we'll have to find another way to load dynamically the configuration.

**Comment by chrisccoy** [comment]
@ndegory . Ya, my bad, I have to sometimes manually switch my /etc/resolv.conf when I move from work and home. I think the lookup timed out silently. I changed my conf file and restarted swarm and the dashes are there.

**Comment by subfuzion** [comment]
@ndegory I'm concerned about this scenario and thinking maybe we should just make sure the configurations are added to the images instead of dynamically loaded. Do you have any other thoughts on how to mitigate the issue when there is a connectivity issue with GitHub?

**Comment by ndegory** [comment]
@subfuzion  The idea behind the downloadable dashboards and datasources is that it allows to have a generic image (can be public), and that we don't have to rebuild the grafana image (takes 20 min) each time we have a change on a dashboard.
The original idea was to have a config container running on each node and mount the config volume in the grafana (or other) containers. It worked with docker-compose, but with Swarm I don't think we can do it anymore.
Do you see other ways to do it?

**Comment by subfuzion** [comment]
@ndegory I understand, and it's definitely a good optimization. I just wonder if it still doesn't make sense to make sure we COPY a basic configuration to be on the safe side? But I guess this is going to be a rare situation not worth spinning our wheels too much on right now. This wasn't a case of GitHub being down (GitHub's CDN is pretty reliable). I'll go ahead and re-close. Thanks.
