### ISSUE TITLE
amp tools

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#551]
All of the `amp*` tools should work similarly with respect to displaying version information (they should at least support `-V|--version`), and any CLI tool generally should support the `version` command as well.

**Comment by bquenin** [comment]
@subfuzion Do you mean all the binaries included in the amp image or only `amp` and `amplifier` ?
Here are the binaries included in the amp image today:
 - `amp`
 - `amplifier`
 - `amp-agent`
 - `amp-log-worker`
 - `amplifier-gateway`
