### ISSUE TITLE
install / build rule proto dependency

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#555]
The dependency on the proto was removed from the Makefile and needs to be restored. As a consequence of its removal, after a cloning the repo or after running `make clean` it is necessary to now manually run `make proto` first or else `make build|install` will fail. The proto rule originally used all the *.pb files as dependencies so it only built `*.pb.go` as necessary; if that stopped working, it should be fixed, but proto should be a prerequisite for build and install.

**Comment by ndegory** [comment]
the removal of .pb.go files has been moved to a proto-clean rule, now make clean install does not trigger any error. Fixed in #530

**Comment by subfuzion** [comment]
This is not a better solution than what existed before. There actually isn't really much of a reason for using a Makefile if we don't take advantage of the fact that it can recognize when file dependencies have been updated and automatically run rules for us. This was one of the few reasons for using a Makefile in the first place; otherwise we could just supply shell script commands. If the rule wasn't working correctly, I'd rather investigate and fix it than remove it, if at all possible.
