### ISSUE TITLE
amp / amplifier config command should be useful

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#556]
Currently, `amp config` and `amplifier config` do not display the current configuration in a useful format.

**Comment by ndegory** [comment]
sorry @bquenin I just saw this issue, I did something on it in #592. If you already worked on it, I can revert that part.

**Comment by bquenin** [comment]
@ndegory no worries, I didn't start working on it yet, It's all yours :)

**Comment by ndegory** [comment]
lol 🙄

**Comment by subfuzion** [comment]
@ndegory Nice work with #592, thanks. Let's make sure *both* amp and amplifier provide the current config in a useful format, then we can close this issue.
