### ISSUE TITLE
Attachable Networks

### ISSUE THREAD

**Issue by generalhenry** [appcelerator-archive/amp#559]
The `amp-infra` and `amp-public` networks should be [attachable](https://github.com/docker/docker/pull/25962) so that we can improve our developer workflow from `amp pf stop && ./shink.sh local && amp pf start -l`

Alternate workflow:
`docker service rm amplifier` 
`docker run -it --rm --network amp-infra --network amp-public --network-alias amplifier -v path/to/local:go/src/github.com/appcelerator/amp appcelerator/ampifier-build bash`
with appcelerator/ampifier-build being:
``` dockerfile
FROM golang:alpine
RUN echo "@community http://nl.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
RUN apk --no-cache add bash alpine-sdk
```
and from there simply `make install && amplifier` for each change

**Comment by generalhenry** [comment]
I made some progress here, I got my container up and attached, with amplifier running correctly, however I haven't gotten haproxy or amp-gateway to route to it.

**Comment by freignat91** [comment]
Seems that attachable network has been added in docker v1.13.0-rc4:
concidering the release note:

**Networking**

Add --attachable network support to enable docker run to work in swarm-mode overlay network #25962
