### ISSUE TITLE
Add amplifier address to client config and amp client --address flag

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#56]
Need to make the server address configurable on the client. The CLI should have an option for providing the server's address (amplifier host:port), and this should be saved in the AMP configuration. The default should be `localhost:50101`). Commands (such as [this](https://github.com/appcelerator/amp/pull/51/files#diff-bcd02246209d4e0d544459f5037c25d0R33)) should use the AMP configuration to get the address, and `api/client/` like [this](https://github.com/appcelerator/amp/blob/53d453ba1f1e7337bcd47a44c68c5faeb33c5284/api/client/amp.go#L35) should be modified to use the configuration.

**Comment by freignat91** [comment]
Tested ok:
config file in $HOME/.amp.yaml
if item ServerAddress is defined in the config file, it is taken as default value for amp command
