### ISSUE TITLE
config files location

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#560]
`amp*` tools should place their config files under `$HOME/.config/amp` on linux/mac-based systems. The individual files do not need a leading `.` with this convention.

`amplifier`'s config should be renamed from `ampswarm.yaml` -> `amplifier.yaml` (named after the program).

    $HOME/
      .config/
            amp/
                amp.yaml
                amplifier.yaml

**Comment by ndegory** [comment]
should we also keep a failover to ~/.amp.yaml if there's no ~/.config/amp/amp.yaml file? That's what most programs do.

**Comment by subfuzion** [comment]
No, not necessary. Littering the top level of the home directory with dotfiles is a pretty archaic convention. We should ensure that if the config file doesn't exist that we create an empty one (also creating the path if that doesn't exist as well).

**Comment by subfuzion** [comment]
I googled and came across [this](http://unix.stackexchange.com/questions/24347/why-do-some-applications-use-config-appname-for-their-config-data-while-other?rq=1). 2 out 3 answers (and 98% of the upvotes) agree on using the XDG Standard.
