### ISSUE TITLE
Developer workflow improvements needed

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#562]
The development experience has gotten worse due to the following reasons:

* Removal of make rules for specific targets. Now, if a developer makes a change to the CLI and wants to rebuild, all the binaries are build, not just the CLI. Build targets, such as `make build-cli / make install-cli` need to be restored.

* Unable to run locally built `amplifier`. Testing updates to `amplifier` now require a full build and update to all the images (using the no-longer aptly-named `shrink.sh` script). This is a time-consuming operation. There are several ways to mitigate this, such as restoring a rule to only build `amplifier` and run it in a container and attach it to the stack overlay network (feasible now that we are using Docker 1.13; this requires making the appropriate networks attachable).

**Comment by generalhenry** [comment]
ref: https://github.com/appcelerator/amp/issues/559

**Comment by bquenin** [comment]
@subfuzion For the second item, about the local amplifier. What we could do as well is to add a flag like this:
`amp pf start --dev`

The `--dev` flag would expose the ports of the amp services (like before) making local development a breeze.

What do you think ?
