### ISSUE TITLE
amp kv command

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#564]
`amp kv` should allow inspection and updates of the key-value store (etcd). The following subcommands should be supported as minimum for now.

* put
* get
* del (alias rm)
* ls [--recursive]

See [etcdctl docs](https://github.com/coreos/etcd/tree/master/etcdctl) for guidance.

**Comment by generalhenry** [comment]
ref: https://github.com/appcelerator/amp/pull/511
