### ISSUE TITLE
Tool help standardization

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#565]
* All of our tools should display help in the same format as the CLI.
* All command and option help descriptions should start with an uppercase letter to look consistent. Linux tools are pretty inconsistent (even gnu programs, like gcc and yacc, aren't consistent). It's not that any one format is best, but we should at least strive for consistency among our own tools. If we end a description with a period, then all descriptions should end with a period (and vice versa).

**Comment by neha-viswanathan** [comment]
There is a difference in the usage message for certain commands. Need a consensus on deciding what should `Use` contain?
```
var StackCmd = &cobra.Command{
	Use:   "stack operations",
	Short: "Stack operations",
       ....
```
```
var ServiceCmd = &cobra.Command{
	Use:   "service",
	Short: "Manage services",
        ....
```

**Comment by ndegory** [comment]
@neha-viswanathan IMO and based on [the official doc](https://github.com/spf13/cobra),  _Use_ should be the binary/command name, _Short_ should be a few words description, and _Long_ can be a multiline description.
