### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#569]
Providing API documentation is quickly becoming a necessity for other teams looking to leverage AMP. We need to provide API (gRPC/protobuf) documentation and REST API docs, and we should consider hosting swagger docs as an amplifier service as well as making them available online.

**Comment by generalhenry** [comment]
ref: https://github.com/appcelerator/amp/issues/425

**Comment by bquenin** [comment]
I think that if we provide swagger files (through the `amplifier-gateway`), we're good to go. Do you think we need more than this ?
