### ISSUE TITLE
amp platform --start

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#570]
Currently the display provides no feedback as to which service is launching. It would be nice to feedback to display which service is being started, and then update the display to say the service is ready.

**Comment by freignat91** [comment]
these messages are visible with -v option. 
Do you want to always see them without -v ?

**Comment by subfuzion** [comment]
amp pf -v is meant to be very verbose -- more of a debugging aid. But I do think the default for the command should be slightly more verbose. There is a long gap between starting the command before feedback gets displayed.

As an aside, the verbose output is a bit misleading the way it is currently expressed:

![misleading](https://cloud.githubusercontent.com/assets/159738/21619138/3da9133a-d1a3-11e6-8c89-6dafaa30c785.png)
