### ISSUE TITLE
editorconfig

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#571]
Go provides standard formatting support, but it would be nice to have an [.editorconfig](http://editorconfig.org/) in the repo for the editors that support it so that formatting appears consistent for not just go, but also

    * yaml files (`.yaml|.yml`)
    * protobuf files (`*.pb`)
    * shell scripts (`*.sh`)

**Comment by ndegory** [comment]
@subfuzion and @generalhenry For go files should it be specified in the .editoconfig or handed down to the Golang formatting plugin that everybody should have on her editor? (I'd prefer the latter)
