### ISSUE TITLE
API Error Codes

### ISSUE THREAD

**Issue by generalhenry** [appcelerator-archive/amp#572]
Most API error currently return the default [grpc error code](https://godoc.org/google.golang.org/grpc/codes) 2 (unknown)

These can be fixed by returning [grpc errors](https://godoc.org/google.golang.org/grpc#Errorf)

Example: https://github.com/appcelerator/amp/blob/master/api/rpc/stack/stack.go#L85
should use `grpc.Errorf(codes.AlreadyExists, "Stack %s already exists", in.Stack.Name)`

**Comment by subfuzion** [comment]
Great tip.

**Comment by generalhenry** [comment]
That's all existing errors.
