### ISSUE TITLE
Standardize output format using tabwriter

### ISSUE THREAD

**Issue by neha-viswanathan** [appcelerator-archive/amp#591]
The outputs of different commands are formatted differently. Only some are using `tabwriter` package (like: `topic` and `kv`)

**Comment by freignat91** [comment]
done for new cluster cli commands, it stays stats and stacks to move on it,
For amp pf command (monitor), we can wait the cluster cli is validated

**Comment by freignat91** [comment]
waiting until #583 is merged to fix this issue

**Comment by subfuzion** [comment]
@freignat91 #583 was merged.
