### ISSUE TITLE
Travis build should run make fmt and check rules

### ISSUE THREAD

**Issue by bquenin** [appcelerator-archive/amp#633]
Enforcing this would avoid having spurious warnings in the build process.

**Comment by subfuzion** [comment]
@bquenin I disagree with this, especially in light of how long `make check` takes to run. These checks should be a part of our CI process, ensuring that they get automatically run for PRs. Once I run an install, I don't care that source code might not have been formatted properly, or even that some of the lint rules have failed.

**Comment by bquenin** [comment]
@subfuzion I agree, it lengthens the install process which is actually already taking time. I can move this to the travis.yml instead

**Comment by subfuzion** [comment]
@bquenin That would be great, thanks! 👍
