### ISSUE TITLE
amp check command

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#640]
It would be very useful to have some kind of smoke test command that can be run from the CLI to verify the environment, note any issues, and potentially offer to fix them. The main use case would be for developing and testing services on localhost.

Initial brainstorming example:

    $ amp check
    Checking local environment...
    [✔] Docker v1.13
    [✔] Host is a swarm manager
    [✔] appcelerator/etcd:3.1.0-rc.1
    . . .
    [❌] The following are out of date:
    - appcelerator/amp-nats-streaming:0.2.0 (should be appcelerator/amp-nats-streaming:0.3.0)
    - appcelerator/elasticsearch-amp:2.3.4 (should be appcelerator/elasticsearch-amp:2.3.5)
    Pull image(s)? [Yn]
    . . .
    [✔] 2 images successfully pulled
    [❌] AMP Platform is not running
    Start it? [Yn]
    (display normal start output)
    . . .
    [✔] AMP Platform v.5.0 is running

Subsequent check:

     Checking local environment...
    [✔] Docker v1.13
    [✔] Host is a swarm manager
    [✔] appcelerator/etcd:3.1.0-rc.1
    . . .
    [✔] AMP Platform v.5.0 is running

**Comment by subfuzion** [comment]
Continuing the brainstorming with @generalhenry ... current thoughts include:

`amp pf start --local` always runs the checks silently, only reporting errors, or showing everything if verbose (-v), offering to fix (or option to toggle)...

There are various `amp platform` options that can be used to accomplish something similar, but having a single command run a full suite of smoke tests, identifying issues and offering to help resolve in a friendly way might be useful.

Per Henry:  `amp pf env (check docker etc) && amp pf pull (check/fix images) && amp start` with amp start doing the first two unless flagged not to

**Comment by subfuzion** [comment]
The UI doesn't have to be nailed down quite yet, but internally what we want is a list of conditions that must be met associated with code for performing the checks and optional suggestions for attempting to fix.

**Comment by bquenin** [comment]
Now that we use Elasticsearch 5, we need to add its prerequisites:

    [✔] Max file descriptor: 131072 (expected: 65536)
    [✔] Max memory maps: 1048576 (expected: 262144)

**Comment by subfuzion** [comment]
This just now happened to me, illustrating how implementing this proposal will improve the developer experience:

```
$ amp pf start --local
Starting AMP platform
Start error: service elasticsearch image appcelerator/elasticsearch-amp:5.1.1 doesn't exist
Service etcd removed
Service amp-ui removed
```

I know that means I need to pull the updated image. We could make it so that if the image is missing it will get automatically pulled (the way the docker cli works when you execute `docker run`), or we can implement this via the `make check` proposal here, so that the user doesn't have to figure out he/she needs to run `amp pf pull --local`...

**Comment by chrisccoy** [comment]
:+1: 
I like the idea of pulling automatically if it is missing. If it is missing the only way to bring the service up would be to manually pull, anyway, so might as well just do it. Is there a downside that I am missing?

In addition, I think adding the dependency checks into the CLI makes sense. We could still have a make target for this, but having it part of the `amp pf start ---local` would improve the experience, in the scenario where a developers environment is not quite right.
