### ISSUE TITLE
Elasticsearch 5 prerequisite issue

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#649]
Last Elasticsearch 5 service, doesn't start on my machine because: (logs):
max file descriptors [10240] for elasticsearch process is too low, increase to at least [65536]

it should be added in prerequisite

**Comment by ndegory** [comment]
on Mac,

> $ ulimit -n
> 4864
> docker exec -ti bf7 /bin/bash -c ulimit -n  (elasticsearch)
> unlimited

so it's not related to the host. Can you check how it behaves on a Linux host?

**Comment by bquenin** [comment]
You' right, it seems it's not related to the host:
```
bq@u16  ~/go/src/github.com/appcelerator/amp   master  ulimit -n
1024
 bq@u16  ~/go/src/github.com/appcelerator/amp   master  docker exec -it e54bd8c02b27 /bin/bash -c "ulimit -n"
65536
```

**Comment by ndegory** [comment]
@freignat91 can you please show the result of these commands on your platform?

**Comment by freignat91** [comment]
Currently;
ulimit -n
-> 1024
and elasticsearch doesn't start so i can' execute: `docker exec -ti bf7 /bin/bash -c ulimit -n (elasticsearch)`
message in log:
```
ERROR: bootstrap checks failed
max file descriptors [10240] for elasticsearch process is too low, increase to at least [65536]
```
update ulimit to 70000, now i got
ulimit -n
-> 70000
and elasticsearch still not start, same error:
```
ERROR: bootstrap checks failed
max file descriptors [10240] for elasticsearch process is too low, increase to at least [65536]
```

**Comment by ndegory** [comment]
@freignat91 ,
I think it's because you have hard limits set on your system, which can be checked with `ulimit -Hn`.
You can update it in your /etc/security/limits.conf (you may also have a .d folder) with for instance:
```
*    hard     nofile         65535
root hard     nofile         65535
```

**Comment by freignat91** [comment]
in my  /etc/security/limits.conf file i have:
```
*    soft nofile 70000
*    hard nofile 70000
root soft nofile 70000
root hard nofile 70000
```

the command: ulimit -Hn
returns: 70000

**Comment by ndegory** [comment]
@freignat91 what about your Docker engine configuration?
You should check with `systemctl edit docker.service` if you have any override such as `LimitNOFILE`, or maybe directly in the docker service definition with `systemctl edit --full docker.service`.

**Comment by ndegory** [comment]
you may even try setting this LimitNofile to 65535 with systemctl edit, restarting the service and checking if it works this way.

**Comment by freignat91** [comment]
I found the issue, it works well now on my machine.
