### ISSUE TITLE
Automate node adding in amp cluster using ampadm

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#653]
in the amp version 0.5.x, manual operation have to be perform after having join a new node in the amp cluster.
Considering than when a node join amp cluster an adm-agent is automatically added and this one register into the adm-server, the adm-server know that a new node arrived and so is able to perform all operations using the agent to verify and prepare the n ode for amp (pull all images, ...)

**Comment by ndegory** [comment]
@freignat91 do we have only the docker pull (infra and user services) or do we already have other operations to automate?
