### ISSUE TITLE
> Missing: There is a 5 minute introductory video under docs.

### ISSUE THREAD

**Issue by alexellis** [appcelerator-archive/amp#655]
**Description**

Video is missing

**Steps to reproduce the issue:**
1. Land on homepage and read note "There is a 5 minute introductory video under docs."
2. Click blue link

**Describe the results you received:**

No video was present and searching the GitHub repo for "video" came up empty too

**Describe the results you expected:**

Video to be linked from initial landing-page to make it easier to surface.

Or - video to be present on linked page (somewhere high up)

**Comment by subfuzion** [comment]
You're right, we should fix the text. The video was moved to the [static_files](https://github.com/appcelerator/amp/tree/master/docs/static_files) directory under `docs`. However, it's also a bit old at this point. We'll have a set of new ones shortly and they'll actually be hosted  at a proper video channel.

**Comment by alexellis** [comment]
Would recommend commenting out or changing link in short-term for any visitors that find the repo from Google and the traffic around FaaS
