### ISSUE TITLE
'make install' takes too long time (more than 30 secs)

### ISSUE THREAD

**Issue by bquenin** [appcelerator-archive/amp#658]

**Comment by subfuzion** [comment]
I can't stand how long it takes either and started working on a fix yesterday as well. I should have created an issue for it. I'm killing two birds at once -- a faster build just for amplifier and the cli and having amp cli run in a container attached to amplifier's overlay network. I'm updating docker/gotools right now. The builder will bind mount the local files plus glide for a faster(er) build.

**Comment by bquenin** [comment]
Great minds come together :) I'll close my PR then!

**Comment by subfuzion** [comment]
Hehe, more like frustrated minds :p ... I don't know that you need to close your PR just yet. Let's chew on it together with @ndegory.

**Comment by subfuzion** [comment]
All I'm doing is adding an optimized build specifically for local development. I'm creating a single all-in-one go build tools image that includes everything we want for building, linting, generating protobuf files, etc, plus an optimizing the way we build/launch the cli during local development.

**Comment by subfuzion** [comment]
Oops, too late ... ok, i guess we'll potentially reopen your PR after discussion...

**Comment by ndegory** [comment]
I guess from what I read that we can gain from both PR. I'll review Bertrand's one, and I'll make another one to add to the frustration :)
