### ISSUE TITLE
AMP UI cluster issues

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#668]
When deploying an AMP cluster, many issues can be seen on AMP UI:
- unable to access services logs (Elasticsearch query error popup)
- two services named cluster-server and cluster-adm are listed in the infrastructure view, but do not exist

automation of deployment of AMP v0.5.0 can be done with https://github.com/appcelerator/amp-swarm-deploy/tree/0.5.0

**Comment by ndegory** [comment]
About logs in the UI, when the error popup opens, the dev console shows:
POST http://elasticsearch._mydomain_/amp-logs/_search 400 (Bad Request)

**Comment by freignat91** [comment]
I updated amp-ui 0.3.0, the adm-server and adm-agent not well named now.
it needs to re-pull appcelerator/amp-ui:0.3.0 image
Due to issue #649, i can't check the elasticsearch issue yet.

**Comment by ndegory** [comment]
For everybody's well-being, I'd prefer to keep amp-ui:0.3.0 as originally tagged, please tag a new 0.3.1 (or 0.4.0) as a fix. You now have an automated build on all tags.
Re-pulling should be only for `latest` images.

**Comment by freignat91** [comment]
The Amp-ui come from a breaking change introduce by EL 5 in query.
The amp-ui ES requests are not compatible with ES 5
they have to be migrated

**Comment by freignat91** [comment]
After discussion, considering amp-ui is a try for developers, we decided to not migrate it to ES 5 and to remove iit from amp.
The project appcelerator/amp-ui stay available as sample of UI integrated in amp using REACT and REACT-Bootstrap
