### ISSUE TITLE
Stack routing failures

### ISSUE THREAD

**Issue by generalhenry** [appcelerator-archive/amp#690]
expected:
  when you start a stack with a public route like "http://go.mycounter.localhost.tv/" it routes to your stack.

actual:
  the first time you start a stack things work.  However, subsequent stack starts frequently result in routing misses eg "no server found for stack=mycounter service=go" and previously correctly routing stacks sometime lose routing as well.

**Comment by subfuzion** [comment]
This issue can be replicated with most of the stack examples.

**Comment by freignat91** [comment]
I'm on it

**Comment by freignat91** [comment]
ok found it. I'm creating an appcelerator/haproxy:1.0.4 release for HAProxy and a PR for amp, both have to be fixed.
I'm performing full tests before creating PR.
