### ISSUE TITLE
Investigate telegraf worker connection with kafka

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#70]
Telegraf occasionally doesn't connect to kafka, which means logs aren't produced. telemetry-worker can say that it's up and healthy yet not have successfully connected to kafka. We probably need a healthcheck for our telegraf image that actually checks to see if it can connect to kafka, and if not, exit with an error so that telegraf is correctly reported as unhealthy. This will cause telegraf to be restarted according to the healthcheck retry policy.

**Comment by ndegory** [comment]
@subfuzion I wasn't able to reproduce this issue with swarm start --min, do you have a specific test to make it happen?

**Comment by subfuzion** [comment]
@ndegory It doesn't happen all the time, but it is frequent enough and everyone of us has experienced this. The only recourse for us is to restart the swarm. You can talk to @freignat91 about it; maybe he can try to reproduce for you in the Puteaux office.

**Comment by ndegory** [comment]
reproduced with latest version of zookeeper and kafka, issue is still there.

> 2016/08/26 16:53:40 Connected to 172.19.0.3:2181
> 2016/08/26 16:53:40 Authenticated: id=96484092623519747, timeout=4000
> 2016/08/26 16:53:40 Started the kafka consumer service, peers: [zookeeper:2181], topics: [telegraf]
> 2016/08/26 16:53:40 Kafka Consumer Error: kafka: error while consuming telegraf/-1: zk: node does not exist
> 2016/08/26 16:54:01 Output [file] buffer fullness: 0 / 1000 metrics. Total gathered metrics: 0. Total dropped metrics: 0.

**Comment by ndegory** [comment]
I'm now able to reproduce the issue in a repeatable way, and I'm trying to patch telegraf to make it fail when the kafka input is not properly initialized.

**Comment by ndegory** [comment]
Workaround now available in Docker hub (tag telegraf-0.13)

**Comment by subfuzion** [comment]
@ndegory Awesome, thanks for this. This is good for now, at least until we switch away from Kafka! ;)
