### ISSUE TITLE
Merge AMP images code in AMP repo

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#711]
AMP repo should include all the images we build specifically for AMP.

To be moved to images folder:
- [x] appcelerator/docker-influxdb-amp
- [x] appcelerator/docker-telegraf
- [x] appcelerator/docker-kapacitor-amp
- [x] appcelerator/docker-grafana-amp
- [ ] appcelerator/docker-haproxy
- [x] appcelerator/docker-elasticsearch-amp
- [x] appcelerator/docker-etcd
- [x] appcelerator/docker-amp-nats-streaming
- [x] appcelerator/docker-pinger

And new rules should be added to the Makefile to build these images and push them on Docker hub.

- [ ] Once moved, the original repos should have a warning in the readme pointing to the amp repo.

**Comment by subfuzion** [comment]
Perfect. Just remove the `docker-` prefix and `-amp` suffix for the subdirectories once you put it under `images`. Thanks!

**Comment by ndegory** [comment]
Extending the existing lifecycle of the amp image to the other ones would be cumbersome, so I propose two different lifecycles for AMP images:

| image | local development | master branch | other branch | any git tag | git tags = _imagename-suffix_ |
| ------ | ------------------ | --------------- | ------------- | ---------- | --------------------------------- |
| appcelerator/amp | local (Makefile) | latest (Travis) | N/A | _tag_ (manual) | N/A |
| others | N/A | latest | N/A | N/A | _suffix_ (Docker hub automated builds or manual) |

This would be easily implemented with the automated build in Docker hub, until a better CI is implemented.

**Comment by ndegory** [comment]
Automated builds have been disabled on the Docker hub repos of the images merged in the github amp repo.
