### ISSUE TITLE
Unable to build with `make`

### ISSUE THREAD

**Issue by alexellis** [appcelerator-archive/amp#718]
**Description**

Hi guys, I was unable to build the code on my Mac with `make` command after cloning and checking out master.

```
git clone https://github.com/appcelerator/amp
Cloning into 'amp'...
remote: Counting objects: 29944, done.
remote: Compressing objects: 100% (102/102), done.
ampeiving objects:   3% (1138/29944), 628.00 KiB | 580.00 KiB/s     
remote: Total 29944 (delta 70), reused 19 (delta 19), pack-reused 29822
Receiving objects: 100% (29944/29944), 105.54 MiB | 3.81 MiB/s, done.
Resolving deltas: 100% (13558/13558), done.
mini:appcelerator alex$ cd amp
mini:amp alex$ make
version: v0.6.0-dev (build: 95583605)
Unable to find image 'appcelerator/gotools2:1.2.0' locally
1.2.0: Pulling from appcelerator/gotools2
c952bb7239f0: Pull complete 
df674db1f5c5: Pull complete 
a97590af2dda: Pull complete 
2727f2714cc4: Pull complete 
56e4f3b398ed: Pull complete 
6d3c63919bcc: Pull complete 
7290b31bf5a4: Pull complete 
25e9742e8526: Pull complete 
b20bb53e8fa4: Pull complete 
e0deb870d58d: Pull complete 
0fd70c64be66: Pull complete 
Digest: sha256:6f0680acad89e0e447953893abba103eee69c86868eac7b8d3944e4470c3d4df
Status: Downloaded newer image for appcelerator/gotools2:1.2.0
hack/build: line 5: $1: unbound variable
make: *** [build-ampadm] Error 1
mini:amp alex$
```

Here's some debugging info:

```
mini:amp alex$ uname -a
Darwin mini.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64
mini:amp alex$ docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by subfuzion** [comment]
Hey @alexellis Thanks for the heads up. Apologies for any inconvenience, but we're addressing this in the following ways right now:
* rewriting our makefile from the ground up (see [here](https://github.com/appcelerator/amp/blob/master/Makefile.refactor.make))
* we are moving all required images into the project and aligning the versions for all dependencies (we just started, see [here](https://github.com/appcelerator/amp/tree/master/images))
* we are improving the toolchain and build processes (everything will be completely containerized and optimized for speedier builds and updates)
* we are reducing the footprint of amp core to just the minimum set of services required; the remaining will be sets of optional stacks for monitoring, etc
* we are focusing on docker 1.13, stacks, and v3 support so we're not necessarily focused on breakage with things that won't be supported going forward (although we will work to resolve this quickly).

There's more, but those are the highlights and we expect to have the improvements I just mentioned in place by Friday.

**Comment by ndegory** [comment]
regression introduced in PR #712

**Comment by subfuzion** [comment]
@alexellis At least In this case it was a nice easy fix, but the points I made above still apply. There will be a much better dev experience by the end of the week. Cheers!
