### ISSUE TITLE
Intermittent Build Failures 

### ISSUE THREAD

**Issue by chrisccoy** [appcelerator-archive/amp#720]
CI is failing occasionally. Appears to be due to environmental [cleanliness](https://travis-ci.org/appcelerator/amp/builds/194657782). 

Suggest we add a cleanup dependency to the pre or post CI processing to ensure the environment is in a good state to perform the builds.

**Comment by ndegory** [comment]
@chrisccoy regarding the build you referenced in the issue, I think it failed because the branch it was related to (gotools) was deleted before the completion of the build. Which is the case when a PR is accepted (and branch deleted) without waiting for the end of a Travis build.

**Comment by chrisccoy** [comment]
@ndegory Unfortunately the included link above is not the error I meant to show. The error that we have been seeing is related to etcd "watch" failures, which appears to fail on occasion. I will see if I can find an example to reference in the travis-build history.

**Comment by ndegory** [comment]
got it.
I see this failure from time to time on local tests, so it's not Travis related. The test is quite simple though, it shouldn't fail that often.
