### ISSUE TITLE
Improve cli tests

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#731]
It's take too much time to update cli tests through amp versions.
It's mainly due to the fact we don't get enough information when an issue occurs and we have for each to know which regex was used in the issue, understand it, compare with the real output and got how to fix, relaunch all tests to test the fix, and iterate this way until the good result. 
Some regex are not so simple and not completely right. Debug them take time, relaunch tests take time.
We take more time fixing/adapting the test itself than the code which should be tested.
To go faster, it should be good to :
- display which test is failing
- in case of error, display the executed command, the regex and the output which doesn't match.
 - if possible display exactly where the problem is in the output (for that, perhaps, use plain texts with variables without regex to describe the expected output and regex only internally to compare the output logical bloc by logical block using the plain text description. This intermediate description layer could allow to know on which logical block the issue occurred)
- be able to launch only one test or several specific tests to debug them quicker

**Comment by bquenin** [comment]
Addressed by #1159

**Comment by subfuzion** [comment]
I think you meant to reference this PR: https://github.com/appcelerator/amp/pull/1160

**Comment by bquenin** [comment]
yes thanks!
