### ISSUE TITLE
separare server address from port in amp config file

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#745]
Right now, we need to have:
```
serveraddress: 127.0.0.1:8080
adminserveraddress: 127.0.0.1:8081
```
in amp config file to make amp work, but the option --server in amp command update only the serveraddress
it seems better to have:
```
serveraddress: 127.0.0.1
serverPort: 8080
adminPort: 8081
```
this way, update server using --server we change the address for both server and adminserver.
`amp node ls --server xxx`, will work, right now it doesn't, it needs an up to date config.

By the way --server is not really the server address, but the haproxy or cloud provider LB one

**Comment by ndegory** [comment]
Good idea. There's already a Port key in the configuration file, I'm not sure if it is used, would be nice to remove it in the effort.
Btw, in my configuration the keys are PascalCased, not in lower case like in your description.

**Comment by freignat91** [comment]
Yes, it's another issue, when you update configuration using 'amp config' command, it's re-written all lowercase.
