### ISSUE TITLE
[Account] User management

### ISSUE THREAD

**Issue by bquenin** [appcelerator-archive/amp#765]
We need to have a working end to end implementation (CLI + backend) and associated tests of user management.

The scope we need to cover is:
 * SignUp
 * Verify
 * Login
 * Forgot Login
 * Password Reset
 * Password Change

There are also some related topics we need to address:
 * Sending emails
 * Managing secrets
 * Authentication (using JWT over gRPC between CLI and the backend)

**Comment by JosephGJ** [comment]
There was one other command. The forgot-login command allowed a user to retrieve their username if they had forgotten it using their email. It would send the username to their email address, similar to password reset.

**Comment by bquenin** [comment]
@JosephGJ Good catch! Thanks
