### ISSUE TITLE
InfraKit DigitalOcean deployment

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#770]
- bootstrap an instance with Swarm manager + Infrakit
- leverage the DO instance plugin to deploy the other nodes with Infrakit

**Comment by ndegory** [comment]
Waiting for the native Infrakit DO instance plugin

**Comment by diogomonica** [comment]
This one: https://github.com/docker/infrakit.digitalocean ?

**Comment by ndegory** [comment]
awesome, thank you for the reference @diogomonica !

**Comment by subfuzion** [comment]
Thanks, @diogomonica
