### ISSUE TITLE
Zookeeper and Kafka images include an Oracle JDK

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#78]
appcelerator/zookeeper and appcelerator/kafka images are based on https://hub.docker.com/r/anapsix/alpine-java/~/dockerfile/, which breaks the Oracle license terms.
see http://blog.takipi.com/running-java-on-docker-youre-breaking-the-law/ for details

**Comment by subfuzion** [comment]
@ndegory: thanks for pointing out the issue.

I was mulling over switching to [NATS](http://nats.io/) and @bertrand-quenin also mentioned it a few days ago on slack. This just adds another argument for eliminating anything jvm-based from our platform, and will probably make this a priority in the next sprint. I'm pretty sure as long as we agree to the license, build our own images, and host them ourselves, we haven't violated any agreement by containerizing; however, I don't feel like worrying about and dancing around Oracle's license, or switching to OpenJDK, or jumping through other hoops to avoid the mess with Java in any case. The heck with Oracle and Java. NATS is written in Go, and is available as [open source on GitHub](https://github.com/nats-io/gnatsd) with an [MIT license](https://raw.githubusercontent.com/nats-io/gnatsd/master/LICENSE).

**Comment by subfuzion** [comment]
@ndegory We will evaluate [NATS Streaming](http://nats.io/documentation/streaming/nats-streaming-intro/) as the alternative. I'm in favor and pretty comfortable with the idea of switching based on early looks, but we need to ensure we evaluate message durability using [file storage](https://github.com/nats-io/nats-streaming-server#user-content-file-store) and feel as comfortable with it as with kafka, which has been battle-tested and is well-documented. This evaluation is something I'd like to coordinate with you and @bertrand-quenin.

**Comment by ndegory** [comment]
@subfuzion The 2 (open) PR linked to this issue replace the Oracle JDK by an openJDK JRE.
So it's not a blocker anymore (once accepted), but if we can get rid of Java all together, I won't complain ;)

**Comment by subfuzion** [comment]
@bertrand-quenin Is already working on prototyping a switch to NATS. 👍

**Comment by subfuzion** [comment]
Since we're switching to NATS, this is no longer an issue for us.

**Comment by ndegory** [comment]
anyway, it's fixed (not in latest tags of the images, as the PR were not accepted), amp swarm already uses the new images.
