### ISSUE TITLE
Update Zookeeper to latest stable version (3.4.8)

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#79]
Current zookeeper image is version 3.4.6, there's been many issues fixed since this version: http://zookeeper.apache.org/doc/r3.4.8/releasenotes.html

**Comment by subfuzion** [comment]
@ndegory Same comment/recommendation as [here](https://github.com/appcelerator/amp/issues/86#issuecomment-243004513). Thanks.

**Comment by ndegory** [comment]
PR still open, so not yet a `latest` image.
But unit tests are OK, so I pushed a tag `3.4.8`
I'll push a tag `3.4.6` from before the change, but I'll leave the tag `latest` to the merge of the PR.

**Comment by subfuzion** [comment]
👍
