### ISSUE TITLE
etcd 3.1.4 fails to start in the amplifier stack 

### ISSUE THREAD

**Issue by bquenin** [appcelerator-archive/amp#825]

**Comment by ndegory** [comment]
Something changed in etcd between 3.1.0 and 3.1.4 (still in 3.1.5):
```etcdmain: --initial-cluster must include default=http://172.20.0.4:2380 given --initial-advertise-peer-urls=http://172.20.0.4:2380```
knowing that initial advertise peer url is set by default by etcd with a discovered IP, but not initial cluster.
