### ISSUE TITLE
AMP CLI wrapper displays passwords

### ISSUE THREAD

**Issue by bquenin** [appcelerator-archive/amp#827]
```
 bq@ubuntu  ~/go/src/github.com/appcelerator/amp   master ± amp user signup
username: bquenin
email: bquenin@axway.com
password: visible
```

**Comment by subfuzion** [comment]
This is an issue when running the CLI in a container since the current wrapper isn't attached to a TTY. Since we're releasing cross-compiled binaries of the CLI for our release now, this won't be relevant.
