### ISSUE TITLE
Telegraf net plugin not enabled

### ISSUE THREAD

**Issue by chrisccoy** [appcelerator-archive/amp#83]
I just reviewed the config for telegraf-agent and  noticed the the "net" plugin is not listed. I think we should add this to the list of measurements. The netstat plugin is enabled, but not net. 
Netstat does not provide a lot of information that is useful. For the demo, I am hoping to be able to stream back byte related I/O information, which is populated via the net plugin

**Comment by ndegory** [comment]
@chrisccoy , you mean the system wide net plugin (as opposed to the docker_container_net metric, already part of the unit tests on the telegraf image, already enabled)?

**Comment by chrisccoy** [comment]
yes,  that is correct.

**Comment by chrisccoy** [comment]
closing this for now.
