### ISSUE TITLE
terraform destroy error

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#858]
Attempted to destroy aws cluster after successfully creating it:

```
$ docker run -it -v $HOME/.aws:/root/.aws:ro -v $PWD/bootstrap/terraform-aws:/data --workdir=/data hashicorp/terraform destroy
. . .
aws_security_group.default: Still destroying... (ID: sg-745ead0f, 5m0s elapsed)
Error applying plan:

2 error(s) occurred:

* aws_subnet.default (destroy): 1 error(s) occurred:

* aws_subnet.default: Error deleting subnet: timeout while waiting for state to become 'destroyed' (last state: 'pending', timeout: 5m0s)
* aws_security_group.default (destroy): 1 error(s) occurred:

* aws_security_group.default: DependencyViolation: resource sg-745ead0f has a dependent object
        status code: 400, request id: 9620cd96-02a5-4d2f-9664-437d663107c0

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by ndegory** [comment]
Terraform is trying to destroy the resources it has created (VPC, subnet, bootstrapped instances = managers). But Swarm worker nodes have been created by InfraKit in the same VPC, so the subnet destruction is timing out, it won't destroy it if there's still network interfaces on it.
The way to clean the cluster is to first tell Infrakit to destroy the group it manages, and then destroy the bootstrap with terraform destroy.

If you don't have access to InfraKit anymore (you've already started the destruction with Terraform, or you never had access to the instance running InfraKit), you can still destroy the worker nodes from the AWS console.
