### ISSUE TITLE
Update Kafka image to latest stable version (10.0.0.1)

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#86]
current image is 10.0.0.0, many fixes in the minor point update:
https://archive.apache.org/dist/kafka/0.10.0.1/RELEASE_NOTES.html

**Comment by subfuzion** [comment]
@ndegory thanks. So is the [commit](https://github.com/appcelerator/docker-kafka/commit/1bb575d5dc14429cd57154d2c85b4553c6cb0aa7) what [latest](https://hub.docker.com/r/appcelerator/kafka/tags/) is now? We should lock down the [tag](https://github.com/appcelerator/amp/blob/master/swarm#L24) (like we did for the tick stack) and continue that process for all our dependencies now.

**Comment by ndegory** [comment]
Not latest, I didn't want to push it until the PR is accepted.
But the PR pushed a tag amp-issue-86. There's no unit test on this repo so I didn't want to tag it with a version on Docker hub.
Update: tag amp-issue-86 has also been copied to 10.0.0.1, and I made a copy of latest to 10.0.0.0.

**Comment by subfuzion** [comment]
👍
