### ISSUE TITLE
AMP labels

### ISSUE THREAD

**Issue by bquenin** [appcelerator-archive/amp#954]
We need to create a document specifying which labels are used for what. Today, we have the following labels:

Resource | Name | Values | Description
--- | --- | --- | ---
container | `io.amp.role` | [`infrastructure`, `tool` ] | Set on amp containers to describe their role |
service | `io.amp.mapping` | `[name]:[port]` | to declare a proxy http mapping between name (in host name) and port to be used |
daemon | `atomiq.clusterid` | Cluster ID | Docker engine label for the local bootstrap cluster |
daemon | `infrakit.group` |  InfraKit group name | Docker engine label for the local bootstrap cluster (is an EC2 tag on AWS cluster deployment) |

Resource type for labels: https://docs.docker.com/engine/userguide/labels-custom-metadata/

**Comment by bquenin** [comment]
@appcelerator/amp Please feel free to complete the table with all the labels we're using

**Comment by freignat91** [comment]
the `pkg/labels/labels.go` file contains all the label names and values declaration
