### ISSUE TITLE
Registry mirror is unable to resolve tag to a digest

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#957]
When updating stacks on a cluster with the mirror registry, all service updates with an image from Docker Hub (not pushed on the local registry) raise a warning: `unable to pin image appcelerator/elasticsearch-amp:5.3.0 to digest: manifest unknown: manifest unknown`
This is fine with versioned images, but could be an issue with unstable tags (`latest`).

**Comment by bquenin** [comment]
Shouldn't we push all the images to the local registry then ?

**Comment by ndegory** [comment]
the message appears when we declare mirror registries, Docker tries to pin the image but is not using all the mirrors plus the official hub. It seems only one registry is tried and if the image is not there we see that message. Pushing all images in the first mirror registry would make this message disappear but that wouldn't make sense, we're better with a real pass-through registry, and we would have to repeat that process with all public images from user stacks...
