### ISSUE TITLE
CLI output when not logged in

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#959]
#### whoami
```
$ amp whoami
Logged in as user: ampuser
```

Desired output:

    You are not logged in. Use `amp login` or `amp user signup`.

#### logs
```
$ amp logs
Error: invalid credentials
```

Desired output:

    Error: not authorized. Please log in.

#### stats
```
$ amp stats
Error: rpc error: code = Unauthenticated desc = invalid credentials
```

Desired output:

    Error: not authorized. Please log in.

**Comment by bquenin** [comment]
Just a comment for:
```
$ amp whoami
Logged in as user: ampuser
```
Make sure you deleted the `~/.config/amp/token` or you're considered logged in.

**Comment by subfuzion** [comment]
Ah, yes, I forgot you used my laptop for a demo and created that user. It shows the correct error without the token. I still think adding the extra hint is good, though.
