### ISSUE TITLE
Telegraf: it misses some io stats data

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#97]
regarding Influx data, for the same timestamp and container_id, it misses some data in docker_container_blkio
It seems related to telegraf

**Comment by ndegory** [comment]
I don't think it should be considered as a bug.
I had a look at docker stats (uses the same data as the docker input plugin of telegraf), some containers don't show any IO (they don't have to).
When a container does not have IO, the docker_container_blkio metric is not sent.
On all the containers of the stack I guess some of them don't have IO, which explains the difference of number of lines between docker_container_blkio and docker_container_mem for instance.

So it's safe to replace missing values by zeros.

**Comment by subfuzion** [comment]
I agree, and showing `0 B` for block I/O is reasonable. Also note that `docker stats` will show `--` when data has not been received in time, vs. `0 B` (or whatever the appropriate unit is) when a specific metric is empty or missing.

**Comment by freignat91** [comment]
ok, I close the issue
