### ISSUE TITLE
replace nginx by haproxy

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#98]
Add new service amp haproxy service having the same behavior than the current nginx service
and remove nginx amp service

**Comment by freignat91** [comment]
created repo: https://github.com/appcelerator/docker-haproxy
to create appcelerator/haproxy image having same behavior than appcelerator/amp

**Comment by subfuzion** [comment]
Thanks @freignat91. Unfortunately, it looks like the [Docker Hub builds](https://hub.docker.com/r/appcelerator/haproxy/builds) are failing.

**Comment by freignat91** [comment]
Yes, it missed the Docker hub build key. It's ok now, the image is built.

**Comment by subfuzion** [comment]
👍
