### ISSUE TITLE
Create proxy service for mapping public service IPs

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#99]
An API to talk to an "ha proxy service" that can be used to dynamically configure a reverse proxy for services that we want to map to a public port

**Comment by subfuzion** [comment]
You are too fast! (In a good way!) 😄  When I talked to you about this on slack, I just wanted to start a brainstorming process and think through the design, but I didn't want to distract you before today's deadline! I should know better. Thanks, Francois! 👍

**Comment by freignat91** [comment]
To start discussion, I reported there the sort discussion we had on slack:

Tony Pujals [2:30 AM] 
if you have some time to put some thought into this today, there is something that would be awesome: an ha proxy service ... in other words, an API to talk to an "ha proxy service" that can be used to dynamically configure a reverse proxy for services that we want to map to a public port

FR:
About HAProxy, what could be cool is to have the amp services information stored in ETCD (the format you want according to the amp service 'service') and have a docker HAProxy service which run container(s) having HAProxy and a little go  program to control HAProxy configuration. Let's call it HAProxy controller.
The HAProxy controller could wait for any updates of the amp services using ETCD api (keys added, keys removed, key updated) and then rebuild the HAProxy configuration accordingly and ask HAProxy to load the new configuration. 
That could be a good start. So we'll have to implement:
- the HAProxy configuration controller (on HAProxy container side)
- the amp 'haproxy' service to declare/remove external service (edited)
  Both of them will work only with ETCD

Tony Pujals:
yes using etcd is the plan for storing all state and configuration. There are two ways to consider the service 1) as an agent, as you described that monitors etcd; or 2) as a service that we tell what to do exposed from amp. There are pros and cons of both ways. But if we first make it a service that we can control, then we can also later build an agent that monitors etcd that can call the amp proxy service (or else use the same package directly). We can brainstorm more after monday.

**Comment by ndegory** [comment]
@freignat91 did you get a look at https://github.com/docker/dockercloud-haproxy ? Maybe we can reuse part of it.

**Comment by subfuzion** [comment]
@ndegory Very good suggestion.

**Comment by freignat91** [comment]
Yes, i'm looking at it to see the way it works.

**Comment by freignat91** [comment]
Prototype #120 done
Waiting for consensus/decision to continue
